Repository protocolbuffers/protobuf, pull requests merged in 2018-08, with the labels that each got.

#4991 Merge 3.6.x branch into master
  CHANGES.txt
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/tests/generated_class_test.php
  protoc-artifacts/README.md
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/google-protobuf.gemspec
  ruby/tests/encode_decode_test.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: no

#4990 Added support for building the aarch64 and ppcle64 protoc binaries with Kokoro
  kokoro/release/protoc/linux/build.sh
  protoc-artifacts/README.md
Labels: cla: yes

#4985 adding of hyperlink of the PHP in the readme.md
  php/README.md
Labels: cla: yes, cleanup, php

#4997 Backport building C# nuget to 3.6.x branch
  csharp/global.json
  kokoro/linux/prepare_build_linux_rc
  kokoro/release/csharp/windows/build_nuget.bat
  kokoro/release/csharp/windows/release.cfg
Labels: cla: yes

#5000 Update php package.xml to 3.6.1
  php/ext/google/protobuf/package.xml
Labels: cla: yes

#5001 Fix spelling error of __GNUC_MINOR__
  src/google/protobuf/stubs/hash.h
Labels: cla: yes, kokoro:run

#5005 Ignore python .egg file to make git status clean #5004
  .gitignore
Labels: cla: yes

#5011 Add header needed for module maps.
  objectivec/GPBUnknownField.m
Labels: cla: yes

#5002 Python wheel kokoro dev
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/linux/config.sh
  kokoro/release/python/linux/release.cfg
Labels: cla: yes, packaging & distribution, python

#5010 #4593 Replace all occurrences of "NULL" to nullptr in src/google/proto…
  src/google/protobuf/stubs/bytestream.cc
  src/google/protobuf/stubs/casts.h
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/stubs/common_unittest.cc
  src/google/protobuf/stubs/io_win32.cc
  src/google/protobuf/stubs/io_win32_unittest.cc
  src/google/protobuf/stubs/logging.h
  src/google/protobuf/stubs/map_util.h
  src/google/protobuf/stubs/mutex.h
  src/google/protobuf/stubs/singleton.h
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/stubs/stl_util.h
  src/google/protobuf/stubs/stringpiece.cc
  src/google/protobuf/stubs/stringpiece.h
  src/google/protobuf/stubs/stringpiece_unittest.cc
  src/google/protobuf/stubs/stringprintf.cc
  src/google/protobuf/stubs/stringprintf_unittest.cc
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/stubs/strutil_unittest.cc
  src/google/protobuf/stubs/substitute.cc
  src/google/protobuf/stubs/substitute.h
  src/google/protobuf/stubs/time.cc
Labels: c++, cla: yes, cleanup

#4981 Fix js reader.js's skipGroup
  js/binary/reader.js
  js/binary/reader_test.js
  js/package.json
Labels: cla: yes, javascript

#5017 Python wheel kokoro for mac
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/macos/release.cfg
Labels: cla: yes

#5020 Fix broken test of const repeated field iterators
  src/google/protobuf/extension_set_unittest.cc
Labels: cla: yes

#5027 Cleanup kokoro scripts.
  kokoro/linux/build_and_run_docker.sh
  kokoro/linux/pull_request_in_docker.sh
  tests.sh
Labels: cla: yes, cleanup

#4951 Add JS and Protobuf.js benchmark, fix js's reader.skipGroup
  benchmarks/Makefile.am
  benchmarks/README.md
  benchmarks/js/benchmark_suite.js
  benchmarks/js/js_benchmark.js
  benchmarks/protobuf.js/generate_pbjs_files.js
  benchmarks/protobuf.js/protobufjs_benchmark.js
Labels: cla: yes, javascript

#5034 Python wheel kokoro for windows
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/build_single_artifact.bat
  kokoro/release/python/windows/release.cfg
Labels: cla: yes, python

#5032 Fix json parsing of wrapper values
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/upb.c
  php/tests/encode_decode_test.php
Labels: cla: yes, php

#5038 Down-integrate proto2 namespace fix.
  python/google/protobuf/pyext/map_container.cc
  python/google/protobuf/pyext/message.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/command_line_interface.h
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/cpp/cpp_unittest.h
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/compiler/package_info.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/extension_set.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/generated_message_reflection_unittest.cc
  src/google/protobuf/io/package_info.h
  src/google/protobuf/map_entry.h
  src/google/protobuf/message.cc
  src/google/protobuf/message.h
  src/google/protobuf/message_lite.h
  src/google/protobuf/metadata.h
  src/google/protobuf/reflection.h
  src/google/protobuf/reflection_internal.h
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/service.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/text_format.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, cleanup

#5040 Fix bazel test.
  BUILD
  cmake/extract_includes.bat.in
  cmake/tests.cmake
  kokoro/linux/bazel/build.sh
Labels: bazel, cla: yes

#5041 Add status badge for bazel build.
  README.md
  src/README.md
Labels: bazel, cla: yes, cleanup

#5042 Document wrapper non-uses
  src/google/protobuf/wrappers.proto
Labels: cla: yes, documentation

#5039 Disable surrogate check for ucs2
  python/google/protobuf/internal/decoder.py
  python/google/protobuf/internal/message_test.py
Labels: cla: yes, python

#5049 Backport #4854 to 3.6.x
  src/google/protobuf/io/gzip_stream.h
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, cleanup

#5048 Include version information in Windows binaries (backport #4579 for 3.6.x)
  Makefile.am
  cmake/CMakeLists.txt
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/protoc.cmake
  cmake/version.rc.in
Labels: c++, cla: yes, cleanup

#5050 Change deprecated Bazel single file attr param
  protobuf.bzl
Labels: bazel, cla: yes

#5024 Fix TryCreateParentDirectory on Windows
  src/google/protobuf/compiler/command_line_interface.cc
Labels: c++, cla: yes

#5021 Support creating FileDescriptors dynamically from binary data.
  csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs
  csharp/src/Google.Protobuf/Reflection/DescriptorPool.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
Labels: c#, cla: yes, kokoro:run

#5068 Replace repo links.
  CHANGES.txt
  Protobuf.podspec
  README.md
  benchmarks/README.md
  cmake/README.md
  conformance/README.md
  csharp/Google.Protobuf.Tools.nuspec
  csharp/README.md
  csharp/compatibility_tests/v3.0.0/protos/csharp/protos/unittest_issues.proto
  csharp/protos/unittest_issues.proto
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  docs/options.md
  docs/performance.md
  examples/WORKSPACE
  examples/add_person.go
  examples/add_person_test.go
  examples/list_people.go
  examples/list_people_test.go
  generate_changelog.py
  java/compatibility_tests/v2.5.0/test.sh
  java/core/src/test/java/com/google/protobuf/CodedOutputStreamTest.java
  java/pom.xml
  js/README.md
  js/package.json
  kokoro/linux/32-bit/Dockerfile
  kokoro/linux/64-bit/Dockerfile
  kokoro/linux/benchmark/build.sh
  objectivec/GPBCodedInputStream.m
  objectivec/Tests/GPBMessageTests.m
  objectivec/Tests/unittest_objc.proto
  php/tests/compatibility_test.sh
  protoc-artifacts/README.md
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
  python/compatibility_tests/v2.5.0/setup.py
  python/release.sh
  python/release/wheel/protobuf_optimized_pip.sh
  python/setup.py
  ruby/ext/google/protobuf_c/wrap_memcpy.c
  ruby/pom.xml
  src/README.md
  src/google/protobuf/compiler/java/java_file.cc
  src/google/protobuf/proto3_arena_unittest.cc
  src/google/protobuf/util/delimited_message_util.cc
  src/google/protobuf/util/delimited_message_util.h
  src/google/protobuf/util/delimited_message_util_test.cc
  src/google/protobuf/util/field_comparator_test.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
  src/google/protobuf/util/internal/testdata/books.proto
  tests.sh
Labels: cla: yes, cleanup

#5074 Revert changed links in Dockerfiles.
  kokoro/linux/32-bit/Dockerfile
  kokoro/linux/64-bit/Dockerfile
  tests.sh
Labels: cla: yes, cleanup

#5077 Update options.md | fix website url for C# port
  docs/options.md
Labels: cla: yes

#5079 Request new option extension (and update URLs for existing projects)
  docs/options.md
Labels: cla: yes

#5100 Add missing reference to conformanc_test_impl.cc in Makefile
  conformance/Makefile.am
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
Labels: cla: yes, conformance tests

#5095 Fix well known type class not inheriting Message
  php/ext/google/protobuf/protobuf.h
  php/tests/well_known_test.php
Labels: cla: yes
