Repository protocolbuffers/protobuf, pull requests merged in 2018-03, with the labels that each got.

#4355 PHP: fixed typo in message.c
  php/ext/google/protobuf/message.c
Labels: cla: yes

#4354 For encoding upb needs descriptor type instead of type.
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
Labels: cla: yes

#4357 Convert descriptortype to type for upb_msgval_sizeof
  php/ext/google/protobuf/upb.c
Labels: cla: yes

#4373 Sync upb change
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
Labels: cla: yes

#4375 Replace //:protoc and similar default macro arguments with
  BUILD
  protobuf.bzl
Labels: cla: yes

#4347 Revert "Move `compiler/plugin.pb.cc` to libprotobuf with the other WKT sources."
  BUILD
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  src/Makefile.am
Labels: cla: yes

#1333 Replace ancient m4/acx_pthread.m4 with m4/ax_pthread.m4
  configure.ac
  m4/acx_pthread.m4
  m4/ax_pthread.m4
Labels: cla: yes, kokoro:run

#4380 Output *_pb2_grpc.py files when use_grpc_plugin=True
  protobuf.bzl
Labels: cla: yes

#4167 Ruby: Fix scope resolution for MessageExts
  ruby/ext/google/protobuf_c/message.c
Labels: cla: yes

#4378 Revert "Removed mention of Buffer in byteSourceToUint8Array"
  js/binary/utils.js
Labels: cla: yes

#4310 Support using MSVC intrinsics in Log2FloorNonZero
  src/google/protobuf/stubs/port.h
Labels: cla: yes

#4222 Remove 64MB memory limit when deserializing messages in C#
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
Labels: cla: yes

#4370 Objective-C: Check return value on write of raw pointer
  objectivec/GPBCodedOutputStream.m
  objectivec/Tests/GPBCodedOuputStreamTests.m
Labels: cla: yes

#4371 Fix spelling error of __GNUC_MINOR__
  src/google/protobuf/stubs/hash.h
Labels: cla: yes

#4397 Cat the test-suite.log on errors for presubmits
  tests.sh
Labels: cla: yes

#4398 Cat the test-suite.log on errors for presubmits
  tests.sh
Labels: cla: yes

#4345 Allow null value in JSON representation of ListValue
  conformance/conformance_test.cc
  csharp/src/Google.Protobuf.Test/JsonParserTest.cs
  csharp/src/Google.Protobuf/JsonParser.cs
Labels: cla: yes

#4361 Add go benchmark
  benchmarks/Makefile.am
  benchmarks/README.md
  benchmarks/cpp_benchmark.cc
  benchmarks/datasets/google_message1/proto2/benchmark_message1_proto2.proto
  benchmarks/datasets/google_message1/proto2/dataset.google_message1_proto2.pb
  benchmarks/datasets/google_message1/proto3/benchmark_message1_proto3.proto
  benchmarks/datasets/google_message1/proto3/dataset.google_message1_proto3.pb
  benchmarks/go_benchmark_test.go
  benchmarks/py_benchmark.py
Labels: cla: yes

#4412 Removed some unused C++ source files
  BUILD
  cmake/extract_includes.bat.in
  cmake/tests.cmake
  src/Makefile.am
  src/google/protobuf/stubs/atomic_sequence_num.h
  src/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
  src/google/protobuf/stubs/atomicops_internals_arm_gcc.h
  src/google/protobuf/stubs/atomicops_internals_arm_qnx.h
  src/google/protobuf/stubs/atomicops_internals_generic_c11_atomic.h
  src/google/protobuf/stubs/atomicops_internals_generic_gcc.h
  src/google/protobuf/stubs/atomicops_internals_mips_gcc.h
  src/google/protobuf/stubs/atomicops_internals_power.h
  src/google/protobuf/stubs/atomicops_internals_ppc_gcc.h
  src/google/protobuf/stubs/atomicops_internals_solaris.h
  src/google/protobuf/stubs/atomicops_internals_tsan.h
  src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc
  src/google/protobuf/stubs/atomicops_internals_x86_gcc.h
  src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc
  src/google/protobuf/stubs/atomicops_internals_x86_msvc.h
  src/google/protobuf/stubs/once.cc
  src/google/protobuf/stubs/once_unittest.cc
  src/google/protobuf/stubs/shared_ptr.h
  src/google/protobuf/stubs/type_traits.h
  src/google/protobuf/stubs/type_traits_unittest.cc
Labels: cla: yes

#4346 Add performance.md and add instruction for linking tcmalloc
  benchmarks/README.md
  docs/performance.md
Labels: cla: yes

#4421 Added missing .inc files to BUILD
  BUILD
Labels: cla: yes

#4422 Updated Ruby conformance test failure list
  conformance/failure_list_ruby.txt
Labels: cla: yes

#4395 Fix bug: whether always_print_enums_as_ints is true or false, it alwa…
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/internal/default_value_objectwriter.h
  src/google/protobuf/util/json_format_proto3.proto
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/json_util_test.cc
Labels: cla: yes, wait for test result

#4350 Fixes MSVC compiler warning C4800
  src/google/protobuf/generated_message_util.h
  src/google/protobuf/io/coded_stream.h
Labels: cla: yes, wait for test result

#4342 source code info for interpreted options; fix source code info for extension range options
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
Labels: cla: yes, wait for test result

#4434 Remove broken build status icons.
  README.md
Labels: cla: yes

#4432 Delete javanano kokoro build configs.
  kokoro/linux/javanano_jdk7/build.sh
  kokoro/linux/javanano_jdk7/continuous.cfg
  kokoro/linux/javanano_jdk7/presubmit.cfg
  kokoro/linux/javanano_oracle7/build.sh
  kokoro/linux/javanano_oracle7/continuous.cfg
  kokoro/linux/javanano_oracle7/presubmit.cfg
Labels: cla: yes

#3794 Change C# reflection to avoid using expression trees
  Makefile.am
  csharp/src/Google.Protobuf/Compatibility/MethodInfoExtensions.cs
  csharp/src/Google.Protobuf/Reflection/OneofAccessor.cs
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
Labels: cla: yes

#4439 Removed atomicops.h stub
  .gitignore
  src/google/protobuf/stubs/atomicops.h
Labels: cla: yes

#4442 Delete unused directories.
  jenkins/README.md
  jenkins/build_and_run_docker.sh
  jenkins/buildcmds/README.md
  jenkins/buildcmds/pull_request.sh
  jenkins/buildcmds/pull_request_32.sh
  jenkins/docker/Dockerfile
  jenkins/docker32/Dockerfile
  jenkins/make_test_output.py
  jenkins/pull_request_in_docker.sh
  more_tests/Makefile
Labels: cla: yes

#4445 Add kokoro build status badges.
  README.md
Labels: cla: yes

#4433 Cleanup LICENSE file.
  LICENSE
Labels: cla: yes
