Repository protocolbuffers/protobuf, pull requests merged in 2018-09, with the labels that each got.

#5092 Add contributing guidelines.
  CONTRIBUTING.md
Labels: cla: yes, documentation

#5078 Added cmake build files for the conformance test runner.
  Makefile.am
  cmake/CMakeLists.txt
  cmake/conformance.cmake
Labels: cla: yes, conformance tests

#5099 Fixes JSON Loading of Any messages with Unknown Fields in C++
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/internal/protostream_objectwriter.h
  src/google/protobuf/util/json_util_test.cc
Labels: c++, cla: yes, json

#5103 Added conformance test impl file to CMake.
  cmake/conformance.cmake
Labels: cla: yes, conformance tests

#5069 Add source dependency of test suite implementation to main function
  conformance/conformance_test.cc
  conformance/conformance_test.h
  conformance/conformance_test_impl.cc
  conformance/conformance_test_runner.cc
Labels: cla: yes, conformance tests

#5111 Update README.md with gradle instructions for java
  java/README.md
Labels: cla: yes

#5125 Upport kokoro/release/python from 3.6.x branch
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/linux/config.sh
  kokoro/release/python/linux/release.cfg
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/macos/release.cfg
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/build_single_artifact.bat
  kokoro/release/python/windows/release.cfg
Labels: cla: yes, cleanup

#5114 Remove 2to3 code from setup.py.
  python/setup.py
Labels: cla: yes, python

#5122 update to Guava 20
  java/pom.xml
Labels: cla: yes, cleanup, java

#5105 On Windows invoke plugins using cmd.exe
  src/google/protobuf/compiler/subprocess.cc
Labels: c++, cla: yes

#5088 Cross-link descriptor when building from byte strings
  csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
Labels: c#, cla: yes

#5085 Route "compiler" value of config_setting through @bazel_tools/tools/cpp:compiler.
  BUILD
  compiler_config_setting.bzl
Labels: bazel, cla: yes

#5127 Merge 3.6.x branch to master
  php/ext/google/protobuf/package.xml
Labels: cla: yes, cleanup

#5106 Adopt upb change for timestamp and duration json to php
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
Labels: cla: yes, php

#5182 fix java build by changing mvn to online
  tests.sh
Labels: cla: yes

#5180 Dart build status
  README.md
Labels: cla: yes

#4642 C# Proto2 feature : Field presence and default values
  Makefile.am
  csharp/src/AddressBook/Addressbook.cs
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  csharp/src/Google.Protobuf.Test/TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf/Collections/MapField.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
  csharp/src/Google.Protobuf/InvalidProtocolBufferException.cs
  csharp/src/Google.Protobuf/MessageExtensions.cs
  csharp/src/Google.Protobuf/MessageParser.cs
  csharp/src/Google.Protobuf/ProtoPreconditions.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldAccessorBase.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldType.cs
  csharp/src/Google.Protobuf/Reflection/IFieldAccessor.cs
  csharp/src/Google.Protobuf/Reflection/MapFieldAccessor.cs
  csharp/src/Google.Protobuf/Reflection/PartialClasses.cs
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
  csharp/src/Google.Protobuf/Reflection/RepeatedFieldAccessor.cs
  csharp/src/Google.Protobuf/Reflection/SingleFieldAccessor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Api.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Type.cs
  csharp/src/Google.Protobuf/WireFormat.cs
  src/google/protobuf/compiler/csharp/csharp_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.h
  src/google/protobuf/compiler/csharp/csharp_generator.cc
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_helpers.h
  src/google/protobuf/compiler/csharp/csharp_map_field.cc
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message.h
  src/google/protobuf/compiler/csharp/csharp_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
Labels: c#, cla: yes

#5172 Smear comments
  csharp/src/Google.Protobuf/WellKnownTypes/Timestamp.cs
  objectivec/google/protobuf/Timestamp.pbobjc.h
  src/google/protobuf/timestamp.proto
Labels: cla: yes, documentation
