Repository protocolbuffers/protobuf, pull requests merged in 2018-05, with the labels that each got.

#4583 Cygwin build failed
  cmake/CMakeLists.txt
Labels: cla: yes

#4586 MinGW build failed
  src/google/protobuf/stubs/mathlimits.h
Labels: cla: yes

#4530 PHP array constructors for protobuf messages
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto_ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto_ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto_EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo_Annotation.php
  php/src/Google/Protobuf/Internal/Message.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo_Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption_NamePart.php
  php/tests/generated_phpdoc_test.php
  php/tests/php_implementation_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, wait for user action

#4527 Add -std=c++11 for python setup on kokoro
  python/setup.py
Labels: cla: yes

#4128 Add VS2017 optional component dependency details to the C# ReadMe for #4119
  csharp/README.md
Labels: cla: yes

#4590 Fix error in Clang UndefinedBehaviorSanitizer
  src/google/protobuf/io/printer.cc
Labels: cla: yes

#4537 use brew install instead of easy_install in OSX
  tests.sh
Labels: cla: yes

#4601 Avoid direct check of class name
  php/src/Google/Protobuf/Timestamp.php
Labels: cla: yes, php

#4603 Throw error if user want to access message properties
  php/ext/google/protobuf/message.c
  php/tests/test.sh
Labels: cla: yes

#4538 Add .proto files to extract_includes.bat
  cmake/extract_includes.bat.in
  update_file_lists.sh
Labels: cla: yes

#4609 Add file option php_metadata_namespace and ruby_package
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  php/src/GPBMetadata/Google/Protobuf/Internal/Descriptor.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor.proto
Labels: cla: yes

#1329 fix index out of range error in C# generation using msvc
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
Labels: cla: yes

#4611 [Java] Remove unsafe no-copy String allocation since it's not useful in rece…
  java/core/src/main/java/com/google/protobuf/UnsafeUtil.java
  java/core/src/main/java/com/google/protobuf/Utf8.java
Labels: cla: yes

#4587 Appveyor MinGW build
  appveyor.bat
  appveyor.yml
  cmake/tests.cmake
Labels: cla: yes

#4179 enable source link for csharp
  csharp/build_packages.bat
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: cla: yes

#4579 Include version information in Windows binaries #3380
  Makefile.am
  cmake/CMakeLists.txt
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/protoc.cmake
  cmake/version.rc.in
Labels: cla: yes

#4622 Adopt php_metadata_namespace in php code generator
  php/tests/proto/test_empty_php_namespace.proto
  php/tests/proto/test_no_namespace.proto
  php/tests/proto/test_php_namespace.proto
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes

#4623 Fix python install, cat java error log for kokoro build
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#4574 Fix appveyor documentation
  appveyor.yml
Labels: cla: yes, wait for user action

#4632 Fix issue with version.rc
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/protoc.cmake
Labels: cla: yes

#4624 Fix undefined behavior in hash function.
  src/google/protobuf/descriptor.cc
Labels: cla: yes

#4631 Fix 4615
  configure.ac
Labels: cla: yes

#4619 cmake: protobuf_generate fix GENERATE_EXTENSIONS, fix DEPENDS, add PROTOC_OUT_DIR
  cmake/protobuf-config.cmake.in
Labels: cla: yes

#4633 re-write int128 long division to avoid license impact from stackoverflow references
  src/google/protobuf/stubs/int128.cc
Labels: cla: yes

#4627 Adopt ruby_package in ruby generated code.
  .gitignore
  ruby/Rakefile
  ruby/tests/generated_code_test.rb
  ruby/tests/test_ruby_package.proto
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes

#4644 Updated PHP generated code for timestamp.proto
  php/src/Google/Protobuf/Timestamp.php
Labels: cla: yes

#4650 remove PACKAGE_NAME and REPOSITORY_NAME deprecated usage
  protobuf.bzl
Labels: cla: yes

#4634 Fix java benchmark bug, fix python lib cache
  benchmarks/Makefile.am
  benchmarks/java/pom.xml
  benchmarks/java/src/main/java/com/google/protobuf/ProtoCaliperBenchmark.java
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#4252 Allows the Ruby json marshaller to be passed json marshal options
  ruby/lib/google/protobuf.rb
  ruby/lib/google/protobuf/message_exts.rb
  ruby/tests/encode_decode_test.rb
Labels: cla: yes

#3984 Windows: expand wildcard arguments
  BUILD
Labels: cla: yes, wait for user action

#4660 Fix python benchmark build
  benchmarks/Makefile.am
Labels: cla: yes

#4620 CMake OSX rpath management
  cmake/CMakeLists.txt
  cmake/install.cmake
Labels: cla: yes, wait for user action

#4663 Add missing ruby/tests/test_ruby_package.proto
  Makefile.am
Labels: cla: yes

#4667 Fix array constructor in c extension for compatibility
  php/ext/google/protobuf/message.c
Labels: cla: yes

#4669 Fix syntax error in BUILD file
  BUILD
Labels: cla: yes

#4674 Add kokoro configs for bazel build.
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel/continuous.cfg
  kokoro/linux/bazel/presubmit.cfg
Labels: cla: yes

#4659 Declare 'google' namespace when importing Python protobuf via Bazel
  BUILD
Labels: cla: yes, python

#4677 Remove jruby from kokoro tests
  README.md
  kokoro/macos/jruby/build.sh
  kokoro/macos/jruby/continuous.cfg
  kokoro/macos/jruby/presubmit.cfg
Labels: cla: yes

#4684 Always add -std=c++11 for mac
  python/setup.py
Labels: cla: yes

#4687 Fixed JS parsing of unspecified map keys
  js/map.js
  js/maps_test.js
  js/testbinary.proto
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes

#4678 Add ability to introspect list of enum values
  objectivec/GPBDescriptor.h
  objectivec/GPBDescriptor.m
  objectivec/README.md
  objectivec/Tests/GPBDescriptorTests.m
Labels: cla: yes, objective-c

#4692 Fix php memory leak test
  php/ext/google/protobuf/def.c
  php/tests/memory_leak_test.php
Labels: cla: yes

#4695 Fix php memory leak test (#4692)
  php/ext/google/protobuf/def.c
  php/tests/memory_leak_test.php
Labels: cla: yes

#4697 Move methods out of class
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes

#4696 Removed duplicate using statement from ReflectionUtil.cs
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
Labels: cla: yes

#4676 Updated generate_changelog.py
  generate_changelog.py
Labels: cla: yes

#4702 Cherry-pick changes into 3.6.x
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes

#4703 Added Clang thread-safety annotations in mutex.h
  src/google/protobuf/stubs/mutex.h
Labels: cla: yes

#4706 Require C++11 and pass -std=c++11
  configure.ac
Labels: cla: yes
