Repository protocolbuffers/protobuf, pull requests merged in 2018-11, with the labels that each got.

#5308 Collapse :protobuf_objc and :objectivec targets.
  BUILD
Labels: cla: yes

#5310 Add more Xcode versions to the objc build script.
  objectivec/DevTools/full_mac_build.sh
Labels: cla: yes

#5309 Support suppressing the objc package prefix checks on a list of files.
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes

#5312 Let the 9.4 migrator migrate the Swift source.
  objectivec/DevTools/full_mac_build.sh
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
Labels: cla: yes

#5275 Added safety checks when malloc returns nil
  objectivec/GPBDescriptor.m
Labels: cla: yes, objective-c

#5183 C# Proto2 feature : Groups
  csharp/src/AddressBook/Addressbook.cs
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  csharp/src/Google.Protobuf.Test/TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestImportProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestImportPublicProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/CodedOutputStream.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/UnknownField.cs
  csharp/src/Google.Protobuf/UnknownFieldSet.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Any.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Api.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Duration.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Empty.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMask.cs
  csharp/src/Google.Protobuf/WellKnownTypes/SourceContext.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Struct.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Timestamp.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Type.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Wrappers.cs
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.cc
Labels: cla: yes

#5314 3rd-party: include Protolock utility
  docs/third_party.md
Labels: cla: yes

#5261 Add Dart example.
  examples/Makefile
  examples/README.md
  examples/add_person.dart
  examples/list_people.dart
  examples/pubspec.yaml
Labels: cla: yes

#5289 Fix bugs in our keyword conversion support for objectivec
  objectivec/Tests/GPBMessageTests.m
  objectivec/Tests/unittest_objc.proto
  src/Makefile.am
  src/google/protobuf/compiler/objectivec/method_dump.sh
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_nsobject_methods.h
Labels: cla: yes, objective-c

#5316 Add wire_format_lite_inl.h include to implicit_weak_message.cc
  src/google/protobuf/implicit_weak_message.cc
Labels: cla: yes

#5319 options: reserved extension range for CSI
  docs/options.md
Labels: cla: yes

#5117 add BOM
  java/bom/pom.xml
  java/pom.xml
  java/util/pom.xml
Labels: cla: yes, java

#5298 Import versions from @bazel_skylib//lib:versions.bzl
  examples/WORKSPACE
  protobuf.bzl
Labels: cla: yes

#5295 Remove superfluous const from return type in json_stream_parser.h
  src/google/protobuf/util/internal/json_stream_parser.h
Labels: c++, cla: yes

#5303 Use libc++ for xcode 10(python-wheel-kokoro-dev branch)
  python/setup.py
Labels: cla: yes, kokoro:force-run, kokoro:run, python

#5296 Add missing include guard to zip_writer.h
  src/google/protobuf/compiler/zip_writer.h
Labels: c++, cla: yes

#5339 Increase C# default recursion limit to 100
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
Labels: cla: yes

#5323 compiler/cpp: replace NULL with nullptr
  src/google/protobuf/any.pb.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.cc
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_enum_field.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_map_field.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/cpp/cpp_string_field.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.cc
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.cc
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes

#5355 Fix up the Xcode project.
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
Labels: cla: yes

#5348 Removed stubs/singleton.h
  Makefile.am
  src/google/protobuf/stubs/singleton.h
Labels: cla: yes

#5359 In debug builds output a warning about NSCoding and extensions.
  objectivec/GPBMessage.m
Labels: cla: yes

#5360 Improve comment about warning being incomplete.
  objectivec/GPBMessage.m
Labels: cla: yes

#5363 Make sure to install stubs/strutil.h
  src/Makefile.am
Labels: cla: yes

#5367 Migrate to new `ctx.actions` API
  protobuf.bzl
Labels: cla: yes

#5366 Updated README.md
  cmake/README.md
Labels: cla: yes

#5313 Fix most of the unused variable warnings in Ruby tests
  ruby/tests/common_tests.rb
  ruby/tests/encode_decode_test.rb
  ruby/tests/generated_code_proto2_test.rb
  ruby/tests/generated_code_test.rb
Labels: cla: yes, ruby

#5379 ObjC: small improvement to extension serialization.
  objectivec/GPBMessage.m
Labels: cla: yes, objective-c

#5368 Some changes to the ObjC code generator to support importing into Google.
  src/google/protobuf/compiler/objectivec/objectivec_enum.h
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.h
  src/google/protobuf/compiler/objectivec/objectivec_extension.h
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_field.h
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_map_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_map_field.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
  src/google/protobuf/compiler/objectivec/objectivec_message_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_message_field.h
  src/google/protobuf/compiler/objectivec/objectivec_oneof.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.h
Labels: cla: yes

#5322 [protobuf/objc] Introduce a protobuf-specific deprecation annotation ⚠️
  objectivec/GPBBootstrap.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c

#5378 Actualizing RubyGems link in README.md
  ruby/README.md
Labels: cla: yes

#5142 Mostly fix Sun Studio configuration using SunCC compiler (GH #5141)
  m4/acx_check_suncc.m4
  src/google/protobuf/generated_message_util.cc
  src/google/protobuf/stubs/common.cc
Labels: autotools, c++, cla: yes, wait for user action

#5386 Update add_person.dart
  examples/add_person.dart
Labels: cla: yes

#5382 Cherry-picked Bazel fix from PR #5085
  BUILD
  compiler_config_setting.bzl
Labels: cla: yes, kokoro:run

#5267 fix json_format.ParseDict modifies input
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/json_format.py
Labels: cla: yes

#5375 Add overrides in C++ code.
  src/google/protobuf/reflection_internal.h
  src/google/protobuf/util/internal/default_value_objectwriter.h
  src/google/protobuf/util/internal/json_objectwriter.h
  src/google/protobuf/util/json_util.cc
Labels: cla: yes

#5391 Make sure Objective C Proto compiler doesn't "duplicate" prefixes
  Makefile.am
  objectivec/DevTools/compile_testing_protos.sh
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/Tests/GPBMessageTests.m
  objectivec/Tests/unittest_objc_options.proto
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c

#5398 Avoid octal constants in strutil.cc
  src/google/protobuf/stubs/strutil.cc
Labels: cla: yes, kokoro:run

#5342 PHP: Add Enum methods for converting to/from strings
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/src/Google/Protobuf/Field/Cardinality.php
  php/src/Google/Protobuf/Field/Kind.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto/Label.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto/Type.php
  php/src/Google/Protobuf/Internal/FieldOptions/CType.php
  php/src/Google/Protobuf/Internal/FieldOptions/JSType.php
  php/src/Google/Protobuf/Internal/FileOptions/OptimizeMode.php
  php/src/Google/Protobuf/Internal/MethodOptions/IdempotencyLevel.php
  php/src/Google/Protobuf/NullValue.php
  php/src/Google/Protobuf/Syntax.php
  php/tests/generated_class_test.php
  php/tests/well_known_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php

#5406 Change MACOSX_DEPLOYMENT_TARGET to 10.9
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/windows/build_artifacts.bat
  python/setup.py
Labels: cla: no

#5404 Cherry-picked fix from PR #4650 into 3.6.x branch
  protobuf.bzl
Labels: cla: yes
