Repository protocolbuffers/protobuf, pull requests merged in 2018-06, with the labels that each got.

#4710 Upport to master: Require C++11 and pass -std=c++11
  configure.ac
Labels: cla: yes

#4709 Remove js_embed binary.
  .gitignore
  BUILD
  cmake/libprotoc.cmake
  src/Makefile.am
  src/google/protobuf/compiler/js/embed.cc
  src/google/protobuf/compiler/js/well_known_types_embed.cc
Labels: cla: yes

#4714 Add reference to protobuf-d
  docs/third_party.md
Labels: cla: yes

#4698 Introduce Proto C API; based on cl/198113115 by amauryfa
  BUILD
  Makefile.am
  python/google/protobuf/proto_api.h
  python/google/protobuf/pyext/message.cc
  python/google/protobuf/pyext/message.h
  python/google/protobuf/pyext/message_module.cc
Labels: cla: yes

#4729 Update code to work for Xcode 10b1
  objectivec/DevTools/full_mac_build.sh
  objectivec/GPBArray.m
  objectivec/GPBDescriptor.m
  objectivec/GPBDictionary.m
  objectivec/README.md
Labels: cla: yes

#4720 Align Bazel on Windows with CMake's MSVC flags
  BUILD
Labels: cla: yes

#4730 Cherry-picked XCode 10 fixes into 3.6.x branch
  objectivec/DevTools/full_mac_build.sh
  objectivec/GPBArray.m
  objectivec/GPBDescriptor.m
  objectivec/GPBDictionary.m
  objectivec/README.md
Labels: cla: yes

#4713 Updated the change log with changes for 3.6.0
  CHANGES.txt
  post_process_dist.sh
Labels: cla: yes

#4736 Update php version to 3.6.0
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes

#4741 Use legacy name in php runtime
  php/src/Google/Protobuf/Internal/Descriptor.php
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/src/Google/Protobuf/Internal/EnumDescriptor.php
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/src/Google/Protobuf/Internal/MapField.php
  php/src/Google/Protobuf/Internal/RepeatedField.php
  php/tests/compatibility_test.sh
Labels: cla: yes

#3507 import inspect
  python/stubout.py
Labels: cla: yes

#3901 Fix unused parameter warnings in generated code with arenas enabled
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/descriptor.pb.cc
Labels: cla: yes

#2811 Java: Mark sun.misc dependency as optional
  java/core/pom.xml
Labels: cla: yes, java

#4758 Migrate to supported version of http_archive
  WORKSPACE
Labels: cla: yes

#4748 Make proto_api target visible
  BUILD
Labels: cla: yes

#4755 Fix incorrect link.
  benchmarks/README.md
Labels: cla: yes

#4766 Added Kokoro Windows release build config for protoc
  kokoro/release/protoc/windows/build.bat
  kokoro/release/protoc/windows/release.cfg
Labels: cla: yes

#4777 Work around MSVC issue with std::atomic initialization
  appveyor.yml
  src/google/protobuf/generated_message_util.h
Labels: cla: yes

#4739 Graceful failure in SerializeToArray().
  src/google/protobuf/message_lite.cc
Labels: cla: yes

#4707 proto_writer.h: RenderBytes is an override. Marking it.
  src/google/protobuf/util/internal/proto_writer.h
Labels: cla: yes

#4770 Added Kokoro protoc release build for OS X
  kokoro/release/protoc/macos/build.sh
  kokoro/release/protoc/macos/release.cfg
Labels: cla: yes

#2121 issue-2108 [protoc/Java] Excessive copying on buildPartial()
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_lazy_message_field.cc
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_string_field.cc
Labels: cla: yes, java

#4626 Declare some generated C++ methods as static #4602
  src/google/protobuf/any.pb.cc
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes

#4306 Update third_party.md
  docs/third_party.md
Labels: cla: yes

#4792 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: cla: yes

#4533 PHP typehints for message setters
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php

#4797 Fix typo in the doc
  docs/performance.md
Labels: cla: yes

#4780 check provided size to check whether to export
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes

#1261 Disable thread local storage for OSX < 10.7
  src/google/protobuf/stubs/platform_macros.h
Labels: cla: yes

#4754 print() is a function in Python 3
  benchmarks/python/py_benchmark.py
  benchmarks/util/big_query_utils.py
  benchmarks/util/run_and_upload.py
Labels: cla: yes

#4811 json: include field name in InvalidName status messages.
  src/google/protobuf/util/json_util.cc
Labels: c++, cla: yes, json

#4648 Add msbuild targets to C# tools for protoc compilers
  Makefile.am
  csharp/Google.Protobuf.Tools.nuspec
  csharp/Google.Protobuf.Tools.targets
Labels: c#, cla: yes

#4812 protostream_objectsource: preserve print options across Any.
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectsource_test.cc
  src/google/protobuf/util/internal/testdata/books.proto
Labels: c++, cla: yes, json

#4813 protostream_objectwriter: fix bug when Any is directly embedded in a …
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
  src/google/protobuf/util/internal/testdata/maps.proto
  src/google/protobuf/util/json_util_test.cc
Labels: c++, cla: yes, json

#4815 Fix parameters declaration
  src/google/protobuf/generated_message_util.h
Labels: c++, cla: yes

#4818 Rename build_artifacts.cfg to release.cfg
  kokoro/release/macos/release.cfg
Labels: cla: yes

#4168 Use versions module from Skylib for version checking
  WORKSPACE
  protobuf.bzl
Labels: bazel, cla: yes

#2470 update ScalaPB url
  docs/third_party.md
Labels: cla: yes

#4753 global __version__ in setup.py
  python/setup.py
Labels: cla: yes, python

#4819 Build ruby gem on kokoro
  kokoro/release/linux/build_artifacts.sh
  kokoro/release/linux/prepare_build.sh
  kokoro/release/linux/release.cfg
  kokoro/release/linux/ruby/ruby_build.sh
  kokoro/release/linux/ruby/ruby_build_environment.sh
  kokoro/release/macos/ruby/ruby_build_environment.sh
  ruby/ext/google/protobuf_c/extconf.rb
Labels: cla: yes, ruby

#4172 Add guards against bswap_XX redefnitions
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes

#4608 Add "override" keyword for overridden virtual functions
  src/google/protobuf/compiler/importer.cc
  src/google/protobuf/compiler/importer.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/dynamic_message.cc
  src/google/protobuf/dynamic_message.h
  src/google/protobuf/extension_set.h
  src/google/protobuf/extension_set_heavy.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/io/zero_copy_stream_impl.h
  src/google/protobuf/io/zero_copy_stream_impl_lite.h
  src/google/protobuf/map_entry.h
  src/google/protobuf/map_entry_lite.h
  src/google/protobuf/map_field.h
  src/google/protobuf/message.cc
  src/google/protobuf/message.h
  src/google/protobuf/reflection_internal.h
  src/google/protobuf/stubs/bytestream.h
  src/google/protobuf/stubs/callback.h
  src/google/protobuf/text_format.cc
  src/google/protobuf/util/field_comparator.h
  src/google/protobuf/util/internal/default_value_objectwriter.h
  src/google/protobuf/util/internal/error_listener.h
  src/google/protobuf/util/internal/json_objectwriter.h
  src/google/protobuf/util/internal/object_location_tracker.h
  src/google/protobuf/util/internal/proto_writer.h
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/internal/protostream_objectwriter.h
  src/google/protobuf/util/internal/type_info.cc
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/json_util.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/message_differencer.h
  src/google/protobuf/util/type_resolver_util.cc
  src/google/protobuf/wire_format.h
  src/google/protobuf/wire_format_lite.h
Labels: c++, cla: yes

#4826 Fixed protobuf_generate output definition
  cmake/protobuf-config.cmake.in
Labels: cla: yes, cmake

#4824 Remove the executable bit from several source code files
  benchmarks/java/pom.xml
  benchmarks/java/src/main/java/com/google/protobuf/ProtoCaliperBenchmark.java
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf.Test/Compatibility/StreamExtensionsTest.cs
  csharp/src/Google.Protobuf.Test/Compatibility/TypeExtensionsTest.cs
  csharp/src/Google.Protobuf.Test/FieldCodecTest.cs
  csharp/src/Google.Protobuf/ByteString.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
  csharp/src/Google.Protobuf/Compatibility/PropertyInfoExtensions.cs
  csharp/src/Google.Protobuf/Compatibility/StreamExtensions.cs
  csharp/src/Google.Protobuf/Compatibility/TypeExtensions.cs
  csharp/src/Google.Protobuf/JsonFormatter.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMaskPartial.cs
  src/google/protobuf/arena.cc
  src/google/protobuf/arenastring.h
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/js/js_generator.h
  src/google/protobuf/reflection.h
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/util/message_differencer_unittest.cc
Labels: cla: yes, cleanup

#3669 rename duplicate testMessageSetNullFail function
  php/tests/undefined_test.php
Labels: cla: yes, php

#4207 Update minimal Python version to 2.7
  python/README.md
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/json_format.py
  python/setup.py
Labels: cla: yes, python

#4817 Remove protoc conditional properties
  csharp/Google.Protobuf.Tools.targets
Labels: c#, cla: yes

#4827 Merge 3.6.x branch into master
  CHANGES.txt
  Protobuf.podspec
  appveyor.yml
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/map.js
  js/maps_test.js
  js/package.json
  js/testbinary.proto
  kokoro/release/linux/build_artifacts.sh
  kokoro/release/linux/prepare_build.sh
  kokoro/release/linux/release.cfg
  kokoro/release/linux/ruby/ruby_build.sh
  kokoro/release/linux/ruby/ruby_build_environment.sh
  kokoro/release/macos/build_artifacts.sh
  kokoro/release/macos/release.cfg
  kokoro/release/macos/ruby/ruby_build.sh
  kokoro/release/macos/ruby/ruby_build_environment.sh
  kokoro/release/protoc/macos/build.sh
  kokoro/release/protoc/macos/release.cfg
  kokoro/release/protoc/windows/build.bat
  kokoro/release/protoc/windows/release.cfg
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/src/Google/Protobuf/Internal/Descriptor.php
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/src/Google/Protobuf/Internal/EnumDescriptor.php
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/src/Google/Protobuf/Internal/MapField.php
  php/src/Google/Protobuf/Internal/RepeatedField.php
  php/tests/compatibility_test.sh
  post_process_dist.sh
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/setup.py
  ruby/ext/google/protobuf_c/extconf.rb
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/generated_message_util.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, cleanup

#4828 Removed forward declaration of MemBlock class
  src/google/protobuf/stubs/bytestream.h
Labels: cla: no

#4830 Add -Og to no-warning-test
  src/Makefile.am
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_enum_field.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/wrappers.pb.cc
Labels: c++, cla: yes, cleanup

#4836 Fix capsule name.
  python/google/protobuf/proto_api.h
Labels: cla: yes, python

#4846 Fix to allow a compilation under mips big endian with gcc
  src/google/protobuf/stubs/platform_macros.h
Labels: cla: yes
