Repository protocolbuffers/protobuf, pull requests merged in 2018-04, with the labels that each got.

#4452 Update instructions about getting protobuf source.
  cmake/README.md
  src/README.md
Labels: cla: yes

#4447 Cleaner protoc artifacts
  protoc-artifacts/Dockerfile
  protoc-artifacts/README.md
  protoc-artifacts/scl-enable-devtoolset.sh
Labels: cla: yes

#4411 Add support for Power (ppc64le) arch
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
Labels: cla: yes

#4467 Improve error message when googletest is missing.
  cmake/tests.cmake
Labels: cla: yes

#4332 js message support for jstype string on integers
  js/message.js
Labels: cla: yes

#4466 Merge branch
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/setup.py
  ruby/google-protobuf.gemspec
Labels: cla: yes

#4283 [C#] Update test project to be used with dotnet test and Visual Studio Test Explorer
  Makefile.am
  appveyor.bat
  csharp/README.md
  csharp/buildall.sh
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Test/Program.cs
Labels: cla: yes

#4475 Fix problem: cmake build failed in c++11 by clang
  cmake/CMakeLists.txt
Labels: cla: yes

#4449 Deliberately call simple code to avoid Unity linker pruning
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
Labels: cla: yes

#4485 Update Xcode settings
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
Labels: cla: yes

#4486 Add the files added in #4485.
  Makefile.am
Labels: cla: yes

#4468 For windows, all python version should use /MT
  python/setup.py
Labels: cla: yes

#4117 Add __init__.py files to compiler and util subpackages
  .gitignore
  Makefile.am
  python/google/protobuf/compiler/__init__.py
  python/google/protobuf/util/__init__.py
  python/setup.py
Labels: cla: yes

#3371 includes the expected class in the exception, otherwise the error is …
  php/src/Google/Protobuf/Internal/GPBUtil.php
Labels: cla: yes

#4381 fix json_decode call parameters
  php/src/Google/Protobuf/Internal/Message.php
Labels: cla: yes, kokoro:run

#4478 Add gogo benchmark
  benchmarks/Makefile.am
  benchmarks/python/__init__.py
  benchmarks/python/py_benchmark.py
  benchmarks/util/gogo_data_scrubber.cc
  benchmarks/util/protoc-gen-gogoproto.cc
  benchmarks/util/schema_proto2_to_proto3_util.h
Labels: cla: yes

#4510 fix java benchmark, fix dashboard build
  benchmarks/Makefile.am
  benchmarks/java/src/main/java/com/google/protobuf/ProtoBench.java
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#4517 Fixed a Visual Studio 2017 build error. (#4488)
  src/google/protobuf/compiler/cpp/cpp_field.cc
  src/google/protobuf/compiler/cpp/cpp_field.h
  src/google/protobuf/compiler/java/java_field.cc
  src/google/protobuf/compiler/java/java_field.h
  src/google/protobuf/compiler/java/java_file.cc
  src/google/protobuf/compiler/java/java_file.h
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_field.h
Labels: cla: yes

#4504 Cleanup + documentation for Java Lite runtime.
  Makefile.am
  java/README.md
  java/lite.md
  java/lite/generate-sources-build.xml
  java/lite/generate-test-sources-build.xml
  java/lite/pom.xml
  java/pom.xml
  src/google/protobuf/compiler/java/java_file.cc
Labels: cla: yes

#4520 Fix benchmark build
  benchmarks/Makefile.am
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#4542 Remove the iOS Test App.
  Makefile.am
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  objectivec/Tests/iOSTestHarness/AppDelegate.m
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/Contents.json
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_1024.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_120.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_152.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_167.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_180.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_20.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_29.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_40.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_58.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_60.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_76.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_80.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/AppIcon.appiconset/appicon_87.png
  objectivec/Tests/iOSTestHarness/Images.xcassets/LaunchImage.launchimage/Contents.json
  objectivec/Tests/iOSTestHarness/Info.plist
  objectivec/Tests/iOSTestHarness/LaunchScreen.xib
  objectivec/Tests/iOSTestHarness/en.lproj/InfoPlist.strings
Labels: cla: yes

#4543 Move to Xcode 9.3 which also means a High Sierra image.
  .travis.yml
  objectivec/DevTools/full_mac_build.sh
Labels: cla: yes

#4559 Fix to allow AOT compilers to play nicely with reflection
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
Labels: c#, cla: yes

#4550 CMake: Update CXX Standard management
  cmake/CMakeLists.txt
Labels: cla: yes

#4572 Using binary one's complement to negate an unsigned int
  src/google/protobuf/wire_format_lite.h
Labels: cla: yes

#4556 [objectivec] Fix memory leak of exceptions raised by RaiseException()
  objectivec/GPBCodedInputStream.m
Labels: cla: yes, objective-c

#4581 Add a third-party RPC implementation: raster
  docs/third_party.md
Labels: cla: yes

#4577 Add space between class name and concat message
  php/src/Google/Protobuf/Internal/Message.php
Labels: cla: yes

#4292 [ruby] Fix RepeatedField#delete_if
  ruby/lib/google/protobuf/repeated_field.rb
  ruby/tests/repeated_field_test.rb
Labels: cla: yes, ruby
