Repository protocolbuffers/protobuf, pull requests merged in 2018-07, with the labels that each got.

#4853 Add wsrpc
  docs/third_party.md
Labels: cla: yes

#4847 Remove write-strings warning from COPTs
  BUILD
Labels: bazel, c++, cla: yes

#4854 Missing symbol exports for Windows DLL
  src/google/protobuf/io/gzip_stream.h
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes

#3847 Google::Protobuf::Struct can access a missing key (#3846)
  ruby/lib/google/protobuf/well_known_types.rb
  ruby/tests/well_known_types_test.rb
Labels: cla: yes, ruby

#4299 Feat: add import-style=commonjs_strict option to the compiler
  Makefile.am
  js/README.md
  js/commonjs/strict_test.js
  js/gulpfile.js
  js/test10.proto
  js/test9.proto
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/js/js_generator.h
Labels: cla: yes, javascript

#4321 Ruby JSON encoding omits zero-length repeated fields by default.
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/basic.rb
Labels: cla: yes, ruby

#3981 Handle srcs in generated files by cd'ing in and out
  BUILD
  protobuf.bzl
Labels: bazel, cla: yes

#4829 Add continuous test for ruby 2.3, 2.4 and 2.5
  ruby/compatibility_tests/v3.0.0/tests/basic.rb
  ruby/compatibility_tests/v3.0.0/tests/repeated_field_test.rb
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic.rb
  ruby/tests/repeated_field_test.rb
  tests.sh
Labels: cla: yes, kokoro:run, ruby

#4856 Add global extension registry to the repo.
  docs/options.md
Labels: cla: yes, documentation

#4835 Update message_module.cc
  python/google/protobuf/pyext/message_module.cc
Labels: cla: yes, python

#4872 Fix SFINAE in 'RepeatedPtrFieldBase::Add'
  src/google/protobuf/repeated_field.h
Labels: cla: yes

#4877 Updated Docker setup to use GCC 4.8
  protoc-artifacts/Dockerfile
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/scl-enable-devtoolset.sh
Labels: cla: yes

#4870 Pragma push 3.5.x
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes

#4879 protoc-artifacts: Update centos base from 6.6 to 6.9
  protoc-artifacts/Dockerfile
Labels: cla: yes

#4878 Fix initialization with Visual Studio
  src/google/protobuf/descriptor.cc
  src/google/protobuf/extension_set.cc
  src/google/protobuf/extension_set.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_util.cc
  src/google/protobuf/generated_message_util.h
  src/google/protobuf/message.cc
  src/google/protobuf/message_lite.h
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/stubs/common.h
  src/google/protobuf/unknown_field_set.cc
Labels: c++, cla: yes

#4882 Merge 3.6.x into master
  src/google/protobuf/descriptor.cc
  src/google/protobuf/extension_set.cc
  src/google/protobuf/extension_set.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_util.cc
  src/google/protobuf/generated_message_util.h
  src/google/protobuf/message.cc
  src/google/protobuf/message_lite.h
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/stubs/common.h
  src/google/protobuf/unknown_field_set.cc
Labels: cla: yes, cleanup

#4876 Fix cpp benchmark dependency on mac
  benchmarks/Makefile.am
  conformance/Makefile.am
Labels: c++, cla: yes

#4191 PHP: disable unicode escape for json
  php/src/Google/Protobuf/Internal/GPBJsonWire.php
  php/src/Google/Protobuf/Internal/Message.php
Labels: cla: yes, php

#4889 protobuf_generate(): add relative path to output dir
  cmake/protobuf-config.cmake.in
Labels: cla: yes, cmake

#4888 OnShutdownDelete shadowing issue
  src/google/protobuf/stubs/common.h
Labels: c++, cla: yes

#4897 objectivec: Quash -Wself-assign and -Wvla
  BUILD
  objectivec/Tests/GPBTestUtilities.m
Labels: cla: yes, objective-c

#4900 Add kokoro bazel configs to 3.6.x branch.
  examples/WORKSPACE
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel/continuous.cfg
  kokoro/linux/bazel/presubmit.cfg
Labels: bazel, cla: yes, cleanup

#4899 Make ruby release configs consistent with protoc.
  kokoro/release/linux/build_artifacts.sh
  kokoro/release/ruby/linux/build_artifacts.sh
  kokoro/release/ruby/linux/prepare_build.sh
  kokoro/release/ruby/linux/release.cfg
  kokoro/release/ruby/linux/ruby/ruby_build.sh
  kokoro/release/ruby/linux/ruby/ruby_build_environment.sh
  kokoro/release/ruby/macos/build_artifacts.sh
  kokoro/release/ruby/macos/release.cfg
  kokoro/release/ruby/macos/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
Labels: cla: yes, packaging & distribution, ruby

#4862 Add Python 3.7 compatibility
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/descriptor_containers.cc
  python/google/protobuf/pyext/descriptor_pool.cc
  python/google/protobuf/pyext/extension_dict.cc
  python/google/protobuf/pyext/message.cc
Labels: cla: yes, python

#4885 Check the message to be encoded is the wrong type.
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/encode_decode_test.rb
Labels: cla: yes, ruby

#4898 fix for API change in PHP 7.3
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
Labels: cla: yes, php

#4906 Added a link for another Clojure protobuf project
  docs/third_party.md
Labels: cla: yes

#4903 fix commonjs js provide GOOGLE_CHECK
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes

#4905 fix linux kokoro build in docker
  examples/list_people_test.go
  kokoro/linux/build_and_run_docker.sh
  kokoro/linux/pull_request_in_docker.sh
  python/tox.ini
Labels: cla: yes, cleanup

#4908 Fix php tests
  php/ext/google/protobuf/message.c
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/src/Google/Protobuf/Internal/MapField.php
  php/src/Google/Protobuf/Internal/RepeatedField.php
  php/tests/compatibility_test.sh
  php/tests/test.sh
Labels: cla: yes

#4913 Update protoc build scripts.
  protoc-artifacts/README.md
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/pom.xml
Labels: cla: yes, cleanup, packaging & distribution

#4916 Add cpp tests under release docker image.
  autogen.sh
  kokoro/linux/cpp_distcheck/build.sh
  kokoro/linux/pull_request_in_docker.sh
  src/google/protobuf/map_entry.h
  tests.sh
Labels: cla: yes, cleanup

#4920 Add protoc release script for Linux build.
  kokoro/release/protoc/linux/build.sh
  kokoro/release/protoc/linux/release.cfg
  protoc-artifacts/build-protoc.sh
Labels: c++, cla: yes, packaging & distribution

#4922 Run autogen.sh in release script.
  kokoro/release/protoc/linux/build.sh
Labels: cla: yes

#4923 Comment out unused command from release script.
  kokoro/release/protoc/linux/build.sh
Labels: cla: yes

#4850 add php benchmark
  benchmarks/Makefile.am
  benchmarks/README.md
  benchmarks/php/PhpBenchmark.php
  benchmarks/php/autoload.php
Labels: cla: yes, php

#4924 Cherry-pick master build fixes and kokoro changes to 3.6.x
  .gitignore
  BUILD
  autogen.sh
  benchmarks/Makefile.am
  cmake/libprotoc.cmake
  conformance/Makefile.am
  conformance/conformance_php.php
  examples/list_people_test.go
  kokoro/linux/build_and_run_docker.sh
  kokoro/linux/cpp_distcheck/build.sh
  kokoro/linux/pull_request_in_docker.sh
  kokoro/release/protoc/linux/build.sh
  kokoro/release/protoc/linux/release.cfg
  php/ext/google/protobuf/message.c
  php/src/Google/Protobuf/Internal/MapField.php
  php/src/Google/Protobuf/Internal/RepeatedField.php
  php/tests/compatibility_test.sh
  php/tests/test.sh
  protoc-artifacts/Dockerfile
  protoc-artifacts/README.md
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/pom.xml
  protoc-artifacts/scl-enable-devtoolset.sh
  python/tox.ini
  ruby/compatibility_tests/v3.0.0/tests/basic.rb
  ruby/compatibility_tests/v3.0.0/tests/repeated_field_test.rb
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic.rb
  ruby/tests/repeated_field_test.rb
  src/Makefile.am
  src/google/protobuf/compiler/js/embed.cc
  src/google/protobuf/compiler/js/well_known_types_embed.cc
  tests.sh
Labels: cla: yes, cleanup

#4912 Fix C# nuget build on Kokoro
  csharp/global.json
  kokoro/linux/prepare_build_linux_rc
  kokoro/release/csharp/windows/build_nuget.bat
Labels: c#, cla: yes

#4934 Sync internal benchmark changes
  benchmarks/util/result_parser.py
  benchmarks/util/result_uploader.py
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#4936 Do Not Define GOOGLE_FALLTHROUGH_INTENDED on GCC Without Attribute Support
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes, kokoro:run

#4942 Delete unused files.
  BUILD
  cmake/libprotoc.cmake
  src/Makefile.am
  src/google/protobuf/compiler/java/java_lazy_message_field.cc
  src/google/protobuf/compiler/java/java_lazy_message_field.h
  src/google/protobuf/compiler/java/java_lazy_message_field_lite.cc
  src/google/protobuf/compiler/java/java_lazy_message_field_lite.h
  src/google/protobuf/compiler/js/well_known_types/any.js
  src/google/protobuf/compiler/js/well_known_types/struct.js
  src/google/protobuf/compiler/js/well_known_types/timestamp.js
Labels: cla: yes, cleanup

#4943 When running unit tests, read reference files in text mode
  src/google/protobuf/compiler/cpp/cpp_bootstrap_unittest.cc
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/ruby/ruby_generator_unittest.cc
  src/google/protobuf/map_test.cc
  src/google/protobuf/testing/file.cc
  src/google/protobuf/testing/file.h
  src/google/protobuf/text_format_unittest.cc
Labels: c++, cla: yes

#4947 Make assertEquals pass for message
  php/ext/google/protobuf/message.c
  php/tests/generated_class_test.php
Labels: cla: yes, kokoro:run, php

#3972 php: Added nanosecond support for Timestamp
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/src/Google/Protobuf/Timestamp.php
  php/tests/compatibility_test.sh
  php/tests/memory_leak_test.php
  php/tests/well_known_test.php
Labels: cla: yes, php, wait for user action

#4952 Update options.md
  docs/options.md
Labels: cla: yes

#4953 Remove/replace travis references
  .travis.yml
  conformance/README.md
  js/README.md
  objectivec/README.md
  python/README.md
  src/README.md
Labels: cla: yes, cleanup

#4949 Check the message to be encoded is the wrong type. (#4885)
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/encode_decode_test.rb
Labels: cla: yes, cleanup

#3829 Update Composer config in PHP module
  php/composer.json
Labels: cla: yes, php, wait for user action

#4930 pyext needs c++11 in linux and mac.
  python/setup.py
Labels: cla: yes, python

#4956 Added support for Visual Studio 2017 in gitignore
  .gitignore
Labels: c++, cla: yes

#4927 Store the class object itself
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/test/java/com/google/protobuf/GeneratedMessageTest.java
Labels: cla: yes, java

#4966 Add conformance test for php c back
  conformance/failure_list_php_c.txt
  tests.sh
Labels: cla: yes, php

#4973 Updated release documentation
  protoc-artifacts/README.md
Labels: cla: yes

#4977 Update third party RPC implementations list
  docs/third_party.md
Labels: cla: yes

#4974 fix third_party/benchmark submodule init
  benchmarks/Makefile.am
Labels: benchmarks, cla: yes

#4825 Ignore unknown enum received in json when ignoreUnknownFields flag is set
  java/util/src/main/java/com/google/protobuf/util/JsonFormat.java
  java/util/src/test/java/com/google/protobuf/util/JsonFormatTest.java
Labels: cla: yes, java

#4979 tests: fix link failure and stack overflow on Mingw w64
  cmake/tests.cmake
Labels: c++, cla: yes, cmake
