Repository protocolbuffers/protobuf, pull requests merged in 2018-12, with the labels that each got.

#5412 [objc] Provide more details/context in deprecation messages ⚠️
  objectivec/GPBBootstrap.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c

#5423 Cherry-pick fix for compatibility with Python 3.7
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/descriptor_containers.cc
  python/google/protobuf/pyext/descriptor_pool.cc
  python/google/protobuf/pyext/extension_dict.cc
  python/google/protobuf/pyext/message.cc
Labels: cla: yes

#5424 Cherry-picked fix from #5406
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/windows/build_artifacts.bat
  python/setup.py
Labels: cla: yes

#5427 [ObjC] Properly annotate extensions for ARC.
  objectivec/Tests/unittest_objc.proto
  src/google/protobuf/compiler/objectivec/objectivec_extension.cc
Labels: cla: yes

#5430 Cherry-picked some internal fixes from Google
  python/google/protobuf/pyext/map_container.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/map_field.h
  src/google/protobuf/map_test.cc
  src/google/protobuf/message.h
  src/google/protobuf/reflection_ops.cc
  src/google/protobuf/text_format.cc
  src/google/protobuf/wire_format.cc
Labels: cla: yes

#5433 Remove mention of Buffer in utils.js
  js/binary/utils.js
Labels: cla: yes

#5442 fix: cmake install
  cmake/extract_includes.bat.in
Labels: cla: yes

#5396 Windows: install missing headers
  cmake/extract_includes.bat.in
Labels: cla: yes

#5446 Ran ./update_file_lists.sh to update CMake configuration
  cmake/extract_includes.bat.in
  cmake/libprotoc.cmake
Labels: cla: yes

#5447 Add docker file for php testing.
  kokoro/linux/dockerfile/push_testing_images.sh
  kokoro/linux/dockerfile/test/php/Dockerfile
Labels: cla: yes

#5389 Add Bazel config for zlib support
  BUILD
  WORKSPACE
  third_party/zlib.BUILD
Labels: cla: yes

#5451 Add composer config to Dockerfile
  kokoro/linux/dockerfile/test/php/Dockerfile
Labels: cla: yes

#5445 Make Protobuf compatible with C# 6
  csharp/src/Google.Protobuf/FieldMaskTree.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/SingleFieldAccessor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/TimestampPartial.cs
Labels: cla: yes

#5454 Create a script to help update the version automatically
  src/Makefile.am
  update_version.sh
Labels: cla: yes

#5452 Updated Bazel workspace in examples/ to handle zlib dependency
  Makefile.am
  examples/WORKSPACE
  examples/third_party/zlib.BUILD
Labels: cla: yes

#5453 Minimize amount of filepaths being copied into protos.
  objectivec/google/protobuf/Any.pbobjc.m
  objectivec/google/protobuf/Api.pbobjc.m
  objectivec/google/protobuf/Duration.pbobjc.m
  objectivec/google/protobuf/Empty.pbobjc.m
  objectivec/google/protobuf/FieldMask.pbobjc.m
  objectivec/google/protobuf/SourceContext.pbobjc.m
  objectivec/google/protobuf/Struct.pbobjc.m
  objectivec/google/protobuf/Timestamp.pbobjc.m
  objectivec/google/protobuf/Type.pbobjc.m
  objectivec/google/protobuf/Wrappers.pbobjc.m
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
Labels: cla: yes, objective-c

#5466 Compile php source to enable openssl and add php7.3 support
  kokoro/linux/dockerfile/push_testing_images.sh
  kokoro/linux/dockerfile/test/php/Dockerfile
Labels: cla: yes

#5468 Use docker for csharp, java_compatibility, and python_compatibility.
  java/compatibility_tests/v2.5.0/test.sh
  kokoro/linux/csharp/build.sh
  kokoro/linux/java_compatibility/build.sh
  kokoro/linux/prepare_build_linux_rc
  kokoro/linux/python_compatibility/build.sh
Labels: cla: yes

#5471 Replace update_version shell script with a python script
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  protoc-artifacts/pom.xml
  update_version.py
  update_version.sh
Labels: cla: yes

#5481 Fix benchmark to use docker image on kokoro
  benchmarks/php/PhpBenchmark.php
  benchmarks/python/py_benchmark.py
  benchmarks/util/result_uploader.py
  kokoro/linux/benchmark/build.sh
  kokoro/linux/benchmark/run.sh
  tests.sh
Labels: cla: yes

#5470 Exclude command_line_interface_unittest.cc in MSVC build
  BUILD
Labels: cla: yes

#5475 Rebuild python docker image
  kokoro/linux/dockerfile/test/python_jessie/Dockerfile
  kokoro/linux/dockerfile/test/python_stretch/Dockerfile
  kokoro/linux/python27/build.sh
  kokoro/linux/python27/continuous.cfg
  kokoro/linux/python27/presubmit.cfg
  kokoro/linux/python27_cpp/build.sh
  kokoro/linux/python27_cpp/continuous.cfg
  kokoro/linux/python27_cpp/presubmit.cfg
  kokoro/linux/python33/build.sh
  kokoro/linux/python33/continuous.cfg
  kokoro/linux/python33/presubmit.cfg
  kokoro/linux/python33_cpp/build.sh
  kokoro/linux/python33_cpp/continuous.cfg
  kokoro/linux/python33_cpp/presubmit.cfg
  kokoro/linux/python34/build.sh
  kokoro/linux/python34/continuous.cfg
  kokoro/linux/python34/presubmit.cfg
  kokoro/linux/python34_cpp/build.sh
  kokoro/linux/python34_cpp/continuous.cfg
  kokoro/linux/python34_cpp/presubmit.cfg
  kokoro/linux/python35/build.sh
  kokoro/linux/python35/continuous.cfg
  kokoro/linux/python35/presubmit.cfg
  kokoro/linux/python35_cpp/build.sh
  kokoro/linux/python35_cpp/continuous.cfg
  kokoro/linux/python35_cpp/presubmit.cfg
  kokoro/linux/python36/build.sh
  kokoro/linux/python36/continuous.cfg
  kokoro/linux/python36/presubmit.cfg
  kokoro/linux/python36_cpp/build.sh
  kokoro/linux/python36_cpp/continuous.cfg
  kokoro/linux/python36_cpp/presubmit.cfg
  kokoro/linux/python37/build.sh
  kokoro/linux/python37/continuous.cfg
  kokoro/linux/python37/presubmit.cfg
  kokoro/linux/python37_cpp/build.sh
  kokoro/linux/python37_cpp/continuous.cfg
  kokoro/linux/python37_cpp/presubmit.cfg
  python/setup.py
  tests.sh
Labels: cla: yes

#5479 Cherry-pick zlib Bazel support
  BUILD
  Makefile.am
  WORKSPACE
  examples/WORKSPACE
  examples/third_party/zlib.BUILD
  third_party/zlib.BUILD
Labels: bazel, cla: yes

#5491 Fix Bazel issues on javalite branch (#5490)
  WORKSPACE
  protobuf.bzl
Labels: cla: yes

#5495 Update kokoro badges for python tests
  README.md
Labels: cla: yes

#5503 benchmark-dashboard fixing
  benchmarks/Makefile.am
  benchmarks/php/PhpBenchmark.php
  benchmarks/python/py_benchmark.py
  kokoro/linux/benchmark/build.sh
  tests.sh
Labels: cla: yes

#5489 Use NoLocalStrtod for international compliance
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  src/Makefile.am
  src/google/protobuf/stubs/strutil.cc
Labels: cla: yes

#5373 Enable the ignore_unknown_field option in the Ruby unmarshal options
  conformance/failure_list_ruby.txt
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
  ruby/lib/google/protobuf.rb
  ruby/tests/basic.rb
Labels: cla: yes, ruby

#5496 Fix Any json encoding/decoding in php
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/tests/encode_decode_test.php
  php/tests/gdb_test.sh
  php/tests/memory_leak_test.php
  php/tests/proto/test.proto
Labels: cla: yes, php
