Repository protocolbuffers/protobuf, pull requests merged in 2018-10, with the labels that each got.

#5206 Fixed typo in documentation
  src/google/protobuf/io/coded_stream.h
Labels: cla: yes

#5210 Added VSCode extension link
  docs/third_party.md
Labels: cla: yes

#5212 Use ::_close rather than ::close in Win32 stubs.
  src/google/protobuf/stubs/io_win32.cc
Labels: cla: yes

#5218 Fixed unsigned warning
  src/google/protobuf/arena_impl.h
Labels: cla: yes

#5221 Fix broken tests by #4816
  Makefile.am
  src/Makefile.am
Labels: cla: yes

#5195 fix(python): fix deprecated collections.abc usage
  python/google/protobuf/internal/containers.py
Labels: cla: yes

#5208 Add `Serializable` attribute to generated C# classes as compiler option
  src/google/protobuf/compiler/csharp/csharp_generator.cc
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message.h
  src/google/protobuf/compiler/csharp/csharp_options.h
Labels: cla: yes

#5207 Add method for Any.Is
  csharp/src/Google.Protobuf.Test/WellKnownTypes/AnyTest.cs
  csharp/src/Google.Protobuf/WellKnownTypes/AnyPartial.cs
Labels: cla: yes

#5166 ParseFromString returns bytes parsed
  python/google/protobuf/internal/message_test.py
  python/google/protobuf/message.py
Labels: cla: yes, python

#5211 Fix parsing empty Struct Values from Json
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/json_format.py
Labels: cla: yes

#5126 PHP: Add support for primitive types in setters
  .gitignore
  Makefile.am
  php/composer.json
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/type_check.c
  php/phpunit.xml
  php/src/Google/Protobuf/Internal/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/test.sh
  php/tests/wrapper_type_setters_test.php
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
  tests.sh
Labels: cla: yes, kokoro:run, php

#5045 Ported FieldMaskUtil from Java to C#
  Makefile.am
  csharp/src/Google.Protobuf.Test/FieldMaskTreeTest.cs
  csharp/src/Google.Protobuf.Test/WellKnownTypes/FieldMaskTest.cs
  csharp/src/Google.Protobuf/FieldMaskTree.cs
  csharp/src/Google.Protobuf/JsonFormatter.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMaskPartial.cs
Labels: c#, cla: yes

#5235 Fix broken ruby test
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
  ruby/tests/common_tests.rb
  ruby/tests/gc_test.rb
Labels: cla: yes, ruby

#5214 remove obsolete parent
  java/pom.xml
Labels: cla: yes, kokoro:run

#5244 Update third_party.md regarding Erlang
  docs/third_party.md
Labels: cla: yes

#5203 Fix string subscript out of range when parse command line argument
  src/google/protobuf/stubs/io_win32.cc
Labels: cla: yes, kokoro:run

#5227 Link to libatomic when necessary (eg. on armv6l)
  configure.ac
  src/Makefile.am
  tests.sh
Labels: cla: yes

#5250 Add ruby2.3,2.4.2.5 test on Mac and disable ruby2.1,2.2 test on Linux
  kokoro/macos/ruby23/build.sh
  kokoro/macos/ruby23/continuous.cfg
  kokoro/macos/ruby23/presubmit.cfg
  kokoro/macos/ruby24/build.sh
  kokoro/macos/ruby24/continuous.cfg
  kokoro/macos/ruby24/presubmit.cfg
  kokoro/macos/ruby25/build.sh
  kokoro/macos/ruby25/continuous.cfg
  kokoro/macos/ruby25/presubmit.cfg
  tests.sh
Labels: cla: yes

#5240 Sync upb for unknown fix
  php/ext/google/protobuf/upb.c
  php/tests/encode_decode_test.php
Labels: cla: yes

#5247 Remove unnecessary cast to Builder in generated Java code
  src/google/protobuf/compiler/java/java_message_builder.cc
Labels: cla: yes

#5198 Revert "protobuf_generate(): add relative path to output dir"
  cmake/protobuf-config.cmake.in
Labels: cla: yes

#5260 Removed unnecessary includes from stubs/common.h
  src/google/protobuf/compiler/python/python_generator.h
  src/google/protobuf/stubs/bytestream.cc
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/common_unittest.cc
  src/google/protobuf/stubs/int128.cc
  src/google/protobuf/stubs/statusor.cc
  src/google/protobuf/stubs/stringpiece.cc
  src/google/protobuf/stubs/stringprintf.cc
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/substitute.cc
  src/google/protobuf/testing/file.cc
  src/google/protobuf/testing/googletest.h
  src/google/protobuf/util/internal/datapiece.h
  src/google/protobuf/util/internal/field_mask_utility.h
Labels: cla: yes

#5256 Add ruby 2.3, 2.4 and 2.5 test for linux.
  kokoro/linux/ruby23/build.sh
  kokoro/linux/ruby23/continuous.cfg
  kokoro/linux/ruby23/presubmit.cfg
  kokoro/linux/ruby24/build.sh
  kokoro/linux/ruby24/continuous.cfg
  kokoro/linux/ruby24/presubmit.cfg
  kokoro/linux/ruby25/build.sh
  kokoro/linux/ruby25/continuous.cfg
  kokoro/linux/ruby25/presubmit.cfg
  ruby/ext/google/protobuf_c/defs.c
  ruby/tests/gc_test.rb
  tests.sh
Labels: cla: yes

#5186 Add node and php to benchmark dashboard
  benchmarks/Makefile.am
  benchmarks/js/js_benchmark.js
  benchmarks/php/PhpBenchmark.php
  benchmarks/python/py_benchmark.py
  benchmarks/util/result_parser.py
  benchmarks/util/result_uploader.py
  kokoro/linux/benchmark/build.sh
Labels: cla: yes

#5280 Fix Javadoc typo
  java/core/src/main/java/com/google/protobuf/Parser.java
Labels: cla: yes

#5277 Remove ruby21 and ruby22 tests
  README.md
  kokoro/linux/ruby_all/build.sh
  kokoro/linux/ruby_all/continuous.cfg
  kokoro/linux/ruby_all/presubmit.cfg
  kokoro/macos/ruby21/build.sh
  kokoro/macos/ruby21/continuous.cfg
  kokoro/macos/ruby21/presubmit.cfg
  kokoro/macos/ruby22/build.sh
  kokoro/macos/ruby22/continuous.cfg
  kokoro/macos/ruby22/presubmit.cfg
  tests.sh
Labels: cla: yes, ruby

#5283 Remove Debug Statement for Win/MinGW
  ruby/ext/google/protobuf_c/extconf.rb
Labels: cla: yes, ruby

#5270 Fix error: unused parameter 'arena' [-Werror=unused-parameter]
  src/google/protobuf/inlined_string_field.h
Labels: cla: yes

#5297 Remove unused types
  src/google/protobuf/extension_set.cc
  src/google/protobuf/stubs/common.cc
Labels: cla: yes
