Repository protocolbuffers/protobuf, pull requests merged in 2019-09, with the labels that each got.

#6499 Document proto2 feature implementations in Google.Protobuf
  docs/csharp/proto2.md
Labels: c#, cla: yes, release notes: yes

#6317 C#: add System.Memory dependency for net45 too
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf/ByteString.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, cla: yes, release notes: no

#6560 Add binary conformance tests for map fields
  .gitignore
  conformance/binary_json_conformance_suite.cc
  conformance/binary_json_conformance_suite.h
  conformance/failure_list_js.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_python.txt
  conformance/failure_list_ruby.txt
Labels: cla: yes, conformance tests, release notes: no

#6554 Add Protojure to third-party wiki
  docs/third_party.md
Labels: cla: yes, documentation, release notes: no

#6535 Enable PROTOBUF_EXPORT/PROTOBUF_USE_DLL on clang/gcc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/repeated_field.cc
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, release notes: no

#6601 Fix up simple typo: invididual -> individual
  python/google/protobuf/internal/_parameterized.py
Labels: cla: yes, release notes: no

#6610 Fix small style issues in the dart example, following Effective Dart
  examples/add_person.dart
  examples/list_people.dart
Labels: cla: yes, kokoro:run, release notes: no

#6614 Sync upb
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
Labels: cla: yes, php, release notes: no, ruby

#6618 Cherry Pick (#6614)
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
Labels: cla: yes, php, release notes: no

#6621 Update protobuf version for Java and PHP
  java/core/pom.xml
  java/lite/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
Labels: cla: yes, java, php, release notes: no

#6628 Linakge Monitor fix to handle a new version of protobuf-bom not available in Maven Central
  tests.sh
Labels: cla: yes, cleanup, release notes: no

#6622 Implement binary conformance test for oneof fields
  conformance/binary_json_conformance_suite.cc
  conformance/binary_json_conformance_suite.h
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
Labels: cla: yes, conformance tests, release notes: no

#6629 Remove duplicate entry in third party list
  docs/third_party.md
Labels: cla: yes, cleanup, release notes: no

#6638 Added pbtools to third party implementations list.
  docs/third_party.md
Labels: cla: yes, release notes: no

#6637 [csharp] Fix typo
  csharp/src/Google.Protobuf/ByteString.cs
Labels: cla: yes, release notes: no

#6651 Add license
  php/ext/google/protobuf/type_check.c
Labels: cla: yes, packaging & distribution, release notes: no

#6656 Simplify template exporting macros
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/repeated_field.cc
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, release notes: no

#6660 Update to 3.10.0-rc0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#6647 Update protobuf version to 3.10.0 stable
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, integration, release notes: no

#6669 Fix incorrect Proto2 C# doc comments
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
Labels: cla: yes, release notes: no

#6672 [ObjC] Don't use unions and instead use memcpy for the type swaps.
  objectivec/GPBUtilities_PackagePrivate.h
Labels: cla: yes, customer issue, ios, objective-c, release notes: no

#6678 [ObjC] Remove OSReadLittle* due to alignment requirements
  objectivec/GPBCodedInputStream.m
Labels: cla: yes, ios, objective-c, release notes: yes

#6680 Pull the ObjC fixes from #6679 to the 3.9.x branch
  objectivec/GPBCodedInputStream.m
  objectivec/GPBUtilities_PackagePrivate.h
Labels: cla: yes, objective-c, release notes: yes

#6681 Pull the ObjC fixes from #6679 to the 3.10.x branch
  objectivec/GPBCodedInputStream.m
  objectivec/GPBUtilities_PackagePrivate.h
Labels: cla: yes, objective-c, release notes: yes

#6682 Update version to 3.9.2
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#6671 Remove unused-parameter warnings
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/stubs/bytestream.h
Labels: cla: yes, release notes: no

#6695 Fixed leap year handling by reworking upb_mktime() -> upb_timegm().
  ruby/ext/google/protobuf_c/upb.c
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#6696 Php timestamp fix
  conformance/binary_json_conformance_suite.cc
  php/ext/google/protobuf/upb.c
Labels: cla: yes, php, release notes: no

#6701 Update to 3.9.2
  java/README.md
Labels: cla: yes, java, release notes: no

#6694 Add document for php development
  php/README.md
Labels: cla: yes, php, release notes: no

#6709 Add option for dart
  docs/options.md
Labels: cla: yes, release notes: no

#6705 Fix #6098
  cmake/CMakeLists.txt
Labels: cla: yes, release notes: no

#6692 Remove unused function and add more UTs
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/stubs/strutil_unittest.cc
Labels: cla: yes, release notes: no

#6708 Update README.md
  php/README.md
Labels: cla: yes, php, release notes: no

#6612 Updated deprecation macros to annotate deprecated code
  BUILD
  src/google/protobuf/dynamic_message.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/port.h
  src/google/protobuf/text_format.h
Labels: c++, cla: yes, release notes: yes

#6713 Initialize well known type values
  php/ext/google/protobuf/message.c
  php/tests/encode_decode_test.php
  php/tests/memory_leak_test.php
  php/tests/proto/test.proto
Labels: cla: yes, php, release notes: no

#6714 Initialize well known type values (#6713)
  php/ext/google/protobuf/message.c
  php/tests/encode_decode_test.php
  php/tests/memory_leak_test.php
  php/tests/proto/test.proto
Labels: cla: yes, php, release notes: no
