Repository protocolbuffers/protobuf, pull requests merged in 2019-01, with the labels that each got.

#5516 Clean up unnecessary compile warning with GCC
  BUILD
Labels: cla: yes

#5519 Ruby build fix mac 3.7.x
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
Labels: cla: yes

#5527 Down-integrate internal changes to github.
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/map_field.cc
  src/google/protobuf/map_field.h
  src/google/protobuf/map_field_inl.h
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/map_test_util.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/type_resolver_util.cc
  src/google/protobuf/util/type_resolver_util_test.cc
Labels: cla: yes

#5553 [ObjC] Add the jspb cases to the switches so they are complete.
  conformance/conformance_objc.m
Labels: cla: yes

#5537 Add ruby 2.6 gem build for linux
  kokoro/linux/dockerfile/push_testing_images.sh
  kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/ruby/linux/prepare_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
Labels: cla: yes

#5532 Fix Empty ListValue/Struct json encoding
  php/ext/google/protobuf/encode_decode.c
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
Labels: cla: yes, kokoro:run

#5568 Comments on the next line will go to the next field.
  conformance/conformance.proto
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
Labels: cla: yes

#5566 Down-integrate internal changes to github.
  conformance/ConformanceJava.java
  conformance/conformance.proto
  conformance/conformance_cpp.cc
  conformance/conformance_python.py
  conformance/conformance_test.cc
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  js/test.proto
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes

#5580 [ObjC] add support for the TextFormat constants.
  conformance/conformance_objc.m
Labels: cla: yes

#5564 Ruby nested msg caps
  ruby/tests/generated_code.proto
  ruby/tests/generated_code_test.rb
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes

#5591 Fix field mask for php in json
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/tests/encode_decode_test.php
  php/tests/generated_class_test.php
  php/tests/php_implementation_test.php
  php/tests/test_base.php
  php/tests/test_util.php
Labels: cla: yes, php

#5597 doc: apply consistent indentation to Any examples
  src/google/protobuf/any.proto
Labels: cla: yes

#5603 Revert "doc: apply consistent indentation to Any examples"
  src/google/protobuf/any.proto
Labels: cla: yes

#5589 Fixed compile warnings for PHP extension.
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/type_check.c
Labels: cla: yes

#5590 Add proto3 to solidity link in third_party.md
  docs/third_party.md
Labels: cla: yes

#5599 Fix c extension doesn' allow message reference in array
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/storage.c
  php/tests/array_test.php
  php/tests/proto/test.proto
Labels: cla: yes, php

#5605 Fix empty FieldMask json encoding/decoding
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_python.txt
  conformance/failure_list_python_cpp.txt
  php/ext/google/protobuf/upb.c
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/tests/encode_decode_test.php
Labels: cla: yes

#5612 Create test for protoc with tcmalloc
  kokoro/linux/cpp_tcmalloc/build.sh
  kokoro/linux/cpp_tcmalloc/continuous.cfg
  kokoro/linux/cpp_tcmalloc/presubmit.cfg
  kokoro/linux/dockerfile/test/cpp_tcmalloc/Dockerfile
  tests.sh
Labels: cla: yes

#5615 Fix protoc release
  protoc-artifacts/Dockerfile
  protoc-artifacts/build-protoc.sh
Labels: cla: yes

#5613 Fix more issues for reference values
  php/ext/google/protobuf/storage.c
  php/ext/google/protobuf/type_check.c
  php/tests/array_test.php
  php/tests/generated_class_test.php
  php/tests/map_field_test.php
  php/tests/proto/test.proto
Labels: cla: yes

#5626 Update version to 3.7.0
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes

#5627 Update more files in update_version.py
  update_version.py
Labels: cla: yes

#5631 Update CHANGES.txt
  CHANGES.txt
Labels: cla: yes

#5629 Allow internalAddGeneratedFile to depend on new nested message name
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes

#5630 Update guava version to 26
  java/pom.xml
Labels: cla: yes

#5638 Fix MacOS protoc release
  kokoro/release/protoc/macos/build.sh
Labels: cla: yes

#5646 Default values should also be serialized for json map key/value (#5643)
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/encode_decode.c
  php/tests/encode_decode_test.php
Labels: cla: yes, php

#5644 Convert integer to string if field is string field in json
  conformance/failure_list_php.txt
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
  tests.sh
Labels: cla: yes, php

#5595 Fix GetErrno() to be const noexcept
  src/google/protobuf/io/zero_copy_stream_impl.h
Labels: cla: yes

#5654 Updated version to 3.7.0rc2
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes

#5652 Fixes warnings in https://github.com/google/oss-fuzz/issues/864#issue…
  src/google/protobuf/arenastring.h
  src/google/protobuf/util/field_comparator.h
Labels: cla: yes

#5648 Swapped libprotoc and libprotobuf
  cmake/protoc.cmake
Labels: cla: yes

#5624 Remove whitespace following trailing backslash
  src/Makefile.am
Labels: cla: yes
