Repository protocolbuffers/protobuf, pull requests merged in 2019-06, with the labels that each got.

#6201 Merge 3.8.x into master branch
  CHANGES.txt
  Makefile.am
  Protobuf.podspec
  configure.ac
  conformance/failure_list_ruby_mac.txt
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/upb.c
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/wrapper_type_setters_test.php
  protobuf.pc.in
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/upb.c
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#6208 compelete fix issue 5060: change CodedOutputStream to CodedOutputStream*
  src/google/protobuf/io/coded_stream.h
Labels: cla: yes, release notes: no

#6204 Fix RPATH when CMAKE_INSTALL_LIBDIR != lib.
  cmake/install.cmake
Labels: cla: yes, release notes: no

#6221 ObjC: avoid assign for object properties
  objectivec/GPBDescriptor.h
Labels: cla: yes, objective-c, release notes: no

#6222 ObjC: avoid assign for object properties (part 2)
  objectivec/GPBDescriptor.h
Labels: cla: yes, objective-c, release notes: no

#6206 Treat plugins as host tools.
  protobuf.bzl
Labels: cla: yes, release notes: no

#6233 Fix JavaLite version
  java/lite/pom.xml
Labels: cla: yes, java-lite, release notes: no

#6203 JSON string output functions should clear() the destination first
  src/google/protobuf/util/json_util.cc
Labels: cla: yes, release notes: no

#6225 add compatibility check badge to README
  python/README.md
Labels: cla: yes, release notes: no

#6166 [Ruby] Remove to_hash methods
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/src/main/java/com/google/protobuf/jruby/RubyMap.java
  ruby/src/main/java/com/google/protobuf/jruby/RubyMessage.java
Labels: cla: yes, release notes: yes, ruby

#6229 Fix Alphabetization of BUILD
  BUILD
Labels: cla: yes, release notes: no

#6240 Add twirpql ID to global registry
  docs/options.md
Labels: cla: yes, release notes: no

#6248 Cherry-pick fixes for protobuf.bzl into 3.8.x
  protobuf.bzl
Labels: cla: yes, release notes: no

#6250 Remove unused fields
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
Labels: c#, cla: yes, release notes: no

#6262 Fix TypeError on decoding enum map values in Ruby
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/basic.rb
  ruby/tests/basic_test.proto
Labels: cla: yes, release notes: no, ruby

#6266 Update version to 3.9.0
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#6265 Update gem to 2.7.9
  kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile
Labels: cla: yes, release notes: no, ruby

#6263 Change offset of Timestamp conformance test to distinguish from the default
  conformance/binary_json_conformance_suite.cc
Labels: cla: yes, conformance tests, release notes: no

#6251 Change int64 json encoding to be string for php and ruby
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  php/ext/google/protobuf/upb.c
  ruby/ext/google/protobuf_c/upb.c
  ruby/tests/common_tests.rb
Labels: cla: yes, php, release notes: yes, ruby

#6268 Update GSON version to 3.8.5
  java/util/pom.xml
Labels: cla: yes, java, release notes: yes

#6270 Update generated codes
  csharp/src/Google.Protobuf.Test/testprotos.pb
  src/google/protobuf/type.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#6269 Revert "JSON string output funtions should clear() the destination fi…
  src/google/protobuf/util/json_util.cc
Labels: c++, cla: yes, release notes: no

#6155 php: Fix formatting of Duration
  conformance/failure_list_php.txt
  php/src/Google/Protobuf/Internal/EnumDescriptor.php
  php/src/Google/Protobuf/Internal/GPBUtil.php
Labels: cla: yes, php, release notes: no

#6276 Include protobuf_deps.bzl in generated release archives
  Makefile.am
Labels: cla: yes, release notes: no

#6274 Removed all use of STLDelete*() in ObjC and C# Generators.
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
Labels: cla: yes, release notes: no

#6277 Make php message class final to avoid mocking
  csharp/src/Google.Protobuf.Test/testprotos.pb
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6279 Add "src/**/*.inc" to //:protobuf_headers
  BUILD
Labels: c++, cla: yes, release notes: no

#6177 Add `protobuf_java_lite` Bazel target
  BUILD
  java/lite/pom.xml
Labels: cla: yes, java-lite, release notes: yes

#6246 Compatibility tests pull artifacts over HTTPS
  java/compatibility_tests/v2.5.0/test.sh
Labels: cla: yes, cleanup, release notes: no

#6176 Add extension number for protoc-gen-validate
  docs/options.md
Labels: cla: yes, release notes: no

#6282 Revert "Append field number to accessors if there is conflict"
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/wrapper_type_setters_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6292 3.8.x merge
  BUILD
  Makefile.am
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  java/lite/pom.xml
  kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile
  php/ext/google/protobuf/upb.c
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/wrapper_type_setters_test.php
  ruby/ext/google/protobuf_c/upb.c
  ruby/tests/common_tests.rb
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#6295 Rename get/setXXXValue to get/setXXXWrapper
  php/tests/wrapper_type_setters_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6223 Added stubs/map_util.h to list of installed headers
  src/Makefile.am
  src/google/protobuf/stubs/map_util.h
Labels: cla: yes, release notes: no

#6298 Merge master into 3.9.x
  BUILD
  Makefile.am
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  docs/options.md
  java/compatibility_tests/v2.5.0/test.sh
  java/lite/pom.xml
  kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile
  php/ext/google/protobuf/upb.c
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptor.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/wrapper_type_setters_test.php
  ruby/ext/google/protobuf_c/upb.c
  ruby/tests/common_tests.rb
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#6300 Merge 3.9.x into master
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/map_util.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#5878 Fix scope resolution for Google namespace
  src/google/protobuf/compiler/ruby/ruby_generated_code_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_code_proto2_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes, release notes: yes, ruby

#6231 Fix javadoc warnings in generated files
  .gitignore
  src/google/protobuf/compiler/java/java_doc_comment.cc
  src/google/protobuf/compiler/java/java_doc_comment.h
  src/google/protobuf/compiler/java/java_enum.cc
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_enum_field_lite.cc
  src/google/protobuf/compiler/java/java_enum_lite.cc
  src/google/protobuf/compiler/java/java_message.cc
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_message_field_lite.cc
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field_lite.cc
  src/google/protobuf/compiler/java/java_string_field.cc
  src/google/protobuf/compiler/java/java_string_field_lite.cc
Labels: cla: yes, java, kokoro:run, release notes: yes

#6306 Setting up JDK8 for Kokoro jobs
  kokoro/linux/dockerfile/test/java_stretch/Dockerfile
  kokoro/linux/java_linkage_monitor/build.sh
  kokoro/linux/java_linkage_monitor/continuous.cfg
  kokoro/linux/java_linkage_monitor/presubmit.cfg
  tests.sh
Labels: cla: yes, release notes: no

#6319 Add changelog for 3.9.x
  CHANGES.txt
Labels: cla: yes, release notes: no
