Repository protocolbuffers/protobuf, pull requests merged in 2019-12, with the labels that each got.

#6972 Update protobuf version to 3.11.1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#6973 Update CHANGES.txt for 3.11.1 release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6971 Add php 7.4 to docker image
  kokoro/linux/dockerfile/test/php/Dockerfile
  kokoro/linux/dockerfile/test/php_32bit/Dockerfile
Labels: cla: yes, php, release notes: no

#6975 Add php 7.4 to docker image (#6971)
  kokoro/linux/dockerfile/test/php/Dockerfile
  kokoro/linux/dockerfile/test/php_32bit/Dockerfile
Labels: cla: yes, php, release notes: no

#6974 Initialize wrapper message during parsing
  php/ext/google/protobuf/encode_decode.c
  php/tests/encode_decode_test.php
Labels: cla: yes, php, release notes: no

#6976 Add a proto_lang_toolchain for javalite (3.11.x backport)
  BUILD
  examples/WORKSPACE
Labels: cla: yes, java-lite, release notes: yes

#6855 Simplifying Linkage Monitor test setup
  tests.sh
Labels: cla: yes, java, release notes: no

#6938 Fix latest ArgumentException for C# extensions
  Makefile.am
  csharp/generate_protos.sh
  csharp/protos/unittest_issue6936_a.proto
  csharp/protos/unittest_issue6936_b.proto
  csharp/protos/unittest_issue6936_c.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936A.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936B.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936C.cs
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/ExtensionRegistry.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
Labels: c#, cla: yes, release notes: yes

#6674 Cleanup various bits of Google.Protobuf
  csharp/src/Google.Protobuf.Test/GeneratedMessageTest.Proto2.cs
  csharp/src/Google.Protobuf/CodedOutputStream.cs
  csharp/src/Google.Protobuf/JsonFormatter.cs
  csharp/src/Google.Protobuf/JsonParser.cs
  csharp/src/Google.Protobuf/MessageParser.cs
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
Labels: c#, cla: yes, release notes: yes

#6970 Migrate from maven_jar to jvm_maven_import_external to prepare for Bazel 2.0
  WORKSPACE
Labels: bazel, cla: yes, release notes: no

#6950 Update to 3.11.0 in docs
  java/README.md
Labels: cla: yes, release notes: no

#6915 Added 3rd party Java library (QuickBuffers)
  docs/third_party.md
Labels: cla: yes, release notes: no

#6990 Allocated a custom option number for Analyze Re Graphene
  docs/options.md
Labels: cla: yes, release notes: no

#6896 Fix some UBsan warnings
  src/google/protobuf/stubs/strutil.cc
Labels: cla: yes, release notes: no

#6845 add `-std=c++11` to make it compile
  examples/Makefile
Labels: cla: yes, release notes: no

#7002 Update CHANGES.txt for 3.11.2 release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6999 Add --<lang>_opt flag for all built-in generators
  src/google/protobuf/compiler/main.cc
Labels: cla: yes, protoc, release notes: no

#6988 Fix typos in benchmarks/README.md .
  benchmarks/README.md
Labels: cla: yes, release notes: no

#6844 Correct interpretation of utf-8 0xf8-0xff
  src/google/protobuf/stubs/strutil.cc
Labels: c++, cla: yes, release notes: no

#7003 Remove use of VLA.
  objectivec/Tests/GPBUnknownFieldSetTest.m
Labels: cla: yes, objective-c, release notes: no

#7004 Update protobuf version to 3.11.2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#7008 Fix Multiple Request for PHP
  .gitignore
  Makefile.am
  php/ext/google/protobuf/protobuf.c
  php/tests/compile_extension.sh
  php/tests/multirequest.php
  php/tests/multirequest.sh
  php/tests/test.sh
  tests.sh
Labels: cla: yes, php, release notes: no

#7011 Remove duplicate license header from test protos
  src/google/protobuf/test_messages_proto2.proto
  src/google/protobuf/test_messages_proto3.proto
Labels: cla: yes, release notes: no, testing

#7009 add python38
  kokoro/linux/dockerfile/test/python_stretch/Dockerfile
  kokoro/linux/python38/build.sh
  kokoro/linux/python38/continuous.cfg
  kokoro/linux/python38/presubmit.cfg
  kokoro/linux/python38_cpp/build.sh
  kokoro/linux/python38_cpp/continuous.cfg
  kokoro/linux/python38_cpp/presubmit.cfg
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/build_single_artifact.bat
  tests.sh
Labels: cla: yes, python, release notes: yes

#7020 Reserve 1076, 1077 for Wire since and until
  docs/options.md
Labels: cla: yes, release notes: no

#7019 Add python3.8 in build_artifacts for linux and macos
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
Labels: cla: yes, python, release notes: no

#7038 Fix python release breakages by set MB_PYTHON_OSX_VER
  kokoro/release/python/macos/build_artifacts.sh
Labels: cla: yes, python, release notes: no
