Repository protocolbuffers/protobuf, pull requests merged in 2019-07, with the labels that each got.

#6318 Kokoro: run Linkage Monitor on presubmit
  tests.sh
Labels: cla: yes, java, release notes: no

#6322 Format with buildifier
  BUILD
Labels: cla: yes, release notes: no

#6324 Revert "Make php message class final to avoid mocking (#6277)"
  csharp/src/Google.Protobuf.Test/testprotos.pb
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6327 Added linkage monitor badge
  README.md
Labels: cla: yes, release notes: no, testing

#6294 Fix path problems in file extract_includes.bat.in
  cmake/extract_includes.bat.in
Labels: c++, cla: yes, release notes: no

#6333 fix a UBSAN warnings.
  src/google/protobuf/stubs/strutil.cc
Labels: c++, cla: yes, release notes: yes

#6337 link libatomic on systems without adequate builtin atomics
  cmake/CMakeLists.txt
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
Labels: cla: yes, release notes: no

#6301 javalite: don't use deprecated single_file option
  protobuf.bzl
Labels: bazel, cla: yes, kokoro:force-run, kokoro:run, release notes: no

#6323 Use proto_library in proto_lang_toolchain.blacklisted_protos
  BUILD
Labels: bazel, cla: yes, release notes: no

#6343 allow copy and paste from readme
  src/README.md
Labels: cla: yes, documentation, release notes: no

#6346 fix dart example readme typo
  examples/README.md
Labels: cla: yes, documentation, release notes: no

#6351 Set oneof case in array constructor
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/tests/generated_class_test.php
Labels: cla: yes, php, release notes: no

#6350 Fix builtin_atomics check in CMakeLists.txt
  cmake/CMakeLists.txt
Labels: cla: yes, release notes: no

#6352 Fix unused-parameter clang warnings in arena.h and map_type_handler.h
  src/google/protobuf/arena.h
  src/google/protobuf/map_type_handler.h
Labels: cla: yes, release notes: no

#6360 ruby: Improve performance of Google::Protobuf::Timestamp#to_time
  ruby/lib/google/protobuf/well_known_types.rb
Labels: cla: yes, release notes: no, ruby

#6348 Update version in README
  java/README.md
Labels: cla: yes, java, release notes: no

#6330 Update gson
  java/util/pom.xml
Labels: cla: yes, java, release notes: no

#6331 Update guava
  java/pom.xml
Labels: cla: yes, java, release notes: no

#6366 Update protobuf version
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#6363 Requesting extension id 1072
  docs/options.md
Labels: cla: yes, release notes: no

#6310 Fix usage of six in //:protobuf_python rule and add import
  BUILD
  WORKSPACE
  protobuf_deps.bzl
Labels: bazel, cla: yes, python, release notes: no

#6046 Change "python" to "python_headers" in comment
  util/python/BUILD
Labels: cla: yes, python, release notes: no

#6383 Fix make test on FreeBSD
  src/google/protobuf/testing/zcgunzip.cc
  src/google/protobuf/testing/zcgzip.cc
Labels: cla: yes, release notes: no

#6365 Remove zlib copts flags when on Windows
  third_party/zlib.BUILD
Labels: cla: yes, release notes: no

#6397 Updated cmake path to io_win32.h
  cmake/extract_includes.bat.in
Labels: cla: yes, release notes: no, windows

#6403 [bazel] Use strip_import_prefix for wkp instead of copying them
  BUILD
Labels: cla: yes, release notes: no

#6406 Drop building wheel for python 3.4
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
Labels: cla: yes, python, release notes: no

#6405 Revert bad change to objc conformance test in #6199
  conformance/conformance_objc.m
Labels: cla: yes, conformance tests, release notes: no

#6413 Updated Bazel test script to use most recent Bazel version
  kokoro/linux/bazel/build.sh
Labels: cla: yes, release notes: no

#6377 Fix assignment between Python protobuf Structs
  python/google/protobuf/internal/well_known_types.py
  python/google/protobuf/internal/well_known_types_test.py
Labels: cla: yes, python, release notes: no

#6380 Fix binary compatibility in FieldCodec factory methods
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: c#, cla: yes, release notes: no

#6424 Backport to 3.9.x: Fix binary compatibility in FieldCodec factory methods (#6380)
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: c#, cla: yes, release notes: yes

#6422 fix typo in io/printer.h
  src/google/protobuf/io/printer.h
Labels: cla: yes, release notes: no

#6415 Add conformance test for binary string
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_php_c.txt
Labels: cla: yes, conformance tests, release notes: no

#6426 Drop building wheel for python 3.4 (#6406)
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
Labels: cla: yes, release notes: no, testing

#6370 Fix null terminated string in Ruby wrapper type helper names
  ruby/ext/google/protobuf_c/message.c
Labels: cla: yes, release notes: no, ruby

#6428 Add binary conformance test case for bytes field
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_php_c.txt
Labels: cla: yes, release notes: no, testing

#6371 Disable javadoc error
  java/pom.xml
Labels: cla: yes, java, release notes: no

#6404 Add podspec for C++
  Protobuf-C++.podspec
  update_version.py
Labels: c++, cla: yes, release notes: yes

#6433 Updated Bazel test script to use most recent Bazel version (#6413)
  kokoro/linux/bazel/build.sh
Labels: bazel, cla: yes, release notes: no

#6434 Add binary conformance test for enum fields.
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_js.txt
Labels: cla: yes, conformance tests, release notes: no

#6432 [bazel] Add fixes for --incompatible_load_{cc,java,proto}_rules_from_bzl
  BUILD
  protobuf_deps.bzl
Labels: bazel, cla: yes, release notes: no

#6435 Add binary conformance test for message type.
  conformance/binary_json_conformance_suite.cc
  conformance/binary_json_conformance_suite.h
  conformance/failure_list_js.txt
  conformance/failure_list_php.txt
Labels: cla: yes, conformance tests, release notes: no

#6394 Fixed JS parsing of default map values
  js/map.js
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes, javascript, release notes: no

#6438 Backport Bazel-incompatible fixes to 3.9.x (orginal: #6432)
  BUILD
  protobuf_deps.bzl
Labels: bazel, cla: yes, release notes: no

#6431 Backport review comments for C# proto2 features (for 3.9.x)
  csharp/src/Google.Protobuf/Extension.cs
  csharp/src/Google.Protobuf/ExtensionRegistry.cs
  csharp/src/Google.Protobuf/ExtensionSet.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
Labels: c#, cla: yes, release notes: no

#5716 Support hashes for struct initializers
  ruby/ext/google/protobuf_c/map.c
  ruby/tests/basic.rb
  ruby/tests/well_known_types_test.rb
Labels: cla: yes, release notes: yes, ruby

#6407 Add csharp compatibility tests between last released and the current version
  csharp/compatibility_tests/v3.0.0/test.sh
  tests.sh
  update_compatibility_version.py
Labels: cla: yes, release notes: no

#6440 Add binary conformance test for default repeated fields
  conformance/binary_json_conformance_suite.cc
  conformance/binary_json_conformance_suite.h
  conformance/conformance_test.cc
  conformance/conformance_test.h
  conformance/failure_list_js.txt
  conformance/failure_list_objc.txt
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
Labels: cla: yes, conformance tests, release notes: no

#6369 Fix proto3 extensions support
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes, release notes: no, ruby

#5044 Windows: expand path names on command line
  BUILD
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/io/io_win32.cc
  src/google/protobuf/io/io_win32.h
  src/google/protobuf/io/io_win32_unittest.cc
Labels: bazel, c++, cla: yes, release notes: no

#6445 [bazel] Add fixes for --incompatible_load_{cc,java,proto}_rules_from_bzl (Part 2)
  BUILD
  Makefile.am
  WORKSPACE
  examples/BUILD
  examples/WORKSPACE
  examples/third_party/zlib.BUILD
  protobuf.bzl
  protobuf_deps.bzl
  third_party/zlib.BUILD
  util/python/BUILD
Labels: cla: yes, release notes: no

#6344 add test case for Generate() in the cpp_bootstrap_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_bootstrap_unittest.cc
Labels: c++, cla: yes, release notes: no

#6455 Fix a Python extension crash in descriptor's nested types container
  python/google/protobuf/internal/descriptor_test.py
  python/google/protobuf/pyext/descriptor_containers.cc
Labels: cla: yes, python, release notes: no
