Repository protocolbuffers/protobuf, pull requests merged in 2019-04, with the labels that each got.

#5901 Fix some UBSAN warnings.
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/text_format.cc
Labels: c++, cla: yes

#5890 Update file list for protobuf_lite
  BUILD
  cmake/extract_includes.bat.in
  cmake/libprotobuf-lite.cmake
Labels: cla: yes

#5985 For 3.7.x: Add missing declaration in protobuf_headers
  BUILD
Labels: cla: yes

#5773 Removes unused code in core and related lint warnings
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
Labels: c++, cla: yes

#5982 support specify C++ STL for android
  BUILD
Labels: cla: yes

#6007 Add Mergeable config
  .github/mergeable.yml
Labels: cla: yes, release notes: no

#6004 Add lite.md to JavaLite branch
  java/lite.md
Labels: cla: yes, release notes: no

#6003 Update documentation for JavaLite
  java/lite.md
Labels: cla: yes, release notes: no

#6016 Down integration to GitHub
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  php/src/Google/Protobuf/Internal/FileOptions.php
  python/google/protobuf/internal/text_format_test.py
  python/google/protobuf/text_format.py
  src/google/protobuf/any.pb.cc
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_enum.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_service.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.proto
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/message.cc
  src/google/protobuf/message.h
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes, integration, release notes: no

#6014 Make cold_threshold_ look used to fix warning
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: c++, cla: yes, release notes: no

#6011 Remove unused constants
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/java/java_helpers.cc
Labels: cla: yes, cleanup, release notes: no

#5991 Emit annotations for oneof field accessors in c++
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: cla: yes

#6000 Small patch to handle -Wfloat-equal warnings
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: c++, cla: yes, release notes: yes

#6032 Replace SimpleItoa with StrCat in ObjectiveC compiler codes
  src/google/protobuf/compiler/objectivec/objectivec_enum.cc
  src/google/protobuf/compiler/objectivec/objectivec_extension.cc
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_oneof.cc
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc
Labels: cla: yes, objective-c, release notes: no

#6033 Down integrate to GitHub
  src/google/protobuf/any.pb.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.cc
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_file.h
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/compiler/scc.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/io/strtod.cc
  src/google/protobuf/message.cc
  src/google/protobuf/message.h
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.cc
  src/google/protobuf/type.pb.h
  src/google/protobuf/unittest_no_arena.proto
  src/google/protobuf/wrappers.pb.cc
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#6034 comply with Bazel recommendations
  BUILD
  protobuf_deps.bzl
Labels: cla: yes, release notes: no

#6037 Satisfy GCC class-memaccess warnings
  src/google/protobuf/descriptor.cc
Labels: cla: yes, release notes: no

#6022 Add -Werror for CI builds
  kokoro/linux/bazel/build.sh
Labels: bazel, cla: yes, release notes: no

#6013 Remove -Wall from default build options
  BUILD
Labels: cla: yes, cleanup, release notes: no

#6051 Down Integration to GitHub
  java/core/src/main/java/com/google/protobuf/Internal.java
  python/google/protobuf/pyext/message.cc
  src/google/protobuf/compiler/cpp/cpp_bootstrap_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_field.cc
  src/google/protobuf/compiler/cpp/cpp_field.h
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message.h
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/cpp/cpp_service.cc
  src/google/protobuf/compiler/cpp/cpp_service.h
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_enum_field.h
  src/google/protobuf/compiler/java/java_enum_field_lite.cc
  src/google/protobuf/compiler/java/java_enum_field_lite.h
  src/google/protobuf/compiler/java/java_enum_lite.cc
  src/google/protobuf/compiler/java/java_enum_lite.h
  src/google/protobuf/compiler/java/java_extension.cc
  src/google/protobuf/compiler/java/java_extension.h
  src/google/protobuf/compiler/java/java_extension_lite.cc
  src/google/protobuf/compiler/java/java_extension_lite.h
  src/google/protobuf/compiler/java/java_field.h
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/java/java_helpers.h
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_message_field.h
  src/google/protobuf/compiler/java/java_message_field_lite.cc
  src/google/protobuf/compiler/java/java_message_field_lite.h
  src/google/protobuf/compiler/java/java_message_lite.cc
  src/google/protobuf/compiler/java/java_message_lite.h
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field.h
  src/google/protobuf/compiler/java/java_primitive_field_lite.cc
  src/google/protobuf/compiler/java/java_primitive_field_lite.h
  src/google/protobuf/compiler/java/java_string_field.cc
  src/google/protobuf/compiler/java/java_string_field.h
  src/google/protobuf/compiler/java/java_string_field_lite.cc
  src/google/protobuf/compiler/java/java_string_field_lite.h
  src/google/protobuf/compiler/js/js_generator.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/io/coded_stream_unittest.cc
  src/google/protobuf/io/zero_copy_stream_impl_lite.cc
  src/google/protobuf/io/zero_copy_stream_impl_lite.h
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/message.h
  src/google/protobuf/util/internal/constants.h
  src/google/protobuf/util/internal/datapiece.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/message_differencer.h
  src/google/protobuf/util/type_resolver_util_test.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes, integration, release notes: no

#6064 Down integrate to GitHub
  java/core/src/test/proto/com/google/protobuf/any_test.proto
  java/core/src/test/proto/com/google/protobuf/cached_field_size_test.proto
  java/core/src/test/proto/com/google/protobuf/message_lite_extension_util_test.proto
  java/core/src/test/proto/com/google/protobuf/multiple_files_test.proto
  java/core/src/test/proto/com/google/protobuf/proto2_message.proto
  java/core/src/test/proto/com/google/protobuf/proto2_message_lite.proto
  java/core/src/test/proto/com/google/protobuf/proto3_message.proto
  java/core/src/test/proto/com/google/protobuf/proto3_message_lite.proto
  java/core/src/test/proto/com/google/protobuf/test_bad_identifiers.proto
  java/core/src/test/proto/com/google/protobuf/test_custom_options.proto
  java/core/src/test/proto/com/google/protobuf/test_extra_interfaces.proto
  java/core/src/test/proto/com/google/protobuf/wrappers_test.proto
  java/util/src/test/proto/com/google/protobuf/util/json_test.proto
  python/google/protobuf/descriptor.py
  python/google/protobuf/internal/generator_test.py
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/descriptor.h
  python/google/protobuf/pyext/descriptor_pool.h
  python/google/protobuf/pyext/map_container.cc
  python/google/protobuf/pyext/scoped_pyobject_ptr.h
  src/google/protobuf/any.pb.cc
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/compiler/importer_unittest.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/descriptor_database_unittest.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/stubs/mutex.h
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectwriter.h
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
  src/google/protobuf/util/json_util.h
  src/google/protobuf/util/json_util_test.cc
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes, integration, release notes: no

#6069 Update the version for JavaLite in update_version script
  update_version.py
Labels: cla: yes, java-lite, release notes: no

#6044 Replaced all instances of Simple{IDF}toa with StrCat.
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_enum.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_primitive_field.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/python/python_generator.cc
Labels: cla: yes, cleanup, release notes: no

#5966 Add a new conformance test for top level JSON null
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
Labels: cla: yes, conformance tests, release notes: no

#6072 Partially Revert "Replaced all instances of Simple{IDF}toa with StrCat."
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/python/python_generator.cc
Labels: cla: yes, release notes: no

#6068 Update version to 3.8.0
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#6077 Remove unused files from lite's pom.xml
  java/lite/pom.xml
Labels: cla: yes, java, java-lite, release notes: no

#6082 Remove unused files from lite's pom.xml
  java/lite/pom.xml
Labels: cla: yes, java, java-lite, release notes: no

#6083 Update change log for 3.8.0
  CHANGES.txt
Labels: cla: yes, release notes: no
