Repository protocolbuffers/protobuf, pull requests merged in 2019-10, with the labels that each got.

#6721 Update CHANGES.txt with changes since 3.10.0-RC1
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6724 Improve the grammar of the unused import message.
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
Labels: cla: yes, release notes: no

#6720 export third_party BUILD files so they are accessible to users
  third_party/BUILD
Labels: cla: yes, release notes: no

#6750 Fix conformance test
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/encode_decode.c
  php/tests/encode_decode_test.php
  php/tests/proto/test.proto
Labels: cla: yes, php, release notes: no

#6728 Merge 3.10.x with master and increment the version number
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  conformance/binary_json_conformance_suite.cc
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/type_check.c
  php/ext/google/protobuf/upb.c
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/upb.c
  ruby/google-protobuf.gemspec
  ruby/tests/common_tests.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#6757 Ported names fix for Ruby to the release branch.
  ruby/lib/google/protobuf.rb
Labels: cla: yes, release notes: no, ruby

#6744 Java: Update to Guava 28.1-android
  java/pom.xml
Labels: cla: yes, java, release notes: no

#6747 Include cmath instead of math.h
  src/google/protobuf/text_format.cc
Labels: cla: yes, release notes: no

#6753 fixed typo
  cmake/README.md
Labels: cla: yes, release notes: no

#6758 Remove unused argument to avoid UB
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/protobuf.h
Labels: cla: yes, release notes: no

#6530 c# feature(RepeatedField): Capacity property to resize the internal array
  csharp/src/Google.Protobuf.Test/Collections/RepeatedFieldTest.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
Labels: c#, cla: yes, release notes: yes

#6775 Updated Cmake example to build Visual Studio to newest 2019 version. [release notes: no] [c++]
  cmake/README.md
Labels: cla: yes, release notes: no

#6766 c++ remove conversion warning in MapEntryFuncs::ByteSizeLong
  src/google/protobuf/map_entry_lite.h
Labels: c++, cla: yes, release notes: yes

#6765 c++ remove unused parameters
  src/google/protobuf/extension_set.h
  src/google/protobuf/message_lite.h
  src/google/protobuf/parse_context.h
Labels: cla: yes, release notes: no

#6759 Add length checks to ExtensionCollection
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
Labels: c#, cla: yes, release notes: yes

#6760 Backport #6759 and disable extension code gen for C#
  csharp/src/AddressBook/Addressbook.cs
  csharp/src/Google.Protobuf.Benchmarks/BenchmarkMessage1Proto3.cs
  csharp/src/Google.Protobuf.Benchmarks/Benchmarks.cs
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  csharp/src/Google.Protobuf.Test/TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestImportProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestImportPublicProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test/TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf/Reflection/CustomOptions.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Any.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Api.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Duration.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Empty.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMask.cs
  csharp/src/Google.Protobuf/WellKnownTypes/SourceContext.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Struct.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Timestamp.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Type.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Wrappers.cs
  src/google/protobuf/compiler/csharp/csharp_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.h
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_helpers.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message.h
  src/google/protobuf/compiler/csharp/csharp_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_reflection_class.cc
  src/google/protobuf/compiler/csharp/csharp_reflection_class.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
Labels: c#, cla: yes, release notes: yes

#6783 Installing BOM before running Java test
  tests.sh
Labels: cla: yes, java, release notes: no

#6785 Update protobuf version to 3.10.1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#6767 c++ remove warning switch contains default but no case
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
Labels: cla: yes, release notes: no

#6791 Ported names fix for Ruby to the release branch
  ruby/lib/google/protobuf.rb
Labels: cla: yes, release notes: yes, ruby

#6790 Update CHANGES.txt for 3.10.1 release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6795 Load @rules_python in six.BUILD
  third_party/six.BUILD
Labels: cla: yes, release notes: no

#6802 protoc-java: Fix broken javadoc generation
  src/google/protobuf/compiler/java/java_enum_field.cc
Labels: cla: yes, release notes: no

#6810 Update to 3.10.0 in docs
  java/README.md
Labels: cla: yes, java, release notes: no

#6690 Fix: Undefined behavior in UTF8GenericScanFastAscii
  src/google/protobuf/stubs/structurally_valid.cc
Labels: cla: yes, release notes: no

#6811 Update GSON and errorprone
  java/util/pom.xml
Labels: cla: yes, java, release notes: no

#6716 Avoid too much overhead in layout_init
  .gitignore
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
Labels: cla: yes, kokoro:run, php, release notes: yes

#6820 Added a descriptor option number for ocaml-protoc-plugin
  docs/options.md
Labels: cla: yes, release notes: no

#6780 Make shared libraries be able to link to MSVC static runtime libraries.
  cmake/CMakeLists.txt
Labels: c++, cla: yes, release notes: yes
