Repository protocolbuffers/protobuf, pull requests merged in 2019-03, with the labels that each got.

#5014 Updating Iterators to be compatible with C++17 in MSVC
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, cleanup

#5670 Generate extra enum method helpers for Ruby
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
Labels: cla: yes, ruby

#5726 Add frozen checks in Ruby
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/basic.rb
  ruby/tests/common_tests.rb
Labels: cla: yes, ruby

#5794 Fix Ruby module name generation when the ruby_package option is used (again)
  ruby/tests/test_ruby_package.proto
  ruby/tests/test_ruby_package_proto2.proto
  src/Makefile.am
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit.proto
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit.proto
  src/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit_pb.rb
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator_unittest.cc
Labels: cla: yes, ruby

#5788 Fix documentation on message differencer.
  src/google/protobuf/util/message_differencer.h
Labels: cla: yes

#5808 Change cerr to cout in PrintHelpText again
  src/google/protobuf/compiler/command_line_interface.cc
Labels: cla: yes, protoc

#5803 Emit annotations for generated C++ extension identifiers
  src/google/protobuf/compiler/cpp/cpp_extension.cc
Labels: c++, cla: yes

#5840 Run Ruby tests
  ruby/travis-test.sh
Labels: cla: yes, kokoro:run

#5740 Simplify holding copies of strings in default_value_objectwriter
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/internal/default_value_objectwriter.h
Labels: cla: yes

#5539 Updated upb from defcleanup branch and modified Ruby to use it
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/storage.c
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
  ruby/lib/google/protobuf.rb
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
  ruby/tests/common_tests.rb
  ruby/tests/type_errors.rb
Labels: cla: yes

#5604 PHP updates for new upb APIs
  Makefile.am
  php/ext/google/protobuf/builtin_descriptors.inc
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  tests.sh
Labels: cla: yes, php

#5848 Revert "Updated upb from defcleanup branch and modified Ruby to use it"
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/storage.c
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
  ruby/lib/google/protobuf.rb
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
  ruby/tests/common_tests.rb
  ruby/tests/type_errors.rb
Labels: cla: yes

#5823 Fix unit tests for older rubies
  ruby/tests/basic.rb
  ruby/tests/common_tests.rb
  ruby/tests/type_errors.rb
Labels: cla: yes, ruby

#5849 CriticalSectionLock class as a lightweight replacement for std::mutex on Windows platforms.
  src/google/protobuf/stubs/mutex.h
Labels: cla: yes

#5826 Cleanups to allow for import by Copybara.
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_doc_comment.cc
  src/google/protobuf/compiler/csharp/csharp_enum.cc
  src/google/protobuf/compiler/csharp/csharp_enum.h
  src/google/protobuf/compiler/csharp/csharp_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.h
  src/google/protobuf/compiler/csharp/csharp_generator.cc
  src/google/protobuf/compiler/csharp/csharp_generator.h
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_map_field.cc
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message.h
  src/google/protobuf/compiler/csharp/csharp_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_names.h
  src/google/protobuf/compiler/csharp/csharp_options.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_reflection_class.cc
  src/google/protobuf/compiler/csharp/csharp_reflection_class.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc
  src/google/protobuf/compiler/csharp/csharp_source_generator_base.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/php/php_generator.h
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator.h
Labels: cla: yes

#5854 Create test to verify that the dist artifact can be installed.
  kokoro/linux/dist_install/build.sh
  kokoro/linux/dist_install/continuous.cfg
  kokoro/linux/dist_install/presubmit.cfg
  tests.sh
Labels: cla: yes, release notes: no

#5855 Add link to continuous test badges
  README.md
Labels: cla: yes, testing

#5853 Fix ruby continuous tests
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  ruby/compatibility_tests/v3.0.0/tests/basic.rb
Labels: cla: yes, ruby

#5811 Bazel: Add dependency to error_prone_annotations
  BUILD
  WORKSPACE
Labels: cla: yes, kokoro:run

#5861 Raise error for JSON overflow encoding in Ruby (#5752)
  ruby/Rakefile
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
Labels: cla: yes, ruby

#5862 Bazel: Add dependency to error_prone_annotations
  BUILD
  WORKSPACE
Labels: cla: yes

#5810 Use fixed size for bool, float and double field in codec
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/FieldCodecTest.cs
  csharp/src/Google.Protobuf.Test/FieldCodecTest.cs
  csharp/src/Google.Protobuf/CodedOutputStream.ComputeSize.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: cla: yes

#5857 Encode empty ListValue
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/travis-test.sh
Labels: cla: yes

#5838 Bump target frameworks of C# programs from netcoreapp1.0 to netcoreapp2.1
  Makefile.am
  conformance/Makefile.am
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/compatibility_tests/v3.0.0/test.sh
  csharp/global.json
  csharp/install_dotnet_sdk.ps1
  csharp/src/AddressBook/AddressBook.csproj
  csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj
  csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  global.json
  kokoro/linux/csharp/build.sh
  kokoro/linux/dockerfile/test/csharp/Dockerfile
  kokoro/release/csharp/windows/build_nuget.bat
Labels: cla: yes

#5872 Stop enabling more warnings for CXX compiles.
  objectivec/DevTools/full_mac_build.sh
Labels: cla: yes

#5864 No define strtoll/strtoull for VS2013 and above
  src/google/protobuf/stubs/strutil.h
Labels: cla: yes

#5873 Avoid passing -Og flag to C++ compiler
  src/Makefile.am
  tests.sh
Labels: cla: yes

#5867 Parse nested listvalue in json for ruby
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_php.txt
  csharp/src/Google.Protobuf.Test/TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  php/ext/google/protobuf/upb.c
  php/tests/proto/test.proto
  ruby/ext/google/protobuf_c/upb.c
  src/google/protobuf/test_messages_proto3.proto
Labels: cla: yes, ruby

#5871 Add terminating character to zend_lookup_class call
  Makefile.am
  php/ext/google/protobuf/def.c
  php/tests/compile_extension.sh
  php/tests/php_implementation_test.php
  php/tests/test.sh
  tests.sh
Labels: cla: yes, php

#5880 Remove GPBWrapperUtil from generated code
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php

#5885 Add terminating character to zend_lookup_class call
  Makefile.am
  php/ext/google/protobuf/def.c
  php/tests/compile_extension.sh
  php/tests/php_implementation_test.php
  php/tests/test.sh
  tests.sh
Labels: cla: yes, php

#5894 Add missing C# windows presubmit.cfg file
  kokoro/windows/csharp/presubmit.cfg
Labels: P1, c#, cla: yes

#5891 Fix source stepping by upgrading sourcelink
  csharp/build_packages.bat
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, cla: yes

#5896 Ruby error messages in 3.7.x
  Makefile.am
  ruby/compatibility_tests/v3.0.0/tests/basic.rb
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
  ruby/tests/type_errors.rb
Labels: cla: yes, ruby

#5898 Make the C# benchmarks non-packable
  csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj
Labels: cla: yes

#5881 Fix macros in header of generated code
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes

#5912 Update CONTRIBUTING.md to recommend applying the appropriate labels
  CONTRIBUTING.md
Labels: cla: yes

#5908 Revert "Updating Iterators to be compatible with C++17 in MSVC"
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes

#5835 C#: add System.Memory dependency
  csharp/src/Google.Protobuf/ByteString.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, cla: yes

#5906 Replace strptime with custom implementation
  conformance/failure_list_ruby.txt
  conformance/failure_list_ruby_mac.txt
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
Labels: cla: yes, ruby

#5709 Allow Java reserved keywords to be used in extensions
  java/core/src/test/java/com/google/protobuf/ExtensionRegistryFactoryTest.java
  java/core/src/test/proto/com/google/protobuf/nested_extension.proto
  java/core/src/test/proto/com/google/protobuf/nested_extension_lite.proto
  java/core/src/test/proto/com/google/protobuf/non_nested_extension.proto
  java/core/src/test/proto/com/google/protobuf/non_nested_extension_lite.proto
  src/google/protobuf/compiler/java/java_extension.cc
  src/google/protobuf/compiler/java/java_extension_lite.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/java/java_helpers.h
Labels: cla: yes, java

#5767 Added io_win32.h to header list in CMake config
  cmake/extract_includes.bat.in
Labels: cla: yes

#5927 Fix Windows builds with future Bazel changes
  src/google/protobuf/testing/googletest.cc
Labels: cla: yes

#5897 [Python] Fix several DeprecationWarning: invalid escape sequence
  benchmarks/util/result_parser.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/text_format_test.py
Labels: cla: yes

#5932 Revert "Remove unused f expression from jscode gen. (#5573)"
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes

#5933 Remove unused import from message.
  js/message.js
Labels: cla: yes

#5934 Remove unused import in message.js.
  js/message.js
Labels: cla: yes

#5928 Avoid marking generated C++ messages as final for now
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes

#5944 No define strtoll/strtoull for VS2013 and above
  src/google/protobuf/stubs/strutil.h
Labels: cla: yes

#5935 Updated NPM version to 3.7.1
  js/package.json
Labels: cla: yes

#5924 Allow bytes field to be longer than 16000 bytes
  php/ext/google/protobuf/upb.c
  php/tests/encode_decode_test.php
  ruby/ext/google/protobuf_c/upb.c
Labels: cla: yes, ruby

#5922 Avoid linking against libatomic when building protoc
  configure.ac
  protoc-artifacts/build-protoc.sh
Labels: cla: yes

#5929 Fix "the the".
  CHANGES.txt
  objectivec/GPBMessage.h
  php/ext/google/protobuf/upb.c
  ruby/ext/google/protobuf_c/upb.c
Labels: cla: yes

#5948 Fixed CI failures with Ruby 2.3 on OSX
  kokoro/macos/prepare_build_macos_rc
  ruby/travis-test.sh
Labels: cla: yes

#5947 Update version number to 3.7.1
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes

#5952 Update third_party.md
  docs/third_party.md
Labels: cla: yes

#5751 Add native type setters for Timestamp and Duration in Ruby
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
Labels: cla: yes, ruby

#5739 Add wrapper type helpers for Ruby
  ruby/.gitignore
  ruby/Rakefile
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
Labels: cla: yes, ruby

#5955 Upgrade the closure compiler version
  js/gulpfile.js
  js/package.json
  kokoro/linux/dockerfile/push_testing_images.sh
  kokoro/linux/dockerfile/test/javascript/Dockerfile
  kokoro/linux/javascript/build.sh
Labels: cla: yes
