Repository protocolbuffers/protobuf, pull requests merged in 2019-11, with the labels that each got.

#6826 Avoid NullReferenceException when accessing CustomOptions
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf/Reflection/EnumDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
Labels: bug, c#, cla: yes, release notes: no

#6824 Fix reflection access when using old generated code
  Makefile.am
  csharp/generate_protos.sh
  csharp/protos/old_extensions1.proto
  csharp/protos/old_extensions2.proto
  csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs
  csharp/src/Google.Protobuf.Test/TestProtos/OldExtensions1.cs
  csharp/src/Google.Protobuf.Test/TestProtos/OldExtensions2.cs
  csharp/src/Google.Protobuf/ExtensionRegistry.cs
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
Labels: c#, cla: yes, release notes: no

#6840 General Xcode 11 support for picking iOS simulators to test against.
  objectivec/DevTools/full_mac_build.sh
Labels: cla: yes, objective-c, release notes: no

#6842 Fix Makefile.am by adding generated files
  Makefile.am
Labels: c#, cla: yes, release notes: no

#6836 C#: Add microbenchmark for parsing wrapper types
  Makefile.am
  csharp/generate_protos.sh
  csharp/src/Google.Protobuf.Benchmarks/Program.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmark.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmarkMessages.cs
  csharp/src/Google.Protobuf.Benchmarks/wrapper_benchmark_messages.proto
Labels: c#, cla: yes, release notes: no

#6828 Use 3 parameter Encoding.GetString for default string values
  csharp/src/Google.Protobuf.Test/TestProtos/Unittest.cs
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
Labels: c#, cla: yes, release notes: yes

#6843 C#: Optimize parsing of some primitive and wrapper types
  csharp/src/Google.Protobuf.Test/WellKnownTypes/WrappersTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: c#, cla: yes, release notes: yes

#6847 Backport wrapper optimizations and microbenchmarks (to 3.10.x)
  Makefile.am
  csharp/generate_protos.sh
  csharp/src/Google.Protobuf.Benchmarks/Program.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmark.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmarkMessages.cs
  csharp/src/Google.Protobuf.Benchmarks/wrapper_benchmark_messages.proto
  csharp/src/Google.Protobuf.Test/WellKnownTypes/WrappersTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: c#, cla: yes, release notes: yes

#6797 Ruby lazy wrappers optimization
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic.rb
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#6856 Change _Extensions property to normal body rather than expression
  csharp/src/Google.Protobuf.Test/TestProtos/TestMessagesProto2.cs
  csharp/src/Google.Protobuf.Test/TestProtos/Unittest.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  src/google/protobuf/compiler/csharp/csharp_message.cc
Labels: c#, cla: yes, release notes: yes

#6866 Fix decoding of overencoded booleans.
  objectivec/GPBCodedInputStream.m
Labels: cla: yes, objective-c, release notes: no

#6832 Move generated test code for Google.Protobuf.Test to a separate lib
  Makefile.am
  csharp/generate_protos.sh
  csharp/src/Google.Protobuf.Test.TestProtos/ForeignMessagePartial.cs
  csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj
  csharp/src/Google.Protobuf.Test.TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/OldExtensions1.cs
  csharp/src/Google.Protobuf.Test.TestProtos/OldExtensions2.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto2.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/Unittest.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImport.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublic.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublicProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.sln
Labels: c#, cla: yes, release notes: no

#6272 Import MutableSequence from collections.abc on Python 3.
  python/google/protobuf/pyext/message.cc
Labels: cla: yes, python, release notes: no

#6877 C# upgrade dotnet SDK
  csharp/install_dotnet_sdk.ps1
  global.json
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: c#, cla: yes, release notes: no

#6888 Revert "C# upgrade dotnet SDK"
  csharp/install_dotnet_sdk.ps1
  global.json
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: c#, cla: yes, release notes: no

#6833 Lazily Create Singular Wrapper Message
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
  php/tests/memory_leak_test.php
  php/tests/proto/test.proto
  php/tests/wrapper_type_setters_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6890 Update Xcode version needed to run Kokoro tests and replace deprecated rubygem options
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
Labels: cla: yes, release notes: no, testing

#6893 Down integrate to GitHub
  js/map.js
  python/google/protobuf/descriptor.py
  python/google/protobuf/pyext/message.cc
  python/google/protobuf/service_reflection.py
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/java/java_helpers.h
  src/google/protobuf/compiler/java/java_name_resolver.cc
  src/google/protobuf/compiler/java/java_name_resolver.h
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/compiler/python/python_generator.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/parse_context.cc
  src/google/protobuf/parse_context.h
Labels: cla: yes, integration, release notes: no

#6898 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, integration, release notes: no

#6899 Persistent Descriptor Pool
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/tests/test.sh
Labels: cla: yes, php, release notes: yes

#6909 Update CHANGES.txt with 3.11.0-RC1 release notes
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6914 Revert "Make shared libraries be able to link to MSVC static runtime libraries, so that VC runtime is not required."
  CHANGES.txt
  cmake/CMakeLists.txt
Labels: c++, cla: yes, release notes: no

#6916 Marked update_compatibility_version.py as executable
  update_compatibility_version.py
Labels: cla: yes, integration, release notes: no

#6917 Merge 3.11.0-rc1 changes to master
  CHANGES.txt
  cmake/CMakeLists.txt
  update_compatibility_version.py
Labels: cla: yes, integration, release notes: no

#6911 Implement lazy loading of php class for proto messages
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
Labels: cla: yes, php, release notes: yes

#6927 Update protobuf version to 3.11.0-RC2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, integration, release notes: no

#6929 Remove add_proto_enumdesc and get_proto_enumdesc
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, php, release notes: no

#6925 Implement lazy loading of php class for proto messages (#6911)
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
Labels: cla: yes, php, release notes: yes

#6931 Remove add_proto_enumdesc and get_proto_enumdesc
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, php, release notes: no

#6920 Revert "Revert "C# upgrade dotnet SDK""
  csharp/install_dotnet_sdk.ps1
  global.json
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: c#, cla: yes, release notes: no

#6943 Update protobuf version to 3.11.0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, integration, release notes: no

#6944 Update CHANGES.txt for 3.11.0 stable release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#6910 Fix conformance test failures for Google.Protobuf
  conformance/failure_list_csharp.txt
  csharp/src/Google.Protobuf.Conformance/Program.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
Labels: c#, cla: yes, release notes: yes

#6946 Extern declare protobuf_globals
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, php, release notes: no

#6882 Add a proto_lang_toolchain for javalite
  BUILD
  examples/WORKSPACE
Labels: cla: yes, java-lite, release notes: yes
