Repository protocolbuffers/protobuf, pull requests merged in 2019-05, with the labels that each got.

#6085 Change update_version to update the generated codes too
  update_version.py
Labels: cla: yes, release notes: no

#6088 Down integrate to GitHub
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/test/java/com/google/protobuf/DescriptorsTest.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  java/util/src/main/java/com/google/protobuf/util/JsonFormat.java
  java/util/src/test/java/com/google/protobuf/util/JsonFormatTest.java
  js/gulpfile.js
  js/map.js
  js/message.js
  js/package.json
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/java/java_message_lite.cc
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/map_field.cc
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/map_test.cc
  src/google/protobuf/map_test_util.cc
  src/google/protobuf/map_test_util.h
  src/google/protobuf/message.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/test_util.h
  src/google/protobuf/test_util.inc
  src/google/protobuf/text_format.cc
  src/google/protobuf/util/internal/json_objectwriter.h
  src/google/protobuf/util/internal/object_writer.h
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/message_differencer.h
  src/google/protobuf/util/message_differencer_unittest.proto
  src/google/protobuf/wire_format_lite.cc
Labels: cla: yes, integration, release notes: no

#6039 Make use of RDTSC optional as it may not be available
  src/google/protobuf/map.h
Labels: cla: yes, release notes: no

#6054 Fixed errors with type declarations on some versions of clang
  src/google/protobuf/parse_context.h
Labels: c++, cla: yes, release notes: no

#6096 should close protocolbuffers#6095
  src/google/protobuf/parse_context.h
Labels: cla: yes, release notes: no

#6106 Update php/release.sh to be executable and create a new branch
  php/release.sh
Labels: cla: yes, release notes: no

#6111 Update version for podspec to not include dot
  Protobuf.podspec
  update_version.py
Labels: cla: yes, release notes: no

#6121 Fix update_version script to use the appropriate rc style for C#
  update_version.py
Labels: cla: yes, release notes: no

#6118 Custom mktime to fix issue on mac
  conformance/failure_list_ruby_mac.txt
  php/ext/google/protobuf/upb.c
  ruby/ext/google/protobuf_c/upb.c
Labels: cla: yes, php, release notes: no, ruby

#6105 Fix typo
  java/core/src/main/java/com/google/protobuf/RopeByteString.java
Labels: cla: yes, release notes: no

#6090 Revert "protobuf.pc.in does not reflect CXXFLAGS"
  protobuf.pc.in
Labels: cla: yes, release notes: no

#6107 Updated gemspec to require Ruby 2.3 or higher
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#6124 Fix compilation error with SDL check flag in Visual Studio
  src/google/protobuf/generated_message_table_driven_lite.h
Labels: cla: yes, release notes: no

#6126 Added conformance tests to Bazel BUILD file
  BUILD
Labels: cla: yes, release notes: no

#6127 Down integrate to GitHub
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  js/binary/decoder_test.js
  python/google/protobuf/descriptor_pool.py
  python/google/protobuf/internal/well_known_types.py
  src/google/protobuf/any.pb.cc
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/java/java_message_lite.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.proto
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/dynamic_message.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/map_entry.h
  src/google/protobuf/map_field.h
  src/google/protobuf/message.cc
  src/google/protobuf/message.h
  src/google/protobuf/message_unittest.inc
  src/google/protobuf/repeated_field.h
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/text_format.cc
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/util/internal/json_stream_parser.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes, integration, release notes: no

#6132 Make sure to include zlib.BUILD in our distribution
  Makefile.am
Labels: cla: yes, release notes: no

#6133 Make sure to return the updated line when modifying .pb.h file
  update_version.py
Labels: c++, cla: yes, release notes: no

#6128 Convert Google::Protobuf.deep_copy to pure Ruby
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/lib/google/protobuf.rb
Labels: cla: yes, release notes: no, ruby

#6140 Revert "Convert Google::Protobuf.deep_copy to pure Ruby"
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/lib/google/protobuf.rb
Labels: cla: yes, release notes: no, ruby

#6139 Typo fix for conformance test runner.
  BUILD
Labels: cla: yes, release notes: no

#6138 Fix typo 'pythong'
  docs/performance.md
Labels: benchmarks, cla: yes, cleanup, release notes: no

#6115 Update instruction on how to use JavaLite runtime
  java/lite.md
Labels: cla: yes, kokoro:run, release notes: no

#6116 Add new file to package.xml
  php/ext/google/protobuf/package.xml
Labels: cla: yes, release notes: no

#6153 Update performance.md
  docs/performance.md
Labels: benchmarks, cla: yes, documentation, release notes: no

#6151 Down Integrate to GitHub
  benchmarks/python/py_benchmark.py
  java/core/src/test/proto/com/google/protobuf/multiple_files_test.proto
  java/core/src/test/proto/com/google/protobuf/test_bad_identifiers.proto
  protobuf.pc.in
  python/google/protobuf/descriptor_pool.py
  python/google/protobuf/internal/descriptor_database_test.py
  python/google/protobuf/internal/descriptor_pool_test.py
  python/google/protobuf/internal/python_message.py
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/util/time_util.h
Labels: cla: yes, integration, release notes: no

#6158 Update performance.md
  docs/performance.md
Labels: benchmarks, cla: yes, cleanup, documentation, release notes: no

#6164 Cherrypick 014872a962a85fe11cd5a1798a8a390b64493c48 to fix build
  protobuf.pc.in
Labels: cla: yes, release notes: no

#6161 Down integrate to GitHub
  benchmarks/util/result_parser.py
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  java/core/src/main/java/com/google/protobuf/AbstractMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/descriptor.proto
  src/google/protobuf/message_lite.h
Labels: cla: yes, integration, release notes: no

#6169 Append field number to accessors if there is conflict
  php/tests/proto/test_wrapper_type_setters.proto
  php/tests/wrapper_type_setters_test.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#6117 Add use_nested to internalAddGeneratedFile to make php and c extension consistent
  php/src/Google/Protobuf/Internal/DescriptorPool.php
Labels: cla: yes, php, release notes: no

#6173 Fix gulpfile to use gulp 4 API
  js/gulpfile.js
  js/package.json
Labels: cla: yes, release notes: no

#6160 Update protobuf version to 3.8.0
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#6162 Move tool out of inputs in bazel config
  protobuf.bzl
Labels: cla: yes, release notes: no

#6183 avoid error when compiling with MSVC2010
  src/google/protobuf/map_field.cc
Labels: cla: yes, release notes: no

#6189 Use runtime_error vs just exiting for some issues.
  conformance/conformance_objc.m
Labels: cla: yes, conformance tests, objective-c, release notes: no

#6199 Down integrate to GitHub
  Makefile.am
  conformance/conformance_objc.m
  java/pom.xml
  java/util/pom.xml
  java/util/src/main/java/com/google/protobuf/util/Structs.java
  java/util/src/main/java/com/google/protobuf/util/Values.java
  java/util/src/test/java/com/google/protobuf/util/StructsTest.java
  java/util/src/test/java/com/google/protobuf/util/ValuesTest.java
  python/google/protobuf/descriptor_pool.py
  python/google/protobuf/internal/message_test.py
  python/google/protobuf/pyext/map_container.cc
  src/google/protobuf/any.pb.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.cc
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_field.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/cpp/cpp_string_field.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor.proto
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/map_test.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/text_format.cc
  src/google/protobuf/text_format.h
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.cc
  src/google/protobuf/type.pb.h
  src/google/protobuf/util/internal/json_objectwriter_test.cc
  src/google/protobuf/wrappers.pb.cc
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#6193 fix typo in examples/README.md
  examples/README.md
Labels: cla: yes, release notes: no

#6202 Update CONTRIBUTING.md to clarify who should set the labels
  CONTRIBUTING.md
Labels: cla: yes, release notes: no

#6196 remove comment about wire_format_lite_inl.h
  src/google/protobuf/wire_format_lite.h
Labels: cla: yes, release notes: no
