Repository protocolbuffers/protobuf, pull requests merged in 2020-02, with the labels that each got.

#7162 Update CHANGES.txt for 3.11.3 release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#7189 Add js files added in #7176 to Makefiles
  Makefile.am
Labels: cla: yes, javascript, release notes: no

#7173 Revisit how the WKTs are bundled with ObjC.
  Makefile.am
  Protobuf.podspec
  objectivec/GPBAny.pbobjc.h
  objectivec/GPBAny.pbobjc.m
  objectivec/GPBApi.pbobjc.h
  objectivec/GPBApi.pbobjc.m
  objectivec/GPBDuration.pbobjc.h
  objectivec/GPBDuration.pbobjc.m
  objectivec/GPBEmpty.pbobjc.h
  objectivec/GPBEmpty.pbobjc.m
  objectivec/GPBFieldMask.pbobjc.h
  objectivec/GPBFieldMask.pbobjc.m
  objectivec/GPBProtocolBuffers.h
  objectivec/GPBProtocolBuffers.m
  objectivec/GPBSourceContext.pbobjc.h
  objectivec/GPBSourceContext.pbobjc.m
  objectivec/GPBStruct.pbobjc.h
  objectivec/GPBStruct.pbobjc.m
  objectivec/GPBTimestamp.pbobjc.h
  objectivec/GPBTimestamp.pbobjc.m
  objectivec/GPBType.pbobjc.h
  objectivec/GPBType.pbobjc.m
  objectivec/GPBWellKnownTypes.h
  objectivec/GPBWrappers.pbobjc.h
  objectivec/GPBWrappers.pbobjc.m
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_tvOS.xcodeproj/project.pbxproj
  objectivec/Tests/GPBCompileTest14.m
  objectivec/Tests/GPBCompileTest15.m
  objectivec/Tests/GPBCompileTest16.m
  objectivec/Tests/GPBCompileTest17.m
  objectivec/Tests/GPBCompileTest18.m
  objectivec/Tests/GPBCompileTest19.m
  objectivec/Tests/GPBCompileTest20.m
  objectivec/Tests/GPBCompileTest21.m
  objectivec/Tests/GPBCompileTest22.m
  objectivec/Tests/GPBCompileTest23.m
  objectivec/generate_well_known_types.sh
  objectivec/google/protobuf/Any.pbobjc.h
  objectivec/google/protobuf/Api.pbobjc.h
  objectivec/google/protobuf/Duration.pbobjc.h
  objectivec/google/protobuf/Empty.pbobjc.h
  objectivec/google/protobuf/FieldMask.pbobjc.h
  objectivec/google/protobuf/SourceContext.pbobjc.h
  objectivec/google/protobuf/Struct.pbobjc.h
  objectivec/google/protobuf/Timestamp.pbobjc.h
  objectivec/google/protobuf/Type.pbobjc.h
  objectivec/google/protobuf/Wrappers.pbobjc.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: yes

#7188 Fix latest ArgumentException for C# extensions
  Makefile.am
  csharp/generate_protos.sh
  csharp/protos/unittest_issue6936_a.proto
  csharp/protos/unittest_issue6936_b.proto
  csharp/protos/unittest_issue6936_c.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936A.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936B.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936C.cs
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/ExtensionRegistry.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
Labels: c#, cla: yes, kokoro:run, release notes: yes

#7155 Aggregate Metadata Files
  php/composer.json
  php/ext/google/protobuf/def.c
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/proto/test_import_descriptor_proto.proto
  php/tests/well_known_test.php
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes, php, release notes: no

#7132 Enforce recursion depth checking for unknown fields
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/UnknownFieldSet.cs
Labels: c#, cla: yes, release notes: yes

#7195 Fix for wrappers with a zero value
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/basic.rb
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#6525 python: add sphinx docs
  .gitignore
  python/docs/Makefile
  python/docs/conf.py
  python/docs/environment.yml
  python/docs/generate_docs.py
  python/docs/google/protobuf.rst
  python/docs/google/protobuf/any_pb2.rst
  python/docs/google/protobuf/descriptor.rst
  python/docs/google/protobuf/descriptor_database.rst
  python/docs/google/protobuf/descriptor_pb2.rst
  python/docs/google/protobuf/descriptor_pool.rst
  python/docs/google/protobuf/duration_pb2.rst
  python/docs/google/protobuf/empty_pb2.rst
  python/docs/google/protobuf/field_mask_pb2.rst
  python/docs/google/protobuf/json_format.rst
  python/docs/google/protobuf/message.rst
  python/docs/google/protobuf/message_factory.rst
  python/docs/google/protobuf/proto_builder.rst
  python/docs/google/protobuf/reflection.rst
  python/docs/google/protobuf/service.rst
  python/docs/google/protobuf/service_reflection.rst
  python/docs/google/protobuf/struct_pb2.rst
  python/docs/google/protobuf/symbol_database.rst
  python/docs/google/protobuf/text_encoding.rst
  python/docs/google/protobuf/text_format.rst
  python/docs/google/protobuf/timestamp_pb2.rst
  python/docs/google/protobuf/type_pb2.rst
  python/docs/google/protobuf/wrappers_pb2.rst
  python/docs/index.rst
  python/docs/make.bat
  python/docs/requirements.txt
  tests.sh
Labels: cla: yes, release notes: no

#7199 Attempt to mitigate "docker pull" failures
  kokoro/linux/build_and_run_docker.sh
  kokoro/linux/cpp_distcheck/build.sh
Labels: cla: yes, release notes: no

#7198 Fix for JSON serialization of 0/empty-valued wrapper types
  conformance/failure_list_ruby.txt
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#7048 Fix GCC build with PROTOBUF_USE_DLLS enabled
  src/google/protobuf/arena.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
Labels: c++, cla: yes, release notes: no

#7194 Aggregate Metadata Files (#7155)
  php/composer.json
  php/ext/google/protobuf/def.c
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/proto/test_import_descriptor_proto.proto
  php/tests/well_known_test.php
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes, php, release notes: no

#7202 Update the Xcode version number in Kokoro
  kokoro/macos/prepare_build_macos_rc
Labels: cla: yes, release notes: no, testing

#7203 Update the Xcode version number in Kokoro
  kokoro/macos/prepare_build_macos_rc
Labels: cla: yes, release notes: no, testing

#7201 Fix for wrappers with a zero value
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/basic.rb
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#7175 Deterministic `protoc --descriptor_set_out`
  src/google/protobuf/compiler/command_line_interface.cc
Labels: c++, cla: yes, release notes: yes

#7166 Use PROTOBUF_RTTI from port_def.inc macro instead of checking for absence of GOOGLE_PROTOBUF_NO_RTTI macro
  src/google/protobuf/message.h
  src/google/protobuf/stubs/casts.h
Labels: cla: yes, release notes: no

#7204 Fix for JSON serialization of 0/empty-valued wrapper types (#7198)
  conformance/failure_list_ruby.txt
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#7206 Update protobuf version to 3.11.4
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, integration, release notes: no

#7205 Update CHANGES.txt for 3.11.4 release
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#7190 [bazel] Move Java runtime/toolchains into //java
  BUILD
  Makefile.am
  compiler_config_setting.bzl
  examples/.gitignore
  java/BUILD
  java/core/BUILD
  java/lite/BUILD
  java/lite/pom.xml
  java/util/BUILD
  kokoro/linux/bazel/build.sh
  protobuf.bzl
  src/google/protobuf/compiler/command_line_interface.cc
Labels: bazel, cla: yes, java, release notes: yes

#7209 Remove protoc release for 32-bit Macs
  kokoro/release/protoc/macos/build.sh
  protoc-artifacts/pom.xml
Labels: cla: yes, integration, release notes: no

#7210 Backport: enforce recursion depth checking for unknown fields (v3.11.x)
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/UnknownFieldSet.cs
Labels: c#, cla: yes, release notes: yes

#7212 Update CHANGES.txt to include the description of #7210
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#7214 Skip building distribution tar files for 32 bit Mac
  protoc-artifacts/build-zip.sh
Labels: cla: yes, integration, release notes: no

#7215 Remove 32-bit Mac binary from csharp build tools
  csharp/build_tools.sh
Labels: c#, cla: yes, release notes: no

#7227 Update Tools.nuspec to remove 32-bit Mac protoc reference
  csharp/Google.Protobuf.Tools.nuspec
Labels: c#, cla: yes, release notes: no

#7228 Remove 32-bit Mac protoc reference from collect_all_artifacts
  kokoro/release/collect_all_artifacts.sh
Labels: c#, cla: yes, release notes: no

#7231 Merge branch 3.11.x to master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/build_tools.sh
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  kokoro/macos/php7.4_mac/build.sh
  kokoro/macos/php7.4_mac/continuous.cfg
  kokoro/macos/php7.4_mac/presubmit.cfg
  kokoro/release/collect_all_artifacts.sh
  kokoro/release/protoc/macos/build.sh
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/tests/descriptors_test.php
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  tests.sh
Labels: cla: yes, integration, release notes: no

#7230 Improves performance of json_stream_parser.cc by factor 1000
  src/google/protobuf/stubs/strutil.h
Labels: c++, cla: yes, release notes: yes

#7233 bug: #7076 adds ERROR to windows portability files
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
Labels: cla: yes, release notes: no

#7170 Reserve extension for Bazel failure detail metadata
  docs/options.md
Labels: cla: yes, release notes: no

#6813 Fix js message pivot selection
  Makefile.am
  js/gulpfile.js
  js/message.js
  js/message_test.js
  js/testlargenumbers.proto
Labels: cla: yes, javascript, release notes: yes

#7154 python: publish sphinx docs to googleapis.dev
  kokoro/docs/common.cfg
  kokoro/docs/publish-python.sh
  kokoro/docs/python.cfg
  kokoro/docs/trampoline.sh
  python/.repo-metadata.json
Labels: cla: yes

#7150 python: publish sphinx docs to read the docs
  .readthedocs.yml
  python/docs/conf.py
  python/docs/generate_docs.py
  python/docs/google/protobuf.rst
  python/docs/google/protobuf/any_pb2.rst
  python/docs/google/protobuf/descriptor.rst
  python/docs/google/protobuf/descriptor_database.rst
  python/docs/google/protobuf/descriptor_pb2.rst
  python/docs/google/protobuf/descriptor_pool.rst
  python/docs/google/protobuf/duration_pb2.rst
  python/docs/google/protobuf/empty_pb2.rst
  python/docs/google/protobuf/field_mask_pb2.rst
  python/docs/google/protobuf/json_format.rst
  python/docs/google/protobuf/message.rst
  python/docs/google/protobuf/message_factory.rst
  python/docs/google/protobuf/proto_builder.rst
  python/docs/google/protobuf/reflection.rst
  python/docs/google/protobuf/service.rst
  python/docs/google/protobuf/service_reflection.rst
  python/docs/google/protobuf/struct_pb2.rst
  python/docs/google/protobuf/symbol_database.rst
  python/docs/google/protobuf/text_encoding.rst
  python/docs/google/protobuf/text_format.rst
  python/docs/google/protobuf/timestamp_pb2.rst
  python/docs/google/protobuf/type_pb2.rst
  python/docs/google/protobuf/wrappers_pb2.rst
  python/docs/index.rst
  python/setup.py
Labels: cla: yes
