Repository protocolbuffers/protobuf, pull requests merged in 2020-05, with the labels that each got.

#7453 Stop building binary gems for ruby <2.5.
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
Labels: cla: yes, release notes: yes, ruby

#7454 Added changelog entry for removing binary gems for Ruby <2.5.
  CHANGES.txt
Labels: cla: yes, release notes: yes, ruby

#7455 Ignore unknown enum value when ignore_unknown specified
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
Labels: cla: yes, php, release notes: no

#7464 Integrate from Piper for C++, Java, and Python
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/json_format.py
  src/google/protobuf/arena.cc
  src/google/protobuf/arena_impl.h
  src/google/protobuf/compiler/cpp/cpp_string_field.cc
  src/google/protobuf/compiler/cpp/cpp_string_field.h
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/map.h
  src/google/protobuf/map_field.h
  src/google/protobuf/message.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/reflection_ops.cc
  src/google/protobuf/reflection_ops.h
  src/google/protobuf/reflection_ops_unittest.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/port.h
  src/google/protobuf/text_format.cc
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/util/internal/default_value_objectwriter.h
  src/google/protobuf/util/internal/json_stream_parser.h
  src/google/protobuf/util/internal/json_stream_parser_test.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/internal/protostream_objectsource_test.cc
Labels: cla: yes, release notes: no

#7465 Use the name from the descriptor instead of RTTI.
  src/google/protobuf/util/field_mask_util.h
Labels: cla: yes, release notes: no

#7462 Ignore unknown enum value when ignore_unknown specified (#7455)
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/encode_decode_test.php
Labels: cla: yes, php, release notes: no

#7476 Updated generated code for C#.
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3Optional.cs
Labels: cla: yes, release notes: no

#7477 Integrate from Piper for C++, Java, and Python
  conformance/binary_json_conformance_suite.cc
  conformance/binary_json_conformance_suite.h
  conformance/failure_list_csharp.txt
  conformance/failure_list_java.txt
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_php_c_32.txt
  conformance/failure_list_ruby.txt
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3Optional.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  python/google/protobuf/pyext/map_container.cc
  python/google/protobuf/pyext/map_container.h
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor_database_unittest.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/map_test.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/proto3_arena_unittest.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/unittest_proto3_optional.proto
  src/google/protobuf/util/internal/default_value_objectwriter_test.cc
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
Labels: cla: yes, release notes: no

#7466 Implement HasPresence for C#
  csharp/src/Google.Protobuf.Test/Reflection/FieldAccessTest.cs
  csharp/src/Google.Protobuf/Extension.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/SingleFieldAccessor.cs
Labels: c#, cla: yes, release notes: yes

#7468 Fix include path to reflection.h in documentation
  src/google/protobuf/message.h
Labels: c++, cla: yes, release notes: no

#7459 Fix typo on py_proto_library
  protobuf.bzl
Labels: cla: yes, release notes: no

#7434 C#: Get rid of broken GetOption API and expose the "GetOptions()" method on descriptors instead
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf/Reflection/EnumDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
Labels: c#, cla: yes, release notes: yes

#7448 C# Add tests for self-referential options
  Makefile.am
  csharp/generate_protos.sh
  csharp/protos/unittest_selfreferential_options.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestSelfreferentialOptions.cs
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
Labels: c#, cla: yes, release notes: no

#7481 [objc] Remove unnecessary call to [self descriptor] in resolveClassMethod:
  objectivec/GPBMessage.m
Labels: cla: yes, objective-c, release notes: no

#7482 Fixed the cpp_distcheck test
  Makefile.am
Labels: cla: yes, release notes: no

#7306 Bazel: Discontinue JDK 7 compatibility support
  Makefile.am
  java/BUILD
  java/core/BUILD
Labels: bazel, cla: yes, release notes: no

#7451 Support cross-compiling when using the cmake build system.
  cmake/CMakeLists.txt
  cmake/README.md
  cmake/conformance.cmake
  cmake/tests.cmake
Labels: cla: yes, cmake, release notes: no

#7485 Integrate from Piper for C++, Java, and Python
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_cpp.txt
  conformance/failure_list_csharp.txt
  conformance/failure_list_java.txt
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_php_c_32.txt
  conformance/failure_list_ruby.txt
  java/core/generate-test-sources-build.xml
  java/core/src/test/java/com/google/protobuf/FieldPresenceTest.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  java/lite/generate-test-sources-build.xml
  python/google/protobuf/internal/test_proto3_optional.proto
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.cc
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/descriptor_database.h
  src/google/protobuf/io/printer.cc
  src/google/protobuf/io/printer_unittest.cc
  src/google/protobuf/type.pb.h
  src/google/protobuf/unittest_lite.proto
Labels: cla: yes, release notes: no

#7491 Cherry-pick fixes onto 3.12.x branch for 3.12.0-rc2
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto2.cs
  csharp/src/Google.Protobuf.Test.TestProtos/Unittest.cs
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf.Test/Reflection/FieldAccessTest.cs
  csharp/src/Google.Protobuf/Extension.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/SingleFieldAccessor.cs
  java/core/generate-test-sources-build.xml
  java/core/src/test/java/com/google/protobuf/FieldPresenceTest.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  java/lite/generate-test-sources-build.xml
  python/google/protobuf/internal/test_proto3_optional.proto
  src/google/protobuf/compiler/csharp/csharp_helpers.h
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/proto3_arena_unittest.cc
  src/google/protobuf/unittest_proto3_optional.proto
Labels: cla: yes, release notes: no

#7495 Fix integration tests for Go examples
  tests.sh
Labels: cla: yes, release notes: no

#7497 Merge 3.12.x branch to master after 3.12.0-rc2
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf.Test/Reflection/CustomOptionsTest.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/Rakefile
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#6904 C#: Allow readonly view of byteString's data with ByteString.Memory property
  csharp/src/Google.Protobuf/ByteString.cs
Labels: c#, cla: yes, release notes: yes

#7501 Added background information about proto3 presence.
  docs/implementing_proto3_presence.md
Labels: cla: yes, release notes: no

#7503 Fixed the PHP Kokoro build.
  kokoro/macos/php7.3_mac/build.sh
  kokoro/macos/php7.3_mac/continuous.cfg
  kokoro/macos/php7.3_mac/presubmit.cfg
  tests.sh
Labels: cla: yes, release notes: no

#7504 Fixed JavaScript Kokoro tests by installing NodeJS.
  tests.sh
Labels: cla: yes, release notes: no

#7502 Integrate from Piper for C++, Java, and Python
  BUILD
  cmake/tests.cmake
  conformance/ConformanceJava.java
  conformance/failure_list_java.txt
  java/util/src/main/java/com/google/protobuf/util/Timestamps.java
  objectivec/DevTools/compile_testing_protos.sh
  objectivec/Tests/GPBUnittestProtos.m
  python/setup.py
  src/Makefile.am
  src/google/protobuf/arena_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/generated_message_table_driven_lite.h
  src/google/protobuf/map.h
  src/google/protobuf/map_lite_unittest.proto
  src/google/protobuf/map_test_util_impl.h
  src/google/protobuf/map_unittest.proto
  src/google/protobuf/message.h
  src/google/protobuf/message_lite.h
  src/google/protobuf/message_unittest.inc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/reflection_ops.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/text_format.cc
  src/google/protobuf/text_format.h
  src/google/protobuf/unittest_arena.proto
  src/google/protobuf/unittest_no_arena.proto
  src/google/protobuf/unittest_no_arena_import.proto
  src/google/protobuf/unittest_no_arena_lite.proto
  src/google/protobuf/wire_format.cc
Labels: cla: yes, release notes: no

#7458 Fix CLI "too long" issues in py_proto_library.
  protobuf.bzl
Labels: cla: yes, release notes: no

#7496 typo: Auxillary -> Auxiliary
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/generated_message_table_driven.h
  src/google/protobuf/generated_message_table_driven_lite.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7508 Fixed bug in map key sorting for Java TextFormat.
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
Labels: cla: yes, java, release notes: yes

#7516 Added a changelog entry about the Java fix.
  CHANGES.txt
Labels: cla: yes, release notes: no

#7517 Merge release branch into master.
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  docs/implementing_proto3_presence.md
  java/bom/pom.xml
  java/core/pom.xml
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#7529 Restore binary builds for Ruby 2.3 and 2.4
  kokoro/release/ruby/linux/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
Labels: cla: yes, release notes: yes, ruby

#7531 Restore binary builds of Ruby 2.3 and 2.4 (cherry-pick of #7529)
  kokoro/release/ruby/linux/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
Labels: cla: yes

#7524 Use lexical-binding in protobuf-mode.el
  editors/protobuf-mode.el
Labels: cla: yes, release notes: no

#7535 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7539 Cherry-pick of df719723: Simplify template exporting macros
  src/google/protobuf/parse_context.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/repeated_field.cc
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, release notes: yes

#7538 Fix :protobuf_objc bazel target
  BUILD
  kokoro/linux/bazel/build.sh
Labels: bazel, cla: yes, release notes: yes

#7551 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  python/google/protobuf/internal/enum_type_wrapper.py
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/json_format.py
  src/google/protobuf/compiler/cpp/cpp_enum.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/java/java_name_resolver.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/descriptor_database_unittest.cc
  src/google/protobuf/dynamic_message.cc
  src/google/protobuf/dynamic_message_unittest.cc
  src/google/protobuf/extension_set_unittest.cc
  src/google/protobuf/generated_enum_reflection.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/lite_unittest.cc
  src/google/protobuf/map.h
  src/google/protobuf/map_test.cc
  src/google/protobuf/map_test_util_impl.h
  src/google/protobuf/no_field_presence_test.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/preserve_unknown_enum_test.cc
  src/google/protobuf/proto3_arena_unittest.cc
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/port.h
  src/google/protobuf/test_util_lite.cc
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/type.pb.h
  src/google/protobuf/unknown_field_set_unittest.cc
  src/google/protobuf/util/field_mask_util_test.cc
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/message_differencer_unittest.cc
  src/google/protobuf/util/type_resolver_util.cc
  src/google/protobuf/util/type_resolver_util_test.cc
  src/google/protobuf/wire_format_unittest.cc
Labels: cla: yes, release notes: no

#7556 Switch to using git@ for clone, to avoid having to enter password.
  php/release.sh
Labels: cla: yes, release notes: no

#7557 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7561 C# project cleanup for dotnet SDK 3.1
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  global.json
Labels: c#, cla: yes, release notes: no

#7559 Merge the 3.12.x branch to master
  BUILD
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  kokoro/linux/bazel/build.sh
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/release.sh
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/parse_context.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/repeated_field.cc
  src/google/protobuf/repeated_field.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7571 Fixed Python release script to upload using twine instead of distutils.
  python/release.sh
Labels: cla: yes, release notes: no

#7573 Tweak the union used for Extensions to support old generated code.
  objectivec/GPBDescriptor_PackagePrivate.h
Labels: bug, cla: yes, customer issue, objective-c, release notes: yes

#7572 PHP: use php-config instead of explicitly setting include paths.
  php/tests/compatibility_test.sh
  php/tests/compile_extension.sh
  php/tests/gdb_test.sh
  php/tests/multirequest.sh
  php/tests/test.sh
  tests.sh
Labels: cla: yes, release notes: no

#7574 Simplified PHP testing scripts.
  php/tests/compatibility_test.sh
  php/tests/compile_extension.sh
  php/tests/gdb_test.sh
  php/tests/multirequest.sh
  php/tests/test.sh
  tests.sh
Labels: cla: yes, release notes: no

#7552 Update rules_cc
  protobuf_deps.bzl
Labels: cla: yes, release notes: no

#7554 Fix depset/list confusion in #7458.
  protobuf.bzl
Labels: cla: yes, release notes: no
