Repository protocolbuffers/protobuf, pull requests merged in 2020-03, with the labels that each got.

#7275 Add bazel to the list of acceptable mergeable tags
  .github/mergeable.yml
Labels: cla: yes, release notes: no

#7237 [bazel] Update gtest and deprecate //external:{gtest,gtest_main}
  .bazelignore
  BUILD
  WORKSPACE
Labels: bazel, cla: yes, release notes: yes

#7218 [bazel] Remove bootstrap hack from cc_proto_library and add interop with proto_library
  BUILD
  protobuf.bzl
Labels: cla: yes, release notes: no

#7249 cmake: add 'plugin' argument to protobuf_generate
  cmake/protobuf-config.cmake.in
Labels: cla: yes, release notes: no

#7295 Update docs so we can generate better output from Sphinx.
  python/google/protobuf/descriptor.py
  python/google/protobuf/descriptor_pool.py
  python/google/protobuf/internal/containers.py
  python/google/protobuf/message.py
  python/google/protobuf/service.py
  python/google/protobuf/service_reflection.py
  python/google/protobuf/symbol_database.py
  python/google/protobuf/text_format.py
Labels: cla: yes, python, release notes: no

#7280 Add compile-time tests for RTTI to port_def.inc
  src/google/protobuf/port_def.inc
Labels: cla: yes, release notes: no

#7291 Add license header to benchmark/datasets .proto files
  benchmarks/datasets/google_message1/proto2/benchmark_message1_proto2.proto
  benchmarks/datasets/google_message1/proto3/benchmark_message1_proto3.proto
  benchmarks/datasets/google_message2/benchmark_message2.proto
  benchmarks/datasets/google_message3/benchmark_message3.proto
  benchmarks/datasets/google_message3/benchmark_message3_1.proto
  benchmarks/datasets/google_message3/benchmark_message3_2.proto
  benchmarks/datasets/google_message3/benchmark_message3_3.proto
  benchmarks/datasets/google_message3/benchmark_message3_4.proto
  benchmarks/datasets/google_message3/benchmark_message3_5.proto
  benchmarks/datasets/google_message3/benchmark_message3_6.proto
  benchmarks/datasets/google_message3/benchmark_message3_7.proto
  benchmarks/datasets/google_message3/benchmark_message3_8.proto
  benchmarks/datasets/google_message4/benchmark_message4.proto
  benchmarks/datasets/google_message4/benchmark_message4_1.proto
  benchmarks/datasets/google_message4/benchmark_message4_2.proto
  benchmarks/datasets/google_message4/benchmark_message4_3.proto
Labels: cla: yes, release notes: no

#7289 Remove unnecessary branch from ReadTag
  csharp/src/Google.Protobuf.Test/IssuesTest.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
Labels: c#, cla: yes, release notes: yes

#7279 Add benchmark for measuring raw primitive parsing speed
  Makefile.am
  csharp/src/Google.Protobuf.Benchmarks/ParseRawPrimitivesBenchmark.cs
Labels: c#, cla: yes, release notes: no

#7308 Allocated extension number 1079 for grpc-graphql-gateway
  docs/options.md
Labels: cla: yes, release notes: no

#7310 Update missing or renamed kernel files
  Makefile.am
Labels: cla: yes, javascript, release notes: no

#7311 Removed unnecessary includes of well-known types from PHP generator.
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#7309 Allocated Cloudstate protobuf extensions
  docs/options.md
Labels: cla: yes, release notes: no

#7314 Request SummaFT extension closes #7315
  docs/options.md
Labels: cla: yes, release notes: no

#7317 [c++] [protoc] Force to use U.S. English for Win32 error messages (#4317)
  src/google/protobuf/compiler/subprocess.cc
Labels: cla: yes, release notes: no

#7329 Update python README.md
  python/README.md
Labels: cla: yes, release notes: no
