Repository protocolbuffers/protobuf, pull requests merged in 2020-07, with the labels that each got.

#7669 upgrade dotnet SDK in the CI to 3.1
  csharp/install_dotnet_sdk.ps1
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: cla: yes, release notes: no

#7658 C# write benchmark improvements
  csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj
  csharp/src/Google.Protobuf.Benchmarks/WriteRawPrimitivesBenchmark.cs
  csharp/src/Google.Protobuf/WritingPrimitives.cs
Labels: c#, cla: yes, release notes: no

#7652 [bazel] Use proto_library targets to exclude WKPs from code-gen
  BUILD
Labels: bazel, cla: yes, release notes: no

#7656 [README] change go's runtime
  README.md
Labels: cla: yes, release notes: no

#7639 Do not use ADL when transforming string to lowercase
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#7644 Optimize reading strings across segments
  .gitignore
  csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj
  csharp/src/Google.Protobuf.Benchmarks/ParseRawPrimitivesBenchmark.cs
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf.Test/ReadOnlySequenceFactory.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
  csharp/src/Google.Protobuf/ParserInternalState.cs
  csharp/src/Google.Protobuf/ParsingPrimitives.cs
Labels: c#, cla: yes, release notes: yes

#7629 [PHP] Fix GPBUtil::getFullClassName() argument order
  php/src/Google/Protobuf/Internal/Descriptor.php
Labels: cla: yes, php, release notes: yes

#7695 Remove old PHP extension
  Makefile.am
  conformance/failure_list_php_c.txt
  conformance/failure_list_php_c_32.txt
  php/ext/google/protobuf/arena.c
  php/ext/google/protobuf/arena.h
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/array.h
  php/ext/google/protobuf/builtin_descriptors.inc
  php/ext/google/protobuf/bundled_php.h
  php/ext/google/protobuf/config.m4
  php/ext/google/protobuf/convert.c
  php/ext/google/protobuf/convert.h
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/def.h
  php/ext/google/protobuf/encode_decode.c
  php/ext/google/protobuf/make-preload.php
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/map.h
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/message.h
  php/ext/google/protobuf/names.c
  php/ext/google/protobuf/names.h
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/storage.c
  php/ext/google/protobuf/type_check.c
  php/ext/google/protobuf/upb.c
  php/ext/google/protobuf/upb.h
  php/ext/google/protobuf/utf8.c
  php/ext/google/protobuf/utf8.h
  php/ext/google/protobuf2/array.c
  php/ext/google/protobuf2/config.m4
  php/ext/google/protobuf2/def.c
  php/ext/google/protobuf2/map.c
  php/ext/google/protobuf2/message.c
  php/ext/google/protobuf2/protobuf.c
  php/ext/google/protobuf2/protobuf.h
  php/tests/compile_extension.sh
  php/tests/php_implementation_test.php
  php/tests/test.sh
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#7699 Updated version to 4.0.0-rc1.
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#7704 Override pip and virtualenv installation for macOS.
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/python/macos/config.sh
  tests.sh
Labels: cla: yes, release notes: no

#7705 Fix C# optional field reflection when there are regular fields too
  csharp/generate_protos.sh
  csharp/protos/unittest_issues.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/Proto3OptionalTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
Labels: c#, cla: yes, release notes: yes

#7710 Update CHANGES.txt with the C# parsing / serialization overhaul
  CHANGES.txt
Labels: cla: yes, release notes: no

#7723 Temporarily disabled ExtensionRegistryFactoryTest
  java/core/src/test/java/com/google/protobuf/ExtensionRegistryFactoryTest.java
Labels: cla: yes, release notes: no

#7726 Fixed release.sh and setup.py for Python
  python/release.sh
  python/setup.py
Labels: cla: yes, release notes: no

#7727 Cherry-picked #7705 into 4.0.x branch
  csharp/generate_protos.sh
  csharp/protos/unittest_issues.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/Proto3OptionalTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
Labels: cla: yes, release notes: no

#7724 Added proto3 presence support for PHP
  Makefile.am
  php/ext/google/protobuf/message.c
  php/src/GPBMetadata/Google/Protobuf/Struct.php
  php/src/Google/Protobuf/Descriptor.php
  php/src/Google/Protobuf/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/Message.php
  php/src/Google/Protobuf/NullValue.php
  php/src/Google/Protobuf/OneofDescriptor.php
  php/src/Google/Protobuf/Value.php
  php/tests/encode_decode_test.php
  php/tests/generate_protos.sh
  php/tests/generated_class_test.php
  php/tests/proto/test.proto
  php/tests/test.sh
  php/tests/valgrind.supp
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes, php, release notes: yes

#7730 Updated minimum required version for C extension to 7.0.
  php/ext/google/protobuf/package.xml
Labels: cla: yes, php, release notes: no

#7731 Removed obsolete TSRMLS_* usage.
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
Labels: cla: yes, php, release notes: no

#7733 Fix a typo in the README
  java/README.md
Labels: cla: yes, release notes: no

#7738 Adding forgotten duration.proto to the lite library
  java/lite/pom.xml
Labels: cla: yes, java, release notes: yes

#7716 Qualify uses of std::string within protobuf/compiler/ruby/...
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator.h
Labels: cla: yes, release notes: no

#7740 Updated upb to pick up several bugfixes
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_php_c_32.txt
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  php/src/Google/Protobuf/Internal/FieldDescriptor.php
  php/tests/compatibility_test.sh
  php/tests/php_implementation_test.php
  php/tests/test_util.php
Labels: cla: yes, php, release notes: no

#7729 Updated version to 4.0.0-rc2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#7750 Cherry-picked #7738 into 4.0.x branch
  java/lite/pom.xml
Labels: cla: yes, release notes: no

#7754 Update third_party.md
  docs/third_party.md
Labels: cla: yes, documentation, release notes: no

#7711 [Javascript] Disable ESLint and TypeScript on JS protobuf file
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes, release notes: no

#7763 Check realoneof in json parsing
  .gitignore
  php/ext/google/protobuf/php-upb.c
  php/tests/encode_decode_test.php
Labels: cla: yes, php, release notes: no

#7766 Fixed compile_extension.sh --release to actually enable optimization.
  php/tests/compile_extension.sh
Labels: cla: yes, release notes: no
