Repository protocolbuffers/protobuf, pull requests merged in 2020-08, with the labels that each got.

#6474 Add parser and linter libraries to third party docs
  docs/third_party.md
Labels: cla: yes, documentation, release notes: no

#7788 Change some SplitStringUsing calls to Split.
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, release notes: no

#7792 [docs] Update IntelliJ plugin link
  docs/third_party.md
Labels: cla: yes, release notes: no

#7786 Update third_party.md
  docs/third_party.md
Labels: cla: yes, release notes: no

#7777 Reserve 1087 for Wire wire_package
  docs/options.md
Labels: cla: yes, release notes: no

#7752 Add a Codespell action
  .github/workflows/codespell.yml
Labels: cla: yes, release notes: no

#7782 //:protobuf_java_util: discontinue JDK 7 compatibility support.
  java/util/BUILD
Labels: cla: yes, release notes: no

#7793 Port php c extension to php8
  .gitignore
  Makefile.am
  kokoro/linux/php80/build.sh
  kokoro/linux/php80/continuous.cfg
  kokoro/linux/php80/presubmit.cfg
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/convert.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/phpunit.xml
  php/tests/ArrayTest.php
  php/tests/DescriptorsTest.php
  php/tests/EncodeDecodeTest.php
  php/tests/GeneratedClassTest.php
  php/tests/GeneratedPhpdocTest.php
  php/tests/GeneratedServiceTest.php
  php/tests/MapFieldTest.php
  php/tests/PhpImplementationTest.php
  php/tests/WellKnownTest.php
  php/tests/WrapperTypeSettersTest.php
  php/tests/test.sh
  tests.sh
Labels: cla: yes, php, release notes: yes

#7802 No need to generate addtional has method for proto2
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ReservedRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto/EnumReservedRange.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/Internal/UninterpretedOption/NamePart.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: no

#7803 Updated version to 3.13.0-rc3
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#7804 Removed conflicting C# version line
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: cla: yes, release notes: no

#7809 Fixed tests for Python 2 in python/release.sh
  python/release.sh
Labels: cla: yes, release notes: no

#7805 Fix segment fault for proto3 optional
  src/google/protobuf/generated_message_reflection.cc
Labels: c++, cla: yes, python, release notes: yes

#7810 Cherry-picked fix from #7805 to address Python issue
  src/google/protobuf/generated_message_reflection.cc
Labels: cla: yes, release notes: no

#7811 Updated protobuf version to 3.13.0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: no

#7822 Fix version number in php macro
  php/ext/google/protobuf/message.c
Labels: cla: yes, php, release notes: no

#7779 [javalite] Add R8 rule to documentation
  java/lite.md
Labels: cla: yes, release notes: no

#7758 [bazel] Add default shell env to gen_well_known_protos_java
  protobuf.bzl
Labels: cla: yes, release notes: no

#7761 Incorrect use of CMake's newer features
  cmake/protobuf-config.cmake.in
Labels: cla: yes, cmake, release notes: no

#7510 Removed test files from pypi distribution generation code.
  python/setup.py
Labels: cla: yes, release notes: no

#7328 Null Check in UnknownField::AddAll()
  csharp/src/Google.Protobuf/UnknownField.cs
Labels: c#, cla: yes, kokoro:run, release notes: no

#7834 Update Gradle dependency reference format
  java/README.md
Labels: cla: yes, release notes: no

#7845 Integrate from Piper for C++, Java, and Python
  csharp/src/Google.Protobuf.Test/testprotos.pb
  java/core/src/test/java/com/google/protobuf/ExtensionRegistryFactoryTest.java
  python/google/protobuf/descriptor.py
  python/google/protobuf/internal/message_test.py
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/importer_unittest.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/map_field.cc
  src/google/protobuf/map_field.h
  src/google/protobuf/map_field_inl.h
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/map_test.cc
  src/google/protobuf/map_test_util.h
  src/google/protobuf/message.h
  src/google/protobuf/util/internal/utility.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/wire_format.cc
Labels: cla: yes, release notes: no

#7783 Add a setuptools extension for generating Python protobufs
  python/protobuf_distutils/README.md
  python/protobuf_distutils/protobuf_distutils/__init__.py
  python/protobuf_distutils/protobuf_distutils/generate_py_protobufs.py
  python/protobuf_distutils/setup.py
  python/setup.py
  tests.sh
Labels: cla: yes, python, release notes: yes

#7379 JS: parse (un)packed fields conditionally
  conformance/failure_list_js.txt
  js/binary/reader.js
  src/google/protobuf/compiler/js/js_generator.cc
Labels: cla: yes, release notes: yes
