Repository protocolbuffers/protobuf, pull requests merged in 2020-04, with the labels that each got.

#7348 Allocated option number 1086 for ADLINK EdgeSDK
  docs/options.md
Labels: cla: yes, release notes: no

#7352 Ruby: Call "Class#new" over rb_class_new_instance in decoding
  ruby/ext/google/protobuf_c/encode_decode.c
Labels: cla: yes, release notes: yes, ruby

#7361 Integrate from Piper @305053102 for C++, Java, and Python
  conformance/conformance_python.py
  csharp/src/Google.Protobuf.Test/testprotos.pb
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/internal/type_checkers.py
  python/google/protobuf/json_format.py
  src/google/protobuf/arena.h
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/zip_writer.cc
  src/google/protobuf/compiler/zip_writer.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/map.h
  src/google/protobuf/map_field.h
  src/google/protobuf/test_messages_proto2.proto
  src/google/protobuf/test_messages_proto3.proto
  src/google/protobuf/util/internal/expecting_objectwriter.h
  src/google/protobuf/util/internal/mock_error_listener.h
Labels: cla: yes, release notes: no

#7359 Hotfix/protobuf cmake import paths
  cmake/protobuf-config.cmake.in
Labels: cla: yes, cmake, release notes: no

#7372 Update to new upb version
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: no

#7360 Refactor some Protobuf C# microbenchmarks
  Makefile.am
  csharp/src/Google.Protobuf.Benchmarks/BenchmarkDatasetConfig.cs
  csharp/src/Google.Protobuf.Benchmarks/GoogleMessageBenchmark.cs
  csharp/src/Google.Protobuf.Benchmarks/ParseMessagesBenchmark.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmark.cs
Labels: c#, cla: yes, release notes: no

#7378 Integrate from Piper for C++, Java, and Python
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  python/google/protobuf/pyext/message.cc
  src/google/protobuf/compiler/cpp/cpp_field.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/cpp/cpp_string_field.cc
  src/google/protobuf/compiler/java/java_file.cc
  src/google/protobuf/compiler/mock_code_generator.h
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/python/python_generator.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor.proto
  src/google/protobuf/dynamic_message.cc
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/generated_message_table_driven_lite.h
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/util/internal/datapiece.cc
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/internal/object_writer.cc
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/internal/type_info.cc
Labels: cla: yes, release notes: no

#7377 deps: update Guava to 29.0
  java/pom.xml
Labels: cla: yes, release notes: no

#7387 docs: add python-betterproto
  docs/third_party.md
Labels: cla: yes, release notes: no

#7027 Build extensions for Ruby 2.7
  kokoro/linux/dockerfile/release/ruby_rake_compiler/Dockerfile
  kokoro/release/ruby/linux/prepare_build.sh
  kokoro/release/ruby/linux/ruby/ruby_build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Rakefile
  ruby/google-protobuf.gemspec
Labels: cla: yes, release notes: yes, ruby

#7091 Rails2.7 segfaults
  ruby/tests/common_tests.rb
  ruby/tests/repeated_field_test.rb
  tests.sh
Labels: cla: yes, release notes: no, ruby

#7396 Drop 3.3, 3.4 and use single version docker images for all python tests
  README.md
  kokoro/linux/dockerfile/push_testing_images.sh
  kokoro/linux/dockerfile/test/python27/Dockerfile
  kokoro/linux/dockerfile/test/python35/Dockerfile
  kokoro/linux/dockerfile/test/python36/Dockerfile
  kokoro/linux/dockerfile/test/python37/Dockerfile
  kokoro/linux/dockerfile/test/python38/Dockerfile
  kokoro/linux/dockerfile/test/python_jessie/Dockerfile
  kokoro/linux/dockerfile/test/python_stretch/Dockerfile
  kokoro/linux/python27/build.sh
  kokoro/linux/python27_cpp/build.sh
  kokoro/linux/python33/build.sh
  kokoro/linux/python33/continuous.cfg
  kokoro/linux/python33/presubmit.cfg
  kokoro/linux/python33_cpp/build.sh
  kokoro/linux/python33_cpp/continuous.cfg
  kokoro/linux/python33_cpp/presubmit.cfg
  kokoro/linux/python34/build.sh
  kokoro/linux/python34/continuous.cfg
  kokoro/linux/python34/presubmit.cfg
  kokoro/linux/python34_cpp/build.sh
  kokoro/linux/python34_cpp/continuous.cfg
  kokoro/linux/python34_cpp/presubmit.cfg
  kokoro/linux/python35/build.sh
  kokoro/linux/python35_cpp/build.sh
  kokoro/linux/python36/build.sh
  kokoro/linux/python36_cpp/build.sh
  kokoro/linux/python37/build.sh
  kokoro/linux/python37_cpp/build.sh
  kokoro/linux/python38/build.sh
  kokoro/linux/python38_cpp/build.sh
Labels: cla: yes, python, release notes: yes

#7403 Move to constexpr.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, cleanup, release notes: no

#7402 Integrate from Piper for C++, Java, and Python
  python/google/protobuf/pyext/message.cc
  python/google/protobuf/text_format.py
  src/google/protobuf/arena_impl.h
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/java/java_enum_field_lite.cc
  src/google/protobuf/compiler/java/java_message_field_lite.cc
  src/google/protobuf/compiler/java/java_primitive_field_lite.cc
  src/google/protobuf/compiler/java/java_string_field_lite.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/proto3_arena_unittest.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
Labels: cla: yes, release notes: no

#7397 Ruby: assigning 'nil' to submessage should clear the field.
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/storage.c
  ruby/tests/basic_proto2.rb
Labels: cla: yes, release notes: yes, ruby

#7294 Generate documentation for internal.container.
  python/docs/generate_docs.py
  python/docs/google/protobuf/internal/containers.rst
  python/docs/index.rst
Labels: cla: yes, release notes: no

#7385 Add Ruby tests for oneof cases.
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
Labels: cla: yes, release notes: no

#7406 Implemented proto3 presence for Ruby.
  ruby/Rakefile
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/encode_decode.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/storage.c
  ruby/ext/google/protobuf_c/upb.c
  ruby/ext/google/protobuf_c/upb.h
  ruby/tests/basic.rb
  ruby/tests/basic_test.proto
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator.h
Labels: cla: yes, release notes: yes, ruby

#7390 Add application note for explicit presence tracking.
  docs/field_presence.md
Labels: cla: yes, release notes: yes

#7407 Howto doc for implementing proto3 presence in a code generator.
  docs/implementing_proto3_presence.md
Labels: cla: yes

#7416 Added some info about Reflection, and a note about timeline.
  docs/implementing_proto3_presence.md
Labels: cla: yes, release notes: no

#7386 Test in Ruby 2.7
  kokoro/linux/dockerfile/test/ruby/Dockerfile
  kokoro/linux/ruby27/build.sh
  kokoro/linux/ruby27/continuous.cfg
  kokoro/linux/ruby27/presubmit.cfg
  kokoro/macos/ruby27/build.sh
  kokoro/macos/ruby27/continuous.cfg
  kokoro/macos/ruby27/presubmit.cfg
  ruby/compatibility_tests/v3.0.0/tests/repeated_field_test.rb
  ruby/tests/gc_test.rb
  ruby/travis-test.sh
  tests.sh
Labels: cla: yes, release notes: no

#7423 Typo in 'disciplines'
  docs/field_presence.md
Labels: release notes: no

#7430 Update shell format in installation instructions.
  src/README.md
Labels: cla: yes, release notes: no

#7435 Integrate from Piper for C++, Java, and Python
  conformance/binary_json_conformance_suite.h
  conformance/conformance_test.h
  conformance/text_format_conformance_suite.h
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  python/google/protobuf/internal/text_format_test.py
  python/google/protobuf/internal/type_checkers.py
  python/google/protobuf/json_format.py
  python/google/protobuf/text_format.py
  src/google/protobuf/arena_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_map_field.cc
  src/google/protobuf/compiler/java/java_enum.cc
  src/google/protobuf/compiler/java/java_enum_lite.cc
  src/google/protobuf/compiler/java/java_field.cc
  src/google/protobuf/compiler/java/java_helpers.cc
  src/google/protobuf/compiler/java/java_helpers.h
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field_lite.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/extension_set_unittest.cc
  src/google/protobuf/implicit_weak_message.h
  src/google/protobuf/io/coded_stream_unittest.cc
  src/google/protobuf/map_entry.h
  src/google/protobuf/map_field.cc
  src/google/protobuf/map_field.h
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/map_test_util.h
  src/google/protobuf/map_type_handler.h
  src/google/protobuf/message.h
  src/google/protobuf/message_lite.h
  src/google/protobuf/metadata_lite.h
  src/google/protobuf/reflection.h
  src/google/protobuf/repeated_field.cc
  src/google/protobuf/repeated_field.h
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/util/internal/datapiece.cc
  src/google/protobuf/util/internal/json_escaping.h
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/time_util_test.cc
  src/google/protobuf/wire_format_lite.h
Labels: cla: yes, release notes: no

#7437 Use the new helpers from Descriptor.
  src/google/protobuf/compiler/objectivec/objectivec_map_field.cc
Labels: cla: yes, objective-c, release notes: no

#7428 Fix when compiling without RTTI
  src/google/protobuf/util/field_mask_util.h
Labels: c++, cla: yes, release notes: no

#7442 Added changelog for 3.12.x.
  CHANGES.txt
Labels: cla: yes

#7449 Update version to 3.12.0-rc1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes
