Repository protocolbuffers/protobuf, pull requests merged in 2020-11, with the labels that each got.

#7997 Update scalapb URL and fix typo in name
  docs/options.md
Labels: cla: yes, release notes: no

#8000 [PHP] New version of upb, and a new hash function wyhash in third_party.
  Makefile.am
  conformance/Makefile.am
  conformance/failure_list_php_c.txt
  conformance/failure_list_php_c_32.txt
  php/ext/google/protobuf/config.m4
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  php/prepare_c_extension.sh
  php/tests/compile_extension.sh
  tests.sh
  third_party/wyhash/LICENSE
  third_party/wyhash/wyhash.h
Labels: cla: yes, php, release notes: yes

#8005 Moved HasOneof test into GeneratedClassTest.php, to avoid the extra file.
  php/phpunit.xml
  php/tests/GeneratedClassTest.php
  php/tests/HasOneofTest.php
  php/tests/test.sh
Labels: cla: yes, php, release notes: no

#8006 [PHP] Optimized away hex2bin() call in generated code
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#8010 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/src/GPBMetadata/Google/Protobuf/Any.php
  php/src/GPBMetadata/Google/Protobuf/Api.php
  php/src/GPBMetadata/Google/Protobuf/Duration.php
  php/src/GPBMetadata/Google/Protobuf/FieldMask.php
  php/src/GPBMetadata/Google/Protobuf/GPBEmpty.php
  php/src/GPBMetadata/Google/Protobuf/SourceContext.php
  php/src/GPBMetadata/Google/Protobuf/Struct.php
  php/src/GPBMetadata/Google/Protobuf/Timestamp.php
  php/src/GPBMetadata/Google/Protobuf/Type.php
  php/src/GPBMetadata/Google/Protobuf/Wrappers.php
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8011 Remove GOOGLE_PROTOBUF_SUPPORT_SYSTEM_MEMORY
  csharp/src/Google.Protobuf/ByteString.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/IBufferMessage.cs
Labels: c#, cla: yes, cleanup, release notes: no

#7928 Fix PyUnknownFields memory leak
  python/google/protobuf/internal/unknown_fields_test.py
  python/google/protobuf/pyext/unknown_fields.cc
Labels: cla: yes, python, release notes: yes

#8013 Deduplicate string suffix predicates
  src/google/protobuf/compiler/python/python_generator.cc
Labels: cla: yes, release notes: no

#8022 [PHP] Fixes for package.xml: added/removed source files.
  php/ext/google/protobuf/package.xml
Labels: cla: yes, php, release notes: no

#8024 Updated python/release.sh to use Python 3 for setup.py
  python/release.sh
Labels: cla: yes, release notes: no

#8025 Fixed PHP version and release notes
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.c
Labels: cla: yes, release notes: no

#8026 Update protobuf version to 3.14.0-rc2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8030 Updated CHANGES.txt for the 3.14.0 release
  CHANGES.txt
Labels: cla: yes, release notes: no

#8029 Update protobuf version to 3.14.0-rc3
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8035 Fix parsing negative Int32Value that crosses segment boundary
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf.Test/WellKnownTypes/WrappersTest.cs
  csharp/src/Google.Protobuf/ParsingPrimitivesWrappers.cs
Labels: P1, c#, cla: yes, release notes: yes

#8048 Merge 3.14.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/src/GPBMetadata/Google/Protobuf/Any.php
  php/src/GPBMetadata/Google/Protobuf/Api.php
  php/src/GPBMetadata/Google/Protobuf/Duration.php
  php/src/GPBMetadata/Google/Protobuf/FieldMask.php
  php/src/GPBMetadata/Google/Protobuf/GPBEmpty.php
  php/src/GPBMetadata/Google/Protobuf/SourceContext.php
  php/src/GPBMetadata/Google/Protobuf/Struct.php
  php/src/GPBMetadata/Google/Protobuf/Timestamp.php
  php/src/GPBMetadata/Google/Protobuf/Type.php
  php/src/GPBMetadata/Google/Protobuf/Wrappers.php
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/release.sh
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8053 Fix some -Wunused-parameter warnings
  src/google/protobuf/arenastring.h
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/map_type_handler.h
Labels: c++, cla: yes, release notes: yes

#8052 Fix detecting file as directory on zOS issue #8051
  src/google/protobuf/compiler/importer.cc
Labels: c++, cla: yes, release notes: yes

#7645 Change ByteString to use memory and support unsafe create without copy
  Makefile.am
  csharp/src/Google.Protobuf.Benchmarks/ByteStringBenchmark.cs
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf/ByteString.cs
  csharp/src/Google.Protobuf/ByteStringAsync.cs
  csharp/src/Google.Protobuf/UnsafeByteOperations.cs
Labels: c#, cla: yes, release notes: yes

#8080 Install examples in `/usr/local/share/protobuf/examples`.
  cmake/install.cmake
Labels: c++, cla: yes, release notes: no

#7180 Fix std::is_pod deprecated in C++20
  src/google/protobuf/arena.h
  src/google/protobuf/generated_message_table_driven.h
  src/google/protobuf/generated_message_table_driven_lite.h
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, release notes: yes

#8089 Fixed some minor issues
  .github/workflows/codespell.yml
  objectivec/GPBMessage.m
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#8077 Updated ax_pthread.m4 to its most recent upstream version
  m4/ax_pthread.m4
Labels: cla: yes, release notes: no

#8042 unregister INI entries and fix invalid read on shutdown
  php/ext/google/protobuf/protobuf.c
Labels: cla: yes, php, release notes: yes

#8092 Work around -Werror=type-limits under gcc 10.2
  src/google/protobuf/parse_context.h
Labels: c++, cla: yes, release notes: no

#8103 Update docker image for php8
  kokoro/linux/dockerfile/test/php80/Dockerfile
Labels: cla: yes, php, release notes: no

#8033 Update param type for PHP Internal Mapfield::offsetGet
  php/src/Google/Protobuf/Internal/MapField.php
Labels: cla: yes, php, release notes: no

#8098 stubs/mutex: Fix compilation by initializing variable in WrappedMutex class.
  src/google/protobuf/stubs/mutex.h
Labels: c++, cla: yes, release notes: no
