Repository protocolbuffers/protobuf, pull requests merged in 2020-10, with the labels that each got.

#7932 Mark some Bazel targets as "manual."
  BUILD
Labels: cla: yes, release notes: no

#7936 Allow `generate_py_protobufs` to find a custom protoc
  python/protobuf_distutils/protobuf_distutils/generate_py_protobufs.py
Labels: cla: yes, release notes: no

#7937 Enhance documentation for `generate_py_protobufs`.
  python/protobuf_distutils/README.md
  python/protobuf_distutils/setup.py
Labels: cla: yes, release notes: no

#7907 Update default dependency for gtest.
  BUILD
  WORKSPACE
Labels: bazel, cla: yes, release notes: no

#7950 Update version number to 3.13.0.1 for php
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, php, release notes: no

#7952 Merge 3.13.x into master
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, release notes: no

#7951 Use the https address for git clone
  php/release.sh
Labels: cla: yes, php, release notes: no

#7955 Add cmake and protoc to mergeable config
  .github/mergeable.yml
Labels: cla: yes, release notes: no

#7956 Remove php 5 tests on mac
  kokoro/macos/php5.6_mac/build.sh
  kokoro/macos/php5.6_mac/continuous.cfg
  kokoro/macos/php5.6_mac/presubmit.cfg
  tests.sh
Labels: cla: yes, release notes: no

#7949 Adds a CMake option to build `libprotoc` separately
  cmake/CMakeLists.txt
  cmake/install.cmake
Labels: c++, cla: yes, cmake, protoc, release notes: yes

#7511 Removed the unnecessary setuptools package dependency for Python package
  python/setup.py
Labels: cla: yes, python, release notes: yes

#7940 Upgrade System.Memory dependency to 4.5.3
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, cla: yes, release notes: no

#7954 Fix finding google/protobuf/descriptor.proto on FreeBSD
  src/google/protobuf/compiler/command_line_interface.cc
Labels: c++, cla: yes, release notes: no

#7973 Updated compiler code to fully qualify std::string
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/csharp/csharp_doc_comment.cc
  src/google/protobuf/compiler/csharp/csharp_enum.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.h
  src/google/protobuf/compiler/csharp/csharp_generator.cc
  src/google/protobuf/compiler/csharp/csharp_generator.h
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
  src/google/protobuf/compiler/csharp/csharp_helpers.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_names.h
  src/google/protobuf/compiler/objectivec/objectivec_enum.cc
  src/google/protobuf/compiler/objectivec/objectivec_enum.h
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.h
  src/google/protobuf/compiler/objectivec/objectivec_extension.cc
  src/google/protobuf/compiler/objectivec/objectivec_extension.h
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_field.h
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_generator.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers_unittest.cc
  src/google/protobuf/compiler/objectivec/objectivec_map_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_map_field.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
  src/google/protobuf/compiler/objectivec/objectivec_message_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_message_field.h
  src/google/protobuf/compiler/objectivec/objectivec_oneof.cc
  src/google/protobuf/compiler/objectivec/objectivec_oneof.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
  src/google/protobuf/compiler/ruby/ruby_generator_unittest.cc
Labels: cla: yes, release notes: no

#7987 Switch to atomic for setting autocreated objects.
  objectivec/GPBMessage.m
  objectivec/GPBUtilities.m
  objectivec/GPBUtilities_PackagePrivate.h
Labels: cla: yes, objective-c, release notes: no

#7971 [CMake] Fix a CMake module for support RelWithDebInfo and MinSizeRel install
  cmake/protobuf-module.cmake.in
Labels: cla: yes, cmake, release notes: no

#7701 annotate ByteString.CopyFrom(ReadOnlySpan<byte>) as SecuritySafeCritical
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf/ByteString.cs
Labels: c#, cla: yes, release notes: yes

#7988 Spell check only comments and strings in vim
  editors/proto.vim
Labels: cla: yes, release notes: no

#7944 [PHP] Native C well-known types
  Makefile.am
  php/ext/google/protobuf/bundled_php.h
  php/ext/google/protobuf/config.m4
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/def.h
  php/ext/google/protobuf/make-preload.php
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/wkt.inc
  php/generate_descriptor_protos.sh
  php/src/GPBMetadata/Google/Protobuf/Any.php
  php/src/GPBMetadata/Google/Protobuf/Api.php
  php/src/GPBMetadata/Google/Protobuf/Duration.php
  php/src/GPBMetadata/Google/Protobuf/FieldMask.php
  php/src/GPBMetadata/Google/Protobuf/GPBEmpty.php
  php/src/GPBMetadata/Google/Protobuf/SourceContext.php
  php/src/GPBMetadata/Google/Protobuf/Struct.php
  php/src/GPBMetadata/Google/Protobuf/Timestamp.php
  php/src/GPBMetadata/Google/Protobuf/Type.php
  php/src/GPBMetadata/Google/Protobuf/Wrappers.php
  php/src/Google/Protobuf/Any.php
  php/src/Google/Protobuf/Api.php
  php/src/Google/Protobuf/BoolValue.php
  php/src/Google/Protobuf/BytesValue.php
  php/src/Google/Protobuf/DoubleValue.php
  php/src/Google/Protobuf/Duration.php
  php/src/Google/Protobuf/Enum.php
  php/src/Google/Protobuf/EnumValue.php
  php/src/Google/Protobuf/Field.php
  php/src/Google/Protobuf/Field/Cardinality.php
  php/src/Google/Protobuf/Field/Kind.php
  php/src/Google/Protobuf/FieldMask.php
  php/src/Google/Protobuf/FloatValue.php
  php/src/Google/Protobuf/Int32Value.php
  php/src/Google/Protobuf/Int64Value.php
  php/src/Google/Protobuf/Internal/AnyBase.php
  php/src/Google/Protobuf/Internal/TimestampBase.php
  php/src/Google/Protobuf/Method.php
  php/src/Google/Protobuf/Mixin.php
  php/src/Google/Protobuf/Option.php
  php/src/Google/Protobuf/SourceContext.php
  php/src/Google/Protobuf/StringValue.php
  php/src/Google/Protobuf/Syntax.php
  php/src/Google/Protobuf/Timestamp.php
  php/src/Google/Protobuf/Type.php
  php/src/Google/Protobuf/UInt32Value.php
  php/src/Google/Protobuf/UInt64Value.php
  php/tests/compile_extension.sh
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/php/php_generator.h
Labels: cla: yes, php, release notes: yes
