Repository protocolbuffers/protobuf, pull requests merged in 2020-12, with the labels that each got.

#8108 Conformance/CMake: Remove non-existence binary_json_conformance_main.cc file.
  cmake/conformance.cmake
Labels: cla: yes, release notes: no

#8111 Allocate extension 1089 to ScalaPB validate
  docs/options.md
Labels: cla: yes, release notes: no

#8112 Update docker file for php7
  kokoro/linux/dockerfile/test/php/Dockerfile
Labels: cla: yes, php, release notes: no

#8106 Don't include sys/param.h for _BYTE_ORDER
  src/google/protobuf/io/coded_stream.h
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes, release notes: yes

#8116 Update docker file for php 32bit tests
  kokoro/linux/dockerfile/test/php_32bit/Dockerfile
Labels: cla: yes, php, release notes: no

#8105 Port for php8
  .gitignore
  README.md
  kokoro/linux/php80/build.sh
  php/composer.json
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/wkt.inc
  php/tests/ArrayTest.php
  php/tests/DescriptorsTest.php
  php/tests/EncodeDecodeTest.php
  php/tests/GeneratedClassTest.php
  php/tests/GeneratedPhpdocTest.php
  php/tests/GeneratedServiceTest.php
  php/tests/MapFieldTest.php
  php/tests/PhpImplementationTest.php
  php/tests/WellKnownTest.php
  php/tests/WrapperTypeSettersTest.php
  php/tests/test.sh
  php/tests/test_base.php
  tests.sh
Labels: cla: yes, php, release notes: no

#7991 deps: update to Guava 30
  java/pom.xml
Labels: cla: yes, java, release notes: no

#8115 Remove PROTOBUF_MAYBE_CONSTEXPR and make the constructor constexpr ev…
  src/google/protobuf/map_field.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/stubs/mutex.h
Labels: cla: yes, release notes: no

#8126 [python] Add macOS big sur compatibility
  python/setup.py
Labels: cla: yes, python, release notes: yes

#8140 C#: do not use <PublicSign>true</PublicSign> on non-windows
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj
  csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, cla: yes, release notes: no

#8138 Update kokoro badge bucket to protobuf-kokoro-badges
  README.md
Labels: cla: yes, integration, release notes: no

#8161 Fix Mac tests by making an unshallow copy of Homebrew repos
  kokoro/macos/prepare_build_macos_rc
Labels: cla: yes, release notes: no

#8154 remove CMAKE_THREAD_LIBS_INIT from pkgconfig CFLAGS
  cmake/protobuf-lite.pc.cmake
  cmake/protobuf.pc.cmake
Labels: c++, cla: yes, release notes: yes

#8159 Fix TextFormatMapTest.DynamicMessage issue#5136
  src/google/protobuf/map_test.cc
Labels: c++, cla: yes, release notes: yes

#8160 Fix for compiler warning issue#8145
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: c++, cla: yes, release notes: yes

#8164 fix: support deprecated enums for GCC < 6
  src/google/protobuf/port_def.inc
Labels: c++, cla: yes, release notes: yes

#8167 Update options.md - Added 'Astounding' Project
  docs/options.md
Labels: cla: yes, release notes: no

#8125 Fix somes warning when compiling with Visual Studio 2019 on x64 target
  src/google/protobuf/parse_context.h
Labels: c++, cla: yes, release notes: yes
