Repository protocolbuffers/protobuf, pull requests merged in 2020-06, with the labels that each got.

#7580 Updated version to 3.12.3 and updated CHANGES.txt.
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  generate_descriptor_proto.sh
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7583 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  cmake/README.md
  conformance/failure_list_python.txt
  conformance/failure_list_python_cpp.txt
  js/message.js
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/internal/well_known_types.py
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/arena_unittest.cc
  src/google/protobuf/compiler/code_generator.h
  src/google/protobuf/compiler/cpp/cpp_generator.h
  src/google/protobuf/compiler/cpp/cpp_string_field.cc
  src/google/protobuf/compiler/java/java_generator.cc
  src/google/protobuf/compiler/java/java_generator.h
  src/google/protobuf/compiler/mock_code_generator.cc
  src/google/protobuf/compiler/mock_code_generator.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/compiler/python/python_generator.h
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor_database.cc
  src/google/protobuf/generated_enum_reflection.h
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/map.h
  src/google/protobuf/message.cc
  src/google/protobuf/parse_context.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/hash.h
  src/google/protobuf/stubs/stringpiece.cc
  src/google/protobuf/stubs/stringpiece.h
  src/google/protobuf/stubs/structurally_valid.cc
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/util/field_mask_util.h
  src/google/protobuf/util/internal/expecting_objectwriter.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7490 Overcome the `ref struct` limitation for pre-roslyn compilers by introducing GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE for generated code
  CHANGES.txt
  Makefile.am
  csharp/src/AddressBook/Addressbook.cs
  csharp/src/Google.Protobuf.Benchmarks/BenchmarkMessage1Proto3.cs
  csharp/src/Google.Protobuf.Benchmarks/Benchmarks.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmarkMessages.cs
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  csharp/src/Google.Protobuf.Test.TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto2.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/Unittest.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImport.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublic.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublicProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936B.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936C.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3Optional.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestSelfreferentialOptions.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf.Test/RefStructCompatibilityTest.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Any.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Api.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Duration.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Empty.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMask.cs
  csharp/src/Google.Protobuf/WellKnownTypes/SourceContext.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Struct.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Timestamp.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Type.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Wrappers.cs
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.h
  src/google/protobuf/compiler/csharp/csharp_map_field.cc
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
Labels: c#, cla: yes, release notes: yes

#7589 Tweak return types for GetSupportedFeatures to unit64_t.
  src/google/protobuf/compiler/csharp/csharp_generator.cc
  src/google/protobuf/compiler/csharp/csharp_generator.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.h
  src/google/protobuf/compiler/ruby/ruby_generator.h
Labels: cla: yes, cleanup, release notes: no

#7528 Initial module docstring for python _pb2
  src/google/protobuf/compiler/python/python_generator.cc
Labels: cla: yes, python, release notes: yes

#7590 Merge release branch
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  generate_descriptor_proto.sh
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  objectivec/GPBDescriptor_PackagePrivate.h
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/release.sh
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7412 Improve performance of parsing repeated fixed sized types
  csharp/src/Google.Protobuf.Benchmarks/ParseMessagesBenchmark.cs
  csharp/src/Google.Protobuf.Test/Collections/RepeatedFieldTest.cs
  csharp/src/Google.Protobuf.Test/ReadOnlySequenceFactory.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
Labels: c#, cla: yes, release notes: yes

#7585 Added changelog entries for all changes already merged from google3.
  CHANGES.txt
Labels: cla: yes, release notes: no

#7602 ObjC Import generation tweaks
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c, release notes: no

#7592 Enable experimental presence detection in JS.
  js/gulpfile.js
  js/proto3_test.js
  js/proto3_test.proto
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/js/js_generator.h
Labels: cla: yes, javascript, release notes: yes

#7596 annotate ByteString.Span and ByteString.Memory as SecuritySafeCritical
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf/ByteString.cs
Labels: c#, cla: yes, release notes: yes

#7579 Added Embedded Proto to third_party.md.
  docs/third_party.md
Labels: cla: yes, release notes: no

#7609 ObjC Support a runtime import override.
  objectivec/README.md
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c, release notes: no

#7605 De-duplicated code to generate PHP protos and install phpunit.
  Makefile.am
  php/composer.json
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
  php/tests/compile_extension.sh
  php/tests/generate_protos.sh
  php/tests/generated_class_test.php
  php/tests/test.sh
  tests.sh
Labels: cla: yes, release notes: no

#7630 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  conformance/failure_list_python.txt
  conformance/failure_list_python_cpp.txt
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskUtil.java
  java/util/src/test/java/com/google/protobuf/util/FieldMaskTreeTest.java
  java/util/src/test/java/com/google/protobuf/util/FieldMaskUtilTest.java
  python/google/protobuf/internal/decoder.py
  python/google/protobuf/internal/encoder.py
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/internal/message_test.py
  python/google/protobuf/internal/python_message.py
  python/google/protobuf/json_format.py
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/descriptor.h
  python/google/protobuf/pyext/descriptor_containers.cc
  python/google/protobuf/pyext/descriptor_pool.cc
  python/google/protobuf/pyext/extension_dict.cc
  python/google/protobuf/pyext/message.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/main.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/compiler/python/python_generator.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/map_entry_lite.h
  src/google/protobuf/map_type_handler.h
  src/google/protobuf/repeated_field.h
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/util/internal/json_stream_parser.cc
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/internal/utility.cc
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#7624 documentation: fix path for fetching submodules
  cmake/README.md
Labels: cla: yes, release notes: no

#7626 Add link to third-party Elixir library
  docs/third_party.md
Labels: cla: yes, release notes: no

#7620 Add imenu index support
  editors/protobuf-mode.el
Labels: cla: yes, release notes: no

#7614 New PHP C Extension based on upb_msg
  Makefile.am
  php/ext/google/protobuf2/arena.c
  php/ext/google/protobuf2/arena.h
  php/ext/google/protobuf2/array.c
  php/ext/google/protobuf2/array.h
  php/ext/google/protobuf2/bundled_php.h
  php/ext/google/protobuf2/config.m4
  php/ext/google/protobuf2/convert.c
  php/ext/google/protobuf2/convert.h
  php/ext/google/protobuf2/def.c
  php/ext/google/protobuf2/def.h
  php/ext/google/protobuf2/make-preload.php
  php/ext/google/protobuf2/map.c
  php/ext/google/protobuf2/map.h
  php/ext/google/protobuf2/message.c
  php/ext/google/protobuf2/message.h
  php/ext/google/protobuf2/names.c
  php/ext/google/protobuf2/names.h
  php/ext/google/protobuf2/php-upb.c
  php/ext/google/protobuf2/php-upb.h
  php/ext/google/protobuf2/protobuf.c
  php/ext/google/protobuf2/protobuf.h
  php/src/Google/Protobuf/Any.php
  php/src/Google/Protobuf/Internal/DescriptorPool.php
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/tests/compile_extension.sh
  php/tests/test.sh
  tests.sh
Labels: cla: yes, php, release notes: yes

#7660 Bugfix for when message constructor has no argument.
  php/ext/google/protobuf2/message.c
Labels: cla: yes

#7666 Fix C# build by regenerating test protos
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
Labels: cla: yes, release notes: no
