Repository protocolbuffers/protobuf, pull requests merged in 2020-09, with the labels that each got.

#7865 Fix some -Wunused-parameter warnings which appeared in release 3.13.0.
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/message.h
Labels: cla: yes, release notes: no

#7871 Update rules_proto
  protobuf_deps.bzl
Labels: cla: yes, release notes: no

#7869 Fix -Wmissing-field-initializers warning
  src/google/protobuf/descriptor_database.cc
Labels: cla: yes, release notes: no

#7874 remove GetArena in _InternalParse
  src/google/protobuf/any.pb.cc
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/wrappers.pb.cc
Labels: cla: yes, release notes: no

#7878 Fix more -Wunused-parameter warnings
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/map.h
Labels: cla: yes, release notes: no

#7883 Added support for "==" to the PHP C extension
  php/ext/google/protobuf/message.c
  php/tests/GeneratedClassTest.php
Labels: cla: yes, php, release notes: yes

#7892 Add Purescript protobuf to third-party list
  docs/third_party.md
Labels: cla: yes, release notes: no

#7898 python/setup.py: remove unneeded wheel dependency
  python/setup.py
Labels: cla: yes, release notes: no

#7900 PHP: Added `==` operators for Map and Array.
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/array.h
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/map.h
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/message.h
  php/ext/google/protobuf/php-upb.c
  php/tests/ArrayTest.php
  php/tests/MapFieldTest.php
Labels: cla: yes, php, release notes: yes

#7902 Remove uses of pkg_resources in non-namespace packages.
  python/google/protobuf/__init__.py
  python/google/protobuf/pyext/__init__.py
Labels: cla: yes, python, release notes: yes

#7908 [bazel/py] Omit google/__init__.py from the Protobuf runtime.
  BUILD
Labels: bazel, cla: yes, python, release notes: yes

#7916 Reserve 1088 for Confluent Schema Registry
  docs/options.md
Labels: cla: yes, release notes: no

#7920 Fix undef warning when building w/ clang or gcc on Windows
  src/google/protobuf/stubs/port.h
Labels: cla: yes, release notes: no

#7924 Work around Codespell false positive
  .github/workflows/codespell.yml
Labels: cla: yes, release notes: no

#7913 Fix: gcc 9 -Warray-bounds warnings about memset() in generated code
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
Labels: cla: yes, release notes: no

#7927 Change Python kokoro configs to test only their specified version.
  kokoro/linux/dockerfile/test/python27/Dockerfile
  kokoro/linux/dockerfile/test/python35/Dockerfile
  kokoro/linux/dockerfile/test/python36/Dockerfile
  kokoro/linux/dockerfile/test/python37/Dockerfile
  kokoro/linux/dockerfile/test/python38/Dockerfile
  kokoro/linux/python27/continuous.cfg
  kokoro/linux/python27/presubmit.cfg
  kokoro/linux/python27_cpp/continuous.cfg
  kokoro/linux/python27_cpp/presubmit.cfg
  kokoro/linux/python35/continuous.cfg
  kokoro/linux/python35/presubmit.cfg
  kokoro/linux/python35_cpp/continuous.cfg
  kokoro/linux/python35_cpp/presubmit.cfg
  kokoro/linux/python36/continuous.cfg
  kokoro/linux/python36/presubmit.cfg
  kokoro/linux/python36_cpp/continuous.cfg
  kokoro/linux/python36_cpp/presubmit.cfg
  kokoro/linux/python37/continuous.cfg
  kokoro/linux/python37/presubmit.cfg
  kokoro/linux/python37_cpp/continuous.cfg
  kokoro/linux/python37_cpp/presubmit.cfg
  kokoro/linux/python38/continuous.cfg
  kokoro/linux/python38/presubmit.cfg
  kokoro/linux/python38_cpp/continuous.cfg
  kokoro/linux/python38_cpp/presubmit.cfg
  python/tox.ini
  tests.sh
Labels: cla: yes, python, release notes: no, testing
