Repository protocolbuffers/protobuf, pull requests merged in 2021-05, with the labels that each got.

#8548 fix typo
  js/README.md
Labels: cla: yes, release notes: no

#8539 Stop using GG_ prefixed macros
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
Labels: cla: yes, release notes: no

#8555 Make update_version.py compatible with Python 3
  update_version.py
Labels: cla: yes, release notes: no

#8528 Fix php json parsing not throwing error for unknown field.
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/EncodeDecodeTest.php
Labels: cla: yes, php, release notes: no

#8558 Updated and simplified PHP testing structure
  Makefile.am
  php/composer.json
  php/generate_test_protos.sh
  php/phpunit.xml
  php/tests/DescriptorsTest.php
  php/tests/GeneratedClassTest.php
  php/tests/GeneratedPhpdocTest.php
  php/tests/PhpImplementationTest.php
  php/tests/autoload.php
  php/tests/bootstrap_phpunit.php
  php/tests/compile_extension.sh
  php/tests/force_c_ext.php
  php/tests/generate_protos.sh
  php/tests/memory_leak_test.php
  php/tests/test.sh
  php/tests/undefined_test.php
  tests.sh
Labels: cla: yes, release notes: no

#8570 Remove Python compatibility tests
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/factory_test1.proto
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/factory_test2.proto
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/more_extensions.proto
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/more_extensions_dynamic.proto
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/more_messages.proto
  python/compatibility_tests/v2.5.0/protos/python/google/protobuf/internal/test_bad_identifiers.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/descriptor.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest_custom_options.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest_import.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest_import_public.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest_mset.proto
  python/compatibility_tests/v2.5.0/protos/src/proto/google/protobuf/unittest_no_generic_services.proto
  python/compatibility_tests/v2.5.0/setup.py
  python/compatibility_tests/v2.5.0/test.sh
  python/compatibility_tests/v2.5.0/tests/__init__.py
  python/compatibility_tests/v2.5.0/tests/google/__init__.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/__init__.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/__init__.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/descriptor_test.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/generator_test.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/golden_message
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/golden_packed_fields_message
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/message_test.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/service_reflection_test.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/test_util.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/text_format_test.py
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/text_format_unittest_data.txt
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/text_format_unittest_extensions_data.txt
  python/compatibility_tests/v2.5.0/tests/google/protobuf/internal/wire_format_test.py
  tests.sh
Labels: cla: yes, release notes: no

#8556 Update protobuf version to 3.16.0-rc2
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8536 Update kokoro/docs/publish-python.sh
  kokoro/docs/publish-python.sh
Labels: cla: yes, documentation, python, release notes: no

#8563 fix(ruby): Fix various exceptions in Ruby on 64-bit Windows
  ruby/ext/google/protobuf_c/protobuf.c
Labels: cla: yes, release notes: yes, ruby

#8568 Fix constness issue detected by MSVC standard conforming mode
  python/google/protobuf/pyext/descriptor_pool.cc
Labels: cla: yes, python, release notes: yes

#8565 fix(ruby): Fix crash when calculating Message hash values on 64-bit Windows
  ruby/Gemfile
  ruby/ext/google/protobuf_c/message.c
Labels: cla: yes, release notes: yes, ruby

#8573 Update PHP release notes and update version to 3.16.0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8578 Comment out unused variable in repeated_field_unittest.cc
  src/google/protobuf/repeated_field_unittest.cc
Labels: cla: yes, release notes: no

#8575 Update protobuf version to 3.17.0-rc1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8581 Merge 3.16.x into master branch
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  update_version.py
Labels: cla: yes, release notes: no

#8583 Updated CHANGES.txt and PHP changelog for 3.17.0
  CHANGES.txt
  php/ext/google/protobuf/package.xml
Labels: cla: yes, release notes: no

#8582 Merge 3.17.x into master
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8579 Use template Delete<> for invoking a dependent template
  src/google/protobuf/map_entry_lite.h
Labels: c++, cla: yes, release notes: yes

#8585 Add the kotlin and kotlin-lite directories to the main pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/pom.xml
  kokoro/macos/prepare_build_macos_rc
Labels: cla: yes, release notes: no

#8587 Fix newly appeared -Wunused-parameter
  src/google/protobuf/arena.h
Labels: cla: yes, release notes: no

#8586 Update protobuf version to 3.17.0-rc2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
  update_version.py
Labels: cla: yes, release notes: no

#8601 Fix -Wunused-parameter in java_names.h
  src/google/protobuf/compiler/java/java_helpers.h
Labels: cla: yes, protoc, release notes: yes

#8576 Some more updates to PHP testing infrastructure
  kokoro/linux/php80/build.sh
  kokoro/linux/php80/continuous.cfg
  kokoro/linux/php80/presubmit.cfg
  kokoro/linux/php_all/build.sh
  kokoro/linux/test_php.sh
  kokoro/macos/prepare_build_macos_rc
  php/generate_test_protos.sh
  php/prepare_c_extension.sh
  php/tests/compile_extension.sh
Labels: cla: yes, release notes: no

#8609 Make the dist_install test use Java 8
  kokoro/linux/dist_install/build.sh
  kokoro/linux/dockerfile/test/java_stretch/Dockerfile
  tests.sh
Labels: cla: yes, release notes: no

#8606 Update protobuf version to 3.17.0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8600 Fix compile error on darwin GCC due to an unsupported attribute init_priority
  src/google/protobuf/port_def.inc
Labels: c++, cla: yes, kokoro:run, release notes: yes

#8571 Export SerializeInternalToArray
  src/google/protobuf/generated_message_table_driven.h
Labels: cla: yes, release notes: no

#8614 Fixed PHP memory leaks and arginfo errors
  Makefile.am
  kokoro/linux/php_all/build.sh
  kokoro/linux/test_php.sh
  php/REFCOUNTING.md
  php/composer.json
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/convert.c
  php/ext/google/protobuf/convert.h
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/def.h
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/wkt.inc
  php/tests/ArrayTest.php
  php/tests/EncodeDecodeTest.php
  php/tests/GeneratedClassTest.php
  php/tests/compile_extension.sh
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#8615 Use correct enum values.
  objectivec/Tests/GPBMessageTests+Runtime.m
  objectivec/Tests/GPBMessageTests+Serialization.m
Labels: cla: yes, objective-c, release notes: no

#8560 Update Objective-C ProtocolBuffers_iOS.xcodeproj To Skip Install
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
Labels: cla: yes, objective-c, release notes: no

#8597 Updating Kotlin compiler version and testing new functionality it allows
  java/kotlin-lite/pom.xml
  java/kotlin-lite/src/test/kotlin/com/google/protobuf/Proto2LiteTest.kt
  java/kotlin/pom.xml
  java/kotlin/src/test/kotlin/com/google/protobuf/Proto2Test.kt
Labels: cla: yes, kotlin, release notes: yes

#8472 [PHP] Fixed $msg->setMessage(null) to properly clear the message.
  php/ext/google/protobuf/message.c
  php/src/Google/Protobuf/Internal/Message.php
  php/src/Google/Protobuf/Internal/RepeatedField.php
  php/tests/ArrayTest.php
  php/tests/EncodeDecodeTest.php
  php/tests/GeneratedClassTest.php
Labels: cla: yes, php, release notes: yes

#8473 C#: Add ParseFrom/MergeFrom ReadOnlySpan<byte>
  csharp/src/Google.Protobuf.Test/CodedInputStreamTest.cs
  csharp/src/Google.Protobuf.Test/MessageParsingHelpers.cs
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/MessageExtensions.cs
  csharp/src/Google.Protobuf/MessageParser.cs
  csharp/src/Google.Protobuf/ParseContext.cs
Labels: c#, cla: yes, release notes: yes

#8613 Fix syntax errors in bswap_64
  src/google/protobuf/stubs/port.h
Labels: cla: yes, release notes: no

#8622 Revert "Merge branch 'kotlin' into master"
  java/kotlin/pom.xml
Labels: cla: yes, release notes: no

#6393 Add more description on unspecified directory in javascript readme (release notes: no)
  js/README.md
Labels: cla: yes, javascript, release notes: no

#5300 Build updates
  autogen.sh
  objectivec/README.md
  src/README.md
Labels: autotools, cla: yes, kokoro:force-run, release notes: no

#8623 Kotlin: update pom.xml to include dokka
  java/kotlin/pom.xml
Labels: cla: yes, release notes: no

#8621 Updated upb version and fixed PHP to not get unset message field.
  CHANGES.txt
  conformance/failure_list_php_c.txt
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
Labels: cla: yes, release notes: no

#8624 Updated version of upb for Ruby
  CHANGES.txt
  conformance/failure_list_ruby.txt
  ruby/Rakefile
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
Labels: cla: yes, release notes: no

#8616 Fix unportable test(1) operator
  configure.ac
Labels: cla: yes, release notes: no

#8626 Use cfg="exec" instead of cfg="host" in internal rules.
  protobuf.bzl
Labels: bazel, cla: yes, release notes: yes

#8632 Php & Ruby Cherry Picks for 3.17.1
  CHANGES.txt
  Makefile.am
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  kokoro/linux/php80/build.sh
  kokoro/linux/php80/continuous.cfg
  kokoro/linux/php80/presubmit.cfg
  kokoro/linux/php_all/build.sh
  php/REFCOUNTING.md
  php/composer.json
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/convert.c
  php/ext/google/protobuf/convert.h
  php/ext/google/protobuf/def.c
  php/ext/google/protobuf/def.h
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
  php/ext/google/protobuf/wkt.inc
  php/generate_test_protos.sh
  php/prepare_c_extension.sh
  php/tests/ArrayTest.php
  php/tests/EncodeDecodeTest.php
  php/tests/GeneratedClassTest.php
  php/tests/compile_extension.sh
  ruby/Rakefile
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#8633 Update protobuf version to 3.17.1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8634 Remove build badges, they were consistently out of date and not very useful.
  README.md
Labels: cla: yes, release notes: no

#8639 Fixed memory bug: properly root repeated/map field when assigning.
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/map.h
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/repeated_field.h
  ruby/tests/basic.rb
Labels: cla: yes, release notes: yes, ruby

#8638 Run PHP aarch64 tests on the CI (with an emulator)
  kokoro/linux/aarch64/php_build_and_run_tests_with_qemu_aarch64.sh
  kokoro/linux/aarch64/test_php_aarch64.sh
  kokoro/linux/aarch64/testimage_protobuf_php_arm64v8/Dockerfile
  kokoro/linux/php_aarch64/build.sh
  kokoro/linux/php_aarch64/continuous.cfg
  kokoro/linux/php_aarch64/presubmit.cfg
Labels: cla: yes, php, release notes: no

#8642 Fix MinGW compilation
  src/google/protobuf/stubs/port.h
Labels: cla: yes, release notes: no

#8649 Added missing release notes for 3.17.1.
  CHANGES.txt
  php/ext/google/protobuf/package.xml
Labels: cla: yes, release notes: no

#8653 Remove maven-bundle-plugin to fix duplicate class errors
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
Labels: cla: yes, kotlin, release notes: no

#8654 [Objective-C] Comment Correcting
  objectivec/GPBDescriptor.h
Labels: cla: yes, release notes: no

#8655 Use template Delete<> for invoking a dependent template
  src/google/protobuf/map_entry.h
Labels: c++, cla: yes, release notes: yes

#8658 Updating change logs for 3.17.2
  CHANGES.txt
  php/ext/google/protobuf/package.xml
Labels: cla: yes, release notes: no

#8661 Fix the Docker build for our javascript Docker image
  kokoro/linux/dockerfile/test/javascript/Dockerfile
Labels: cla: yes, release notes: no

#8662 Reserve 1109 for Glitchdot
  docs/options.md
Labels: release notes: no

#8663 Add internal.bzl to EXTRA_DIST.
  Makefile.am
Labels: bazel, cla: yes, release notes: yes

#8650 Merge 3.17.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/map.h
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/repeated_field.h
  ruby/google-protobuf.gemspec
  ruby/tests/basic.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8669 ObjC: Add stdin/stdout/stderr to reserved word list.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: yes

#8671 Scope `string` usage with the namespace.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: no

#8670 Fixed SEGV in sub-message getters for well-known types when message is unset.
  php/ext/google/protobuf/message.c
  php/src/Google/Protobuf/Api.php
  php/src/Google/Protobuf/Enum.php
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Option.php
  php/src/Google/Protobuf/Type.php
  php/tests/GeneratedClassTest.php
  php/tests/WellKnownTest.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: yes

#8673 Correct ordering of export API for DescriptorTable
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: c++, cla: yes, release notes: yes

#8665 Fix OSS benchmarking script
  kokoro/linux/benchmark/build.sh
  kokoro/linux/benchmark/run.sh
Labels: cla: yes, release notes: no
