Repository protocolbuffers/protobuf, pull requests merged in 2021-02, with the labels that each got.

#8220 Allow FileDescriptors to be parsed with extension registries
  csharp/src/Google.Protobuf.Test/ExtensionSetTest.cs
  csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs
  csharp/src/Google.Protobuf/ExtensionValue.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
Labels: c#, cla: yes, release notes: yes

#8219 Include the size of values (and tags) for extensions, even if the value is the default
  csharp/src/Google.Protobuf.Test/ExtensionSetTest.cs
  csharp/src/Google.Protobuf/ExtensionValue.cs
  csharp/src/Google.Protobuf/FieldCodec.cs
Labels: c#, cla: yes, release notes: yes

#8243 Fix problem when restoring C# dependencies on win2016
  kokoro/release/csharp/windows/build_nuget.bat
  kokoro/windows/csharp/build.bat
Labels: c#, cla: yes, release notes: no

#8246 Add cmake to the path to fix the build on kokoro
  kokoro/release/python/windows/build_single_artifact.bat
Labels: cla: yes, packaging & distribution, release notes: no

#8121 add python 3.9
  kokoro/linux/dockerfile/test/python39/Dockerfile
  kokoro/linux/python39/build.sh
  kokoro/linux/python39/continuous.cfg
  kokoro/linux/python39/presubmit.cfg
  kokoro/linux/python39_cpp/build.sh
  kokoro/linux/python39_cpp/continuous.cfg
  kokoro/linux/python39_cpp/presubmit.cfg
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/build_single_artifact.bat
  python/setup.py
  python/tox.ini
  tests.sh
Labels: cla: yes, python, release notes: no

#8248 Protect against stack overflow if the user derives from Message.
  php/ext/google/protobuf/message.c
  php/src/Google/Protobuf/Internal/Message.php
  php/tests/GeneratedClassTest.php
Labels: cla: yes, php, release notes: yes

#8252 Fixed clone_obj for PHP8.
  php/ext/google/protobuf/array.c
  php/ext/google/protobuf/map.c
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.h
Labels: cla: yes, php, release notes: no

#8253 Enhance explanation in kokoro/README.md.
  kokoro/README.md
Labels: cla: yes, cleanup, release notes: no, testing

#8250 Remove obsolete scripts for building python wheels
  Makefile.am
  python/release/wheel/Dockerfile
  python/release/wheel/README.md
  python/release/wheel/build_wheel_manylinux.sh
  python/release/wheel/protobuf_optimized_pip.sh
Labels: cla: yes, python, release notes: no

#8258 Updated upb to allow nonzero offset minutes in JSON timestamps.
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
Labels: cla: yes, php, release notes: yes, ruby

#8251 Add test for php5 for pure php implementation
  kokoro/linux/dockerfile/test/php/Dockerfile
  kokoro/linux/dockerfile/test/php_32bit/Dockerfile
  php/composer.json
  tests.sh
Labels: cla: yes, php, release notes: no

#8262 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/Android.java
  java/core/src/main/java/com/google/protobuf/RawMessageInfo.java
  java/lite/proguard.pgcfg
  js/binary/reader_test.js
  js/binary/writer_test.js
  js/commonjs/rewrite_tests_for_commonjs.js
  js/compatibility_tests/v3.1.0/binary/reader_test.js
  js/compatibility_tests/v3.1.0/binary/writer_test.js
  js/compatibility_tests/v3.1.0/maps_test.js
  js/compatibility_tests/v3.1.0/message_test.js
  js/maps_test.js
  js/message_test.js
  js/proto3_test.js
  php/src/Google/Protobuf/Internal/FileOptions.php
  src/google/protobuf/arena.h
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/cpp/cpp_file.cc
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/dynamic_message.cc
  src/google/protobuf/generated_message_table_driven_lite.h
  src/google/protobuf/message_lite.cc
  src/google/protobuf/message_lite.h
  src/google/protobuf/message_unittest.inc
  src/google/protobuf/metadata_lite.h
  src/google/protobuf/repeated_field.h
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/internal/json_stream_parser.cc
  src/google/protobuf/util/internal/json_stream_parser_test.cc
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/internal/protostream_objectsource_test.cc
  src/google/protobuf/util/internal/type_info_test_helper.cc
  src/google/protobuf/util/internal/type_info_test_helper.h
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/message_differencer.h
Labels: cla: yes, release notes: no

#8256 Reserve extension id for protoc-gen-psql & protoc-gen-sanitize
  docs/options.md
Labels: cla: yes, release notes: no

#8265 Update protobuf version to 3.15.0-rc1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8267 Updated CHANGES.txt for the 3.15.0 release
  CHANGES.txt
Labels: cla: yes, release notes: no

#8275 Added PHP changes for 3.15.0 into package.xml
  php/ext/google/protobuf/package.xml
Labels: cla: yes, release notes: no

#8281 Updated collect_all_artifacts.sh to avoid installing apt-transport-https
  kokoro/release/collect_all_artifacts.sh
Labels: cla: yes, release notes: no

#8282 Added to the changelog entries for Ruby & PHP.
  CHANGES.txt
Labels: cla: yes

#8276 Added more information to "file already loaded" warning.
  php/ext/google/protobuf/def.c
Labels: cla: yes, php, release notes: yes

#8270 Expand reserved IDs for protoc-gen-psql and protoc-gen-sanititize
  docs/options.md
Labels: cla: yes

#8209 deps: update to Guava 30.1
  java/pom.xml
Labels: cla: yes, java, release notes: no

#8190 Fix compiler warnings issue found in conformance_test_runner#8189
  conformance/binary_json_conformance_suite.cc
  conformance/conformance_test_runner.cc
Labels: c++, cla: yes, release notes: yes

#8288 Remove the (unused) Python all-versions Kokoro config.
  kokoro/linux/python/build.sh
  kokoro/linux/python/continuous.cfg
  kokoro/linux/python/presubmit.cfg
Labels: cla: yes, release notes: no

#8147 Add .NET 5 target and improve WriteString performance with SIMD
  csharp/install_dotnet_sdk.ps1
  csharp/src/Google.Protobuf.Benchmarks/Google.Protobuf.Benchmarks.csproj
  csharp/src/Google.Protobuf.Test/Buffers/ArrayBufferWriter.cs
  csharp/src/Google.Protobuf.Test/CodedOutputStreamTest.cs
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Test/JsonParserTest.cs
  csharp/src/Google.Protobuf.Test/JsonTokenizerTest.cs
  csharp/src/Google.Protobuf.Test/LegacyGeneratedCodeTest.cs
  csharp/src/Google.Protobuf.Test/MessageParsingHelpers.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/WritingPrimitives.cs
  global.json
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: c#, cla: yes, release notes: yes

#8302 Delete root-owned files in Kokoro builds
  kokoro/linux/cpp_distcheck/build.sh
  kokoro/release/python/linux/build_artifacts.sh
Labels: cla: yes, release notes: no

#8303 Updated collect_all_artifacts.sh for Ubuntu Xenial
  kokoro/release/collect_all_artifacts.sh
Labels: cla: yes, release notes: no

#8236 fix: README supported PHP version for C extension
  php/README.md
Labels: cla: yes

#7613 [PHP] Changed parameter type from long to integer
  php/src/Google/Protobuf/Internal/RepeatedField.php
Labels: cla: yes

#8305 Update protobuf version to 3.15.0-rc2
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8294 Some doc on AOT compilation and protobuf
  docs/jvm_aot.md
Labels: cla: yes

#8307 Update protobuf version to 3.15.0
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: cla: yes, release notes: no

#8313 [Ruby] Bugfix for Message.[] for repeated or map fields.
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/basic.rb
Labels: cla: yes, release notes: yes, ruby

#8320 [Ruby] Fix for truncating behavior when converting Float to Duration.
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#8318 Made some small fixes for MinGW and for C++20 with GCC
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/mutex.h
Labels: cla: yes, release notes: no

#8328 Move the class map to a CFDictionary.
  objectivec/GPBExtensionRegistry.m
Labels: cla: yes, objective-c, release notes: yes

#8329 Merge 3.15.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/message.c
  ruby/google-protobuf.gemspec
  ruby/tests/basic.rb
  ruby/tests/common_tests.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/mutex.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8330 [Ruby] Fix for FieldDescriptor.get(msg).
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/message.h
  ruby/tests/well_known_types_test.rb
Labels: cla: yes, release notes: yes, ruby

#8323 Fix PROTOBUF_CONSTINIT macro redefinition
  src/google/protobuf/port_def.inc
Labels: c++, cla: yes, release notes: yes

#8333 Cherry-picked #8323 into 3.15.x branch
  src/google/protobuf/port_def.inc
Labels: cla: yes, release notes: no

#8338 Merge 3.15.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/message.h
  ruby/google-protobuf.gemspec
  ruby/tests/well_known_types_test.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8341 Ruby <2.7now uses WeakMap too, which prevents memory leaks.
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
Labels: cla: yes, release notes: yes, ruby

#8345 Updated CHANGES.txt for 3.15.3 release
  CHANGES.txt
Labels: cla: yes, release notes: no

#8342 Updated protobuf version to 3.15.3
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8348 Merge 3.15.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no
