Repository protocolbuffers/protobuf, pull requests merged in 2021-12, with the labels that each got.

#9276 Fixing windows builds
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
Labels: cla: yes, bazel, release notes: no

#9277 Change include directories
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
Labels: cla: yes, bazel, release notes: no

#9278 Add comma
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9280 Add protoc-gen-go-svc to options.md
  docs/options.md
Labels: cla: yes, go, release notes: yes

#9273 Fix broken max macro on Windows
  src/google/protobuf/arena.h
  src/google/protobuf/stubs/stl_util.h
Labels: cla: yes, c++, windows, release notes: no, platform related

#9311 Dropped Ruby 2.3 and 2.4 support for CI and releases.
  kokoro/linux/dockerfile/test/ruby/Dockerfile
  kokoro/linux/ruby23/build.sh
  kokoro/linux/ruby23/continuous.cfg
  kokoro/linux/ruby23/presubmit.cfg
  kokoro/linux/ruby24/build.sh
  kokoro/linux/ruby24/continuous.cfg
  kokoro/linux/ruby24/presubmit.cfg
  kokoro/macos/ruby23/build.sh
  kokoro/macos/ruby23/continuous.cfg
  kokoro/macos/ruby23/presubmit.cfg
  kokoro/macos/ruby24/build.sh
  kokoro/macos/ruby24/continuous.cfg
  kokoro/macos/ruby24/presubmit.cfg
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Gemfile
  ruby/Rakefile
Labels: ruby, release notes: yes

#9309 show less log junk from Maven
  tests.sh
Labels: java, release notes: no

#9298 remove unused test proto
  Makefile.am
  java/core/generate-test-sources-build.xml
  java/core/src/test/proto/com/google/protobuf/message_lite_extension_util_test.proto
  java/lite/generate-test-sources-build.xml
Labels: java, java-lite, release notes: no

#9316 Add space to fix error message formatting.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: objective-c, release notes: no

#9317 Change windows cross compile includes
  toolchain/BUILD
Labels: bazel, release notes: no

#9318 Change toolchain includes
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
Labels: bazel, release notes: no

#9322 Update python 3.10 install MD5 Sum
  kokoro/release/python/windows/install_python_interpreters.ps1
Labels: release notes: no

#9323 Cherry-pick Python 3.10 fix to 3.19.x
  kokoro/release/python/windows/install_python_interpreters.ps1
Labels: release notes: no

#9320 Cherry-pick fix from #9311 into 3.18.x
  kokoro/linux/dockerfile/test/ruby/Dockerfile
  kokoro/linux/ruby23/build.sh
  kokoro/linux/ruby23/continuous.cfg
  kokoro/linux/ruby23/presubmit.cfg
  kokoro/linux/ruby24/build.sh
  kokoro/linux/ruby24/continuous.cfg
  kokoro/linux/ruby24/presubmit.cfg
  kokoro/macos/ruby23/build.sh
  kokoro/macos/ruby23/continuous.cfg
  kokoro/macos/ruby23/presubmit.cfg
  kokoro/macos/ruby24/build.sh
  kokoro/macos/ruby24/continuous.cfg
  kokoro/macos/ruby24/presubmit.cfg
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Gemfile
  ruby/Rakefile
Labels: ruby, release notes: no

#9336 Merge 3.18.x into 3.19.x
  kokoro/linux/dockerfile/test/ruby/Dockerfile
  kokoro/linux/ruby23/build.sh
  kokoro/linux/ruby23/continuous.cfg
  kokoro/linux/ruby23/presubmit.cfg
  kokoro/linux/ruby24/build.sh
  kokoro/linux/ruby24/continuous.cfg
  kokoro/linux/ruby24/presubmit.cfg
  kokoro/macos/prepare_build_macos_rc
  kokoro/macos/ruby23/build.sh
  kokoro/macos/ruby23/continuous.cfg
  kokoro/macos/ruby23/presubmit.cfg
  kokoro/macos/ruby24/build.sh
  kokoro/macos/ruby24/continuous.cfg
  kokoro/macos/ruby24/presubmit.cfg
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/Gemfile
  ruby/Rakefile
Labels: release notes: no
