Repository protocolbuffers/protobuf, pull requests merged in 2021-11, with the labels that each got.

#9170 Fix benchmark by making sure we use Python 3
  benchmarks/Makefile.am
  benchmarks/python/python_benchmark_messages.cc
  benchmarks/util/result_parser.py
  kokoro/linux/benchmark/run.sh
Labels: cla: yes, python, release notes: no

#9176 Cherry-pick benchmark fix from #9170 into 3.19.x
  benchmarks/Makefile.am
  benchmarks/python/python_benchmark_messages.cc
  benchmarks/util/result_parser.py
  kokoro/linux/benchmark/run.sh
Labels: cla: yes, release notes: no

#9177 Add pbkit to third_party.md
  docs/third_party.md
Labels: cla: yes, release notes: no

#9139 Implement unambiguous comparisons for RepeatedPtrIterator in C++20
  src/google/protobuf/repeated_ptr_field.h
Labels: cla: yes, c++, release notes: no

#9187 Use repo-relative labels wherever possible
  protobuf.bzl
  protobuf_deps.bzl
Labels: cla: yes, bazel, release notes: yes

#9188 Creates a protoc release zip
  BUILD
  Makefile.am
  WORKSPACE
  protobuf_deps.bzl
  protobuf_release.bzl
  toolchain/cc_toolchain_config.bzl
Labels: cla: yes, bazel, release notes: no

#9203 Update our build script to publish Mac aarch_64 binaries
  protoc-artifacts/build-zip.sh
Labels: cla: yes, protoc, release notes: no

#9195 Remove unnecessary dependency from @com_google_protobuf//:protobuf_java_util
  java/util/BUILD
Labels: cla: yes, java, bazel, release notes: no

#9210 Creating bazel toolchains to compile for macOS.
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
  toolchain/toolchains.bazelrc
Labels: cla: yes, bazel, release notes: no

#9201 [C++] Fix missing #ifdef for undefined identifiers
  src/google/protobuf/inlined_string_field.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
Labels: cla: yes, c++, release notes: no

#9208 Fix typo in docstring
  python/google/protobuf/descriptor.py
Labels: cla: yes, python, release notes: no

#9205 [C#] Update .NET SDKs to LTS versions
  Makefile.am
  appveyor.bat
  conformance/Makefile.am
  csharp/NuGet.Config
  csharp/buildall.sh
  csharp/compatibility_tests/v3.0.0/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/compatibility_tests/v3.0.0/test.sh
  csharp/install_dotnet_sdk.ps1
  csharp/src/AddressBook/AddressBook.csproj
  csharp/src/Google.Protobuf.Benchmarks/Program.cs
  csharp/src/Google.Protobuf.Conformance/Google.Protobuf.Conformance.csproj
  csharp/src/Google.Protobuf.JsonDump/Google.Protobuf.JsonDump.csproj
  csharp/src/Google.Protobuf.Test/Collections/RepeatedFieldTest.cs
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Test/JsonParserTest.cs
  csharp/src/Google.Protobuf.Test/JsonTokenizerTest.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/JsonTokenizer.cs
  global.json
  kokoro/linux/aarch64/test_csharp_aarch64.sh
  kokoro/linux/dockerfile/test/csharp/Dockerfile
Labels: cla: yes, c#, release notes: no

#9214 Changing cpp version back to 8
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9217 Update BUILD paths
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#8466 Fix .NET SourceLink and warnings in NuGet package
  csharp/build_packages.bat
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: cla: yes, c#, release notes: yes

#9222 Fix dotnet aarch64
  kokoro/linux/aarch64/test_csharp_aarch64.sh
Labels: cla: yes, c#, release notes: no

#9224 Update BUILD paths
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9226 Update BUILD
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9227 Update include directories
  toolchain/cc_toolchain_config.bzl
Labels: cla: yes, bazel, release notes: no

#9235 Change sysroot flags
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
Labels: cla: yes, bazel, release notes: no

#9233 Add a envvar to provide a prefix on all proto package prefixed symbols.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c, kokoro:run, kokoro:force-run, release notes: no

#9234 Support no_package:FILE in the expected prefixes file.
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, kokoro:run, kokoro:force-run, release notes: no

#9242 Update BUILD
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9243 Update BUILD
  toolchain/BUILD
Labels: cla: yes, bazel, release notes: no

#9244 Update toolchains.bazelrc
  toolchain/toolchains.bazelrc
Labels: cla: yes, bazel, release notes: no

#9250 Adding windows toolchains
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
  toolchain/toolchains.bazelrc
Labels: cla: yes, bazel, release notes: no

#9251 Remove unused includes from unit tests
  src/google/protobuf/compiler/csharp/csharp_generator_unittest.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers_unittest.cc
Labels: cla: yes, protoc, release notes: no

#9253 Use C++11 integer types and fully qualify std::string
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers_unittest.cc
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator_unittest.cc
  src/google/protobuf/stubs/common.h
Labels: release notes: no

#9252 Name protoc artifacts by their cpu and os
  BUILD
  protobuf_release.bzl
Labels: cla: yes, bazel, release notes: no

#9266 remove UTF8Utils class that hasn't been needed since Java 6
  Makefile.am
  java/core/src/test/java/com/google/protobuf/Utf8Test.java
  java/core/src/test/java/com/google/protobuf/Utf8Utils.java
Labels: cla: yes, java, release notes: no

#9267 No error throwing for unknown OS
  protobuf_release.bzl
Labels: cla: yes, bazel, release notes: no

#9182 [C#] Fix trim warnings
  Makefile.am
  csharp/src/Google.Protobuf.Test.TestProtos/Google.Protobuf.Test.TestProtos.csproj
  csharp/src/Google.Protobuf.Test/Google.Protobuf.Test.csproj
  csharp/src/Google.Protobuf.Test/JsonParserTest.cs
  csharp/src/Google.Protobuf/Compatibility/DynamicallyAccessedMemberTypes.cs
  csharp/src/Google.Protobuf/Compatibility/DynamicallyAccessedMembersAttribute.cs
  csharp/src/Google.Protobuf/Compatibility/RequiresUnreferencedCodeAttribute.cs
  csharp/src/Google.Protobuf/Compatibility/TypeExtensions.cs
  csharp/src/Google.Protobuf/Compatibility/UnconditionalSuppressMessageAttribute.cs
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/JsonFormatter.cs
  csharp/src/Google.Protobuf/Reflection/CustomOptions.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/GeneratedClrTypeInfo.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ReflectionUtil.cs
  csharp/src/Google.Protobuf/Reflection/SingleFieldAccessor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMaskPartial.cs
Labels: cla: yes, c#, release notes: yes

#9271 Small tweaks to C# unit tests
  src/google/protobuf/compiler/csharp/csharp_bootstrap_unittest.cc
  src/google/protobuf/compiler/csharp/csharp_generator_unittest.cc
Labels: cla: yes, protoc, release notes: no
