Repository protocolbuffers/protobuf, pull requests merged in 2021-07, with the labels that each got.

#8782 ObjC: Fix logic error in exception loading.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: no

#8787 fix: missing comma in PHP names.c and generator.cc
  php/ext/google/protobuf/names.c
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: no

#8788 field_presence.md: fix Go example
  docs/field_presence.md
Labels: cla: yes

#8800 Update rules_jvm_external to 4.1
  protobuf_deps.bzl
Labels: bazel, cla: yes, release notes: no

#8735 Fix #7047 Safely handle setlocale
  src/google/protobuf/stubs/stringprintf_unittest.cc
Labels: c++, cla: yes, release notes: yes

#8801 PHP: add new keywords to missing test
  php/tests/proto/test_reserved_enum_value_upper.proto
Labels: cla: yes, php, release notes: no

#8794 Remove deprecated version of SetTotalBytesLimit()
  src/google/protobuf/io/coded_stream.h
  src/google/protobuf/io/coded_stream_unittest.cc
Labels: c++, cla: yes, release notes: yes

#8805 Add some knobs tweak what is generated.
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
Labels: cla: yes, objective-c, release notes: no

#8806 Revert "Add option for eliding property metadata from messages"
  objectivec/DevTools/compile_testing_protos.sh
  objectivec/GPBMessage_PackagePrivate.h
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
Labels: cla: yes, objective-c, release notes: no

#8758 Support arena allocation of google::protobuf::AnyMetadata
  src/google/protobuf/any.cc
  src/google/protobuf/any.h
  src/google/protobuf/any.pb.h
  src/google/protobuf/any_lite.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: c++, cla: yes, release notes: yes

#8811 Remove JvmField annotations from Kotlin private properties (#8804)
  java/kotlin/src/main/kotlin/com/google/protobuf/ExtensionList.kt
  src/google/protobuf/compiler/java/java_message.cc
  src/google/protobuf/compiler/java/java_message_lite.cc
Labels: cla: yes, kotlin, release notes: no

#8813 updating caliper to latest maven version.
  benchmarks/java/pom.xml
Labels: cla: yes, java, release notes: no

#8823 Update the automake and Bazel configs to be consistent about field_ac…
  BUILD
  src/Makefile.am
Labels: cla: yes, release notes: no

#8834 Update protokt options link
  docs/options.md
Labels: cla: yes, documentation, release notes: no

#8832 Add syntax highlighting and fix Ruby and Python comment syntax
  docs/field_presence.md
Labels: cla: yes, documentation, release notes: no

#8821 Fix some -Wunused-parameter warnings in cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_helpers.h
Labels: cla: yes, release notes: no

#8827 Fix undefined symbol error around SharedCtor()
  src/google/protobuf/any.pb.cc
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.cc
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/duration.pb.cc
  src/google/protobuf/empty.pb.cc
  src/google/protobuf/field_mask.pb.cc
  src/google/protobuf/source_context.pb.cc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/timestamp.pb.cc
  src/google/protobuf/type.pb.cc
  src/google/protobuf/wrappers.pb.cc
Labels: c++, cla: yes, release notes: yes

#8751 Fix #8748 tests.exe link failure under mingw/mingw64
  src/google/protobuf/map_test.cc
Labels: c++, cla: yes, release notes: no
