Repository protocolbuffers/protobuf, pull requests merged in 2021-06, with the labels that each got.

#8678 fixed warning about missing pragma warning push
  src/google/protobuf/wire_format_lite.h
Labels: c++, cla: yes, release notes: yes

#8683 Some cpp style fixes.
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
Labels: cla: yes, objective-c, release notes: no

#8684 Tweak tests to allow common protos to evolve more.
  objectivec/Tests/GPBDescriptorTests.m
Labels: cla: yes, objective-c, release notes: no

#8610 Use modern JS tooling instead of Closure's deprecated Python scripts.
  js/README.md
  js/commonjs/export.js
  js/commonjs/export_asserts.js
  js/commonjs/export_testdeps.js
  js/compatibility_tests/v3.0.0/test.sh
  js/gulpfile.js
  js/package.json
Labels: cla: yes, javascript, release notes: yes

#8685 Adding dokka to main pom
  java/pom.xml
Labels: cla: yes, kotlin, release notes: no

#8686 Adding PHP fix to changes for 3.17.2
  CHANGES.txt
Labels: cla: yes, release notes: no

#8557 protoc maven artifacts: reuse osx-x86_64 for osx-aarch_64
  protoc-artifacts/pom.xml
Labels: cla: yes, java, release notes: no

#8689 Merge 3.17.x into master
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8521 deps: update to Guava 30.1.1
  java/pom.xml
Labels: cla: yes, java, release notes: no

#8666 OSS benchmarks: print benchmarks JSON results to build job log
  benchmarks/util/result_parser.py
  kokoro/linux/benchmark/run.sh
Labels: cla: yes, release notes: no

#8690 constinit not working as expected in Visual Studio 2019 Update 16.10
  src/google/protobuf/port_def.inc
Labels: c++, cla: yes, release notes: no

#8637 Fix QNX 7.0 support #8593
  src/google/protobuf/compiler/cpp/cpp_enum_field.cc
  src/google/protobuf/compiler/cpp/cpp_primitive_field.cc
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/io/coded_stream.h
  src/google/protobuf/stubs/mutex.h
  src/google/protobuf/stubs/platform_macros.h
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes, release notes: yes

#8139 Fix clang-cl build on Windows (#6503)
  cmake/CMakeLists.txt
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/protoc.cmake
Labels: cla: yes, cleanup, cmake, release notes: no, windows

#8698 Merge 3.17.x into master
  CHANGES.txt
  java/pom.xml
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/package.xml
  php/src/Google/Protobuf/Api.php
  php/src/Google/Protobuf/Enum.php
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/DescriptorProto/ExtensionRange.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumValueDescriptorProto.php
  php/src/Google/Protobuf/Internal/FieldDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/MethodDescriptorProto.php
  php/src/Google/Protobuf/Internal/OneofDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Option.php
  php/src/Google/Protobuf/Type.php
  php/tests/GeneratedClassTest.php
  php/tests/WellKnownTest.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, release notes: no

#8699 Fixing kotlin duplicate class error
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
Labels: cla: yes, release notes: no

#8700 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8701 Updating changelog
  CHANGES.txt
Labels: cla: yes, release notes: no

#8664 Fix warnings raised by clang 11
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/cpp/cpp_enum_field.h
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_message_field.h
  src/google/protobuf/compiler/cpp/cpp_primitive_field.h
  src/google/protobuf/compiler/cpp/cpp_string_field.h
  src/google/protobuf/compiler/cpp/cpp_unittest.inc
  src/google/protobuf/compiler/csharp/csharp_enum.cc
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_field_base.cc
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message.cc
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_reflection_class.cc
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc
  src/google/protobuf/compiler/csharp/csharp_source_generator_base.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
  src/google/protobuf/compiler/importer.cc
  src/google/protobuf/compiler/java/java_enum_field.h
  src/google/protobuf/compiler/java/java_extension.h
  src/google/protobuf/compiler/java/java_extension_lite.h
  src/google/protobuf/compiler/java/java_generator_factory.h
  src/google/protobuf/compiler/java/java_map_field.h
  src/google/protobuf/compiler/java/java_message_field.h
  src/google/protobuf/compiler/java/java_message_field_lite.h
  src/google/protobuf/compiler/java/java_message_lite.h
  src/google/protobuf/compiler/java/java_primitive_field.h
  src/google/protobuf/compiler/java/java_primitive_field_lite.h
  src/google/protobuf/compiler/java/java_service.h
  src/google/protobuf/compiler/java/java_string_field.h
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.h
  src/google/protobuf/compiler/objectivec/objectivec_field.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_map_field.h
  src/google/protobuf/compiler/objectivec/objectivec_message_field.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.h
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/compiler/plugin.cc
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/dynamic_message_unittest.cc
  src/google/protobuf/io/gzip_stream.h
  src/google/protobuf/io/printer.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/util/field_mask_util.cc
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/internal/expecting_objectwriter.h
Labels: c++, cla: yes, release notes: yes

#7526 [Java] Remove unnecessary allocation during String field emptiness checks
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  src/google/protobuf/compiler/java/java_string_field.cc
Labels: cla: yes, java, release notes: no

#8718 Fix -Wunused-parameter introduced in 3.17.3
  src/google/protobuf/arena.h
Labels: c++, cla: yes, release notes: no

#8709 Merge 3.17.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/arena.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8707 Make StringPiece constructible from std::string_view
  src/google/protobuf/stubs/stringpiece.h
Labels: c++, cla: yes, release notes: yes

#8714 Add missing capability attributes for LLVM 12
  src/google/protobuf/stubs/mutex.h
Labels: c++, cla: yes, release notes: yes

#8720 Disable the warning for adding duplicated symbol
  php/ext/google/protobuf/def.c
Labels: cla: yes, php, release notes: no

#8723 Fix errorprone conflict
  java/util/pom.xml
Labels: cla: yes, java, release notes: yes

#8729 Add basic KVO test.
  objectivec/Tests/GPBMessageTests.m
Labels: cla: yes, objective-c, release notes: no

#8730 Add override to C++ code generation for InternalGetTable
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: c++, cla: yes, release notes: no

#8742 cypher -> cipher for the codespell workflow.
  CHANGES.txt
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil_unittest.cc
Labels: cla: yes, release notes: no

#8743 Add "Sur" to the ignore list for "Big Sur".
  .github/workflows/codespell.yml
Labels: cla: yes, cleanup, release notes: no

#8744 Fix the `skip` entry so the workflow doesn't get flagged.
  .github/workflows/codespell.yml
Labels: cla: yes, release notes: no

#8740 [csharp] ByteString.CreateCodedInput should use ArraySegment offset and count
  csharp/src/Google.Protobuf.Test/ByteStringTest.cs
  csharp/src/Google.Protobuf/ByteString.cs
Labels: c#, cla: yes, release notes: yes

#8738 ObjC: Block deprecated warnings when testing on newer OS
  objectivec/Tests/GPBMessageTests.m
Labels: cla: yes, objective-c, release notes: no

#8746 Reintroduce setup.py changes from #8280 erased by piper import #8617
  python/setup.py
Labels: cla: yes, release notes: no

#8749 Removing deprecated TimeUtil class.
  java/util/src/main/java/com/google/protobuf/util/TimeUtil.java
  java/util/src/test/java/com/google/protobuf/util/TimeUtilTest.java
Labels: cla: yes, java, release notes: yes

#8750 Remove TimeUtil.java and TimeUtilTest.java from Makefile.am
  Makefile.am
Labels: cla: yes, release notes: no

#8753 avoid using Bazel latest.
  kokoro/linux/bazel/build.sh
Labels: cla: yes, release notes: no

#8756 Ensure testdata text always uses \n newlines.
  java/core/src/test/java/com/google/protobuf/TestUtil.java
Labels: cla: yes, java, release notes: no

#8757 Install python38/39 on windows
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/install_python_interpreters.ps1
Labels: cla: yes, python, release notes: no

#8739 ObjC: Add option to remove property metadata from message classes to reduce codegen
  objectivec/DevTools/compile_testing_protos.sh
  objectivec/GPBMessage_PackagePrivate.h
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_OSX.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/PerformanceTests.xcscheme
  objectivec/ProtocolBuffers_iOS.xcodeproj/xcshareddata/xcschemes/ProtocolBuffers.xcscheme
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.h
Labels: cla: yes, objective-c, release notes: yes

#8761 Fix for Windows Bazel CI
  java/core/src/test/java/com/google/protobuf/TestUtil.java
Labels: cla: yes, java, kokoro:run, release notes: no

#8760 [ObjC] Add support for using the proto package to prefix symbols.
  objectivec/README.md
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: cla: yes, objective-c, release notes: yes

#8763 Fix up objectivec sources to simplify import into Google.
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: no

#8762 Fix failing java7 linux test
  tests.sh
Labels: cla: yes, java, release notes: no

#8767 Detect Windows vs Non-Windows execution context in tests.
  java/core/src/test/java/com/google/protobuf/TestUtil.java
Labels: cla: yes, java, release notes: no

#8752 Create java_export targets
  BUILD
  Makefile.am
  WORKSPACE
  java/core/BUILD
  java/core/pom_template.xml
  java/lite/BUILD
  java/lite/pom_template.xml
  java/util/BUILD
  java/util/pom_template.xml
  protobuf_version.bzl
Labels: cla: yes, java, java-lite, release notes: no

#8771 Cherry-pick #8757 into 3.17.x
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/install_python_interpreters.ps1
Labels: cla: yes, release notes: no

#7935 Raise ParseError when JSON string is expected and not given
  python/google/protobuf/internal/json_format_test.py
  python/google/protobuf/internal/well_known_types.py
Labels: cla: yes, python, release notes: no

#8770 Adding protobuf_version.bzl to update_version.py
  update_version.py
Labels: cla: yes, release notes: no

#8741 Stop using std::iterator (deprecated in C++17).
  src/google/protobuf/reflection.h
  src/google/protobuf/repeated_field.h
Labels: c++, cla: yes, release notes: yes

#8772 Allocated eigr/protocol protobuf extensions
  docs/options.md
Labels: cla: yes, release notes: no

#8777 use our java tests target instead of recursive walk
  kokoro/linux/bazel/build.sh
Labels: bazel, cla: yes, release notes: no

#8776 creating a single target to rollup maven artifacts
  java/BUILD
  java/core/BUILD
  java/util/BUILD
Labels: bazel, cla: yes, release notes: no

#8775 Move field_access_listener from libprotobuf-lite to libprotobuf
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
Labels: c++, cla: yes, release notes: yes

#7268 PHP: Adds "finally", "fn", "match", and "yield" to reserved names
  php/ext/google/protobuf/names.c
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/tests/GeneratedClassTest.php
  php/tests/proto/test_reserved_enum_lower.proto
  php/tests/proto/test_reserved_enum_upper.proto
  php/tests/proto/test_reserved_enum_value_lower.proto
  php/tests/proto/test_reserved_message_lower.proto
  php/tests/proto/test_reserved_message_upper.proto
  src/google/protobuf/compiler/php/php_generator.cc
Labels: cla: yes, php, release notes: no

#8778 Allow suppression of objc prefix checks.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: cla: yes, objective-c, release notes: no
