Repository protocolbuffers/protobuf, pull requests merged in 2021-04, with the labels that each got.

#8442 Changing codespell and mergeable ymls
  .github/mergeable.yml
  .github/workflows/codespell.yml
Labels: cla: yes, release notes: no

#8434 Fixed message equality in cases where the message type is different.
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/common_tests.rb
Labels: cla: yes, kokoro:run, release notes: yes, ruby

#8444 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  csharp/src/Google.Protobuf.Test/testprotos.pb
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  java/core/src/main/java/com/google/protobuf/CodedInputStream.java
  java/core/src/test/java/com/google/protobuf/CodedInputStreamTest.java
  php/src/Google/Protobuf/Internal/FileOptions.php
  src/google/protobuf/descriptor.proto
  src/google/protobuf/port_undef.inc
  src/google/protobuf/util/field_comparator.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/message_differencer.h
Labels: c#, c++, cla: yes, java, php, release_notes: no

#8446 Revert "[C++] Refactor uint128 (#8416)"
  src/google/protobuf/stubs/int128.cc
  src/google/protobuf/stubs/int128.h
  src/google/protobuf/stubs/int128_unittest.cc
  src/google/protobuf/stubs/logging.h
Labels: cla: yes, release notes: no

#8447 Merge 3.15.x into the master branch
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/google-protobuf.gemspec
  ruby/tests/common_tests.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8392 Emulated python aarch64 tests
  .github/workflows/codespell.yml
  kokoro/linux/aarch64/dockcross_helpers/run_dockcross_manylinux2014_aarch64.sh
  kokoro/linux/aarch64/python_crosscompile_aarch64.sh
  kokoro/linux/aarch64/python_run_tests_with_qemu_aarch64.sh
  kokoro/linux/aarch64/test_python_aarch64.sh
Labels: cla: yes, python, release notes: no

#8443 addressbook.proto: Enable java_multiple_files option
  examples/AddPerson.java
  examples/ListPeople.java
  examples/addressbook.proto
Labels: cla: yes, release notes: no

#8456 Updated CHANGES.txt for 3.16.0
  .github/workflows/codespell.yml
  CHANGES.txt
Labels: cla: yes, release notes: no

#8448 Update protobuf version to 3.16.0-rc1
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8461 Fixed memory leak of Ruby arena objects.
  ruby/ext/google/protobuf_c/protobuf.c
Labels: cla: yes, release notes: yes, ruby

#8327 [python-runtime] Add MethodDescriptor.CopyToProto()
  python/google/protobuf/descriptor.py
  python/google/protobuf/internal/descriptor_test.py
Labels: cla: yes, python, release notes: yes

#8463 Updated version to 3.15.8
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8465 Cherry-pick #8461 to the 3.16.x branch
  ruby/ext/google/protobuf_c/protobuf.c
Labels: cla: yes, release notes: no

#8467 [documentation] [java] Fixed version for gradle in java Readme.md
  java/README.md
Labels: cla: yes, java, release notes: no

#8469 Use a newer version of rules_proto, with the new rule `proto_descriptor_set`
  protobuf_deps.bzl
Labels: bazel, cla: yes, release notes: yes

#8471 Fix source gem compilation
  ruby/Rakefile
  ruby/ext/google/protobuf_c/extconf.rb
Labels: cla: yes, release notes: yes, ruby

#8496 #8492 constexpr defaulted default constructor of WrappedMutex
  src/google/protobuf/stubs/mutex.h
Labels: c++, cla: yes, release notes: no

#8482 Add intelliJ protobuf plugin and sisyphus
  docs/third_party.md
Labels: cla: yes, release notes: no

#8490 Use C++11 enum class for Utf8CheckMode
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
Labels: cla: yes, release notes: no

#8497 Undef DELETE macro on Windows
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
Labels: cla: yes, release notes: no

#8502 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  conformance/binary_json_conformance_suite.cc
  conformance/failure_list_csharp.txt
  conformance/failure_list_php.txt
  conformance/failure_list_php_c.txt
  conformance/failure_list_ruby.txt
  python/google/protobuf/json_format.py
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
Labels: cla: yes, release notes: no

#8505 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  conformance/failure_list_java_lite.txt
  conformance/text_format_failure_list_java_lite.txt
  src/google/protobuf/map_test.cc
  src/google/protobuf/message.h
  src/google/protobuf/message_unittest.inc
  src/google/protobuf/unittest.proto
  src/google/protobuf/wire_format_unittest.cc
Labels: cla: yes, release notes: no

#8500 Fix -Wunused-parameter in map<string, int> fields (fixes #8494)
  src/google/protobuf/compiler/cpp/cpp_map_field.cc
Labels: c++, cla: yes, release notes: yes

#8503 Use byteswap.h when building against musl libc
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes, release notes: yes

#8511 Update third_party.md
  docs/third_party.md
Labels: cla: yes, release notes: no

#8513 Remove unused python_protobuf.{cc,h}
  Makefile.am
  python/google/protobuf/internal/python_protobuf.cc
  python/google/protobuf/python_protobuf.h
Labels: cla: yes, python, release notes: yes

#8486 Make Go example work out of the box
  examples/Makefile
  examples/addressbook.proto
Labels: cla: yes, release notes: no

#8517 Fix some -Wunused parameter issues
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/compiler/importer.h
  src/google/protobuf/io/printer.h
  src/google/protobuf/io/tokenizer.h
Labels: cla: yes, release notes: no

#8356 Ruby: Add support for proto3 json_name in compiler and field definitions
  ruby/ext/google/protobuf_c/defs.c
  ruby/tests/encode_decode_test.rb
  ruby/tests/generated_code.proto
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes, release notes: yes, ruby

#8506 Bazel powered Java testing
  BUILD
  WORKSPACE
  conformance/conformance_test_runner.sh
  internal.bzl
  java/BUILD
  java/core/BUILD
  java/internal/BUILD
  java/internal/testing.bzl
  java/lite/BUILD
  java/lite/pom.xml
  java/util/BUILD
  protobuf.bzl
  protobuf_deps.bzl
Labels: bazel, cla: yes, java, java-lite, release notes: no

#8518 Cherry-pick #8356 into 3.16.x
  ruby/ext/google/protobuf_c/defs.c
  ruby/tests/encode_decode_test.rb
  ruby/tests/generated_code.proto
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: cla: yes, release notes: no

#8509 Fix protobuf version in the example
  examples/CMakeLists.txt
Labels: cla: yes, cmake, release notes: no

#8516 Fix some -Wsign-compare issues
  src/google/protobuf/compiler/cpp/cpp_helpers.h
Labels: cla: yes, release notes: no

#8523 ensure maven deps are pinned for reproducibility.
  WORKSPACE
  maven_install.json
Labels: bazel, cla: yes, release notes: no

#8522 add missing files to Makefile.am for java bazel
  Makefile.am
Labels: autotools, cla: yes, release notes: no

#8524 updating GSON and Guava to more recent versions
  WORKSPACE
  maven_install.json
Labels: cla: yes, java, java-lite, release notes: yes

#8526 rely on only HTTPS mirrors for maven.
  WORKSPACE
  maven_install.json
Labels: bazel, cla: yes, release notes: no

#8479 Run python aarch64 tests on the CI
  kokoro/linux/aarch64/dockcross_helpers/run_dockcross_manylinux2014_aarch64.sh
  kokoro/linux/aarch64/python_crosscompile_aarch64.sh
  kokoro/linux/aarch64/qemu_helpers/prepare_qemu.sh
  kokoro/linux/aarch64/test_python_aarch64.sh
  kokoro/linux/python_aarch64/build.sh
  kokoro/linux/python_aarch64/continuous.cfg
  kokoro/linux/python_aarch64/presubmit.cfg
Labels: cla: yes, python, release notes: no

#8346 Make libprotobuf symbols local on OSX
  python/setup.py
Labels: cla: yes, python, release notes: no

#8501 Run csharp aarch64 tests on the CI (with an emulator)
  kokoro/linux/aarch64/test_csharp_aarch64.sh
  kokoro/linux/csharp_aarch64/build.sh
  kokoro/linux/csharp_aarch64/continuous.cfg
  kokoro/linux/csharp_aarch64/presubmit.cfg
Labels: c#, cla: yes, release notes: no

#8485 Run java aarch64 tests on the CI (with an emulator)
  kokoro/linux/aarch64/protoc_crosscompile_aarch64.sh
  kokoro/linux/aarch64/test_java_aarch64.sh
  kokoro/linux/java_aarch64/build.sh
  kokoro/linux/java_aarch64/continuous.cfg
  kokoro/linux/java_aarch64/presubmit.cfg
Labels: cla: yes, java, release notes: no

#8534 Fix C# aarch64 tests (fix typo in test_csharp_aarch64.sh)
  kokoro/linux/aarch64/test_csharp_aarch64.sh
Labels: cla: yes, release notes: no

#8530 Start publishing python aarch64 manylinux wheels normally
  kokoro/release/python/linux/build_artifacts.sh
Labels: cla: yes, python, release notes: yes

#8532 Fix -Wundefined-inline error when using SharedCtor() or SharedDtor()
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: c++, cla: yes, release notes: yes

#8391 run basic C++ aarch64 tests under qemu emulator
  kokoro/linux/aarch64/cpp_crosscompile_and_run_tests_with_qemu_aarch64.sh
  kokoro/linux/aarch64/dockcross_helpers/run_dockcross_linux_aarch64.sh
  kokoro/linux/aarch64/test_cpp_aarch64.sh
  kokoro/linux/cpp_aarch64/build.sh
  kokoro/linux/cpp_aarch64/continuous.cfg
  kokoro/linux/cpp_aarch64/presubmit.cfg
Labels: c++, cla: yes, release notes: no

#8544 Test javascript on linux aarch64 (under qemu emulator)
  kokoro/linux/aarch64/javascript_build_and_run_tests_with_qemu_aarch64.sh
  kokoro/linux/aarch64/test_javascript_aarch64.sh
  kokoro/linux/javascript_aarch64/build.sh
  kokoro/linux/javascript_aarch64/continuous.cfg
  kokoro/linux/javascript_aarch64/presubmit.cfg
Labels: cla: yes, javascript, release notes: no
