Repository protocolbuffers/protobuf, pull requests merged in 2021-08, with the labels that each got.

#8844 remove various broken build status tags
  js/README.md
  objectivec/README.md
  python/README.md
  src/README.md
Labels: cla: yes, cleanup, release notes: no

#8850 Move DSL implementation from C to pure Ruby
  .gitignore
  Makefile.am
  ruby/Rakefile
  ruby/ext/google/protobuf_c/defs.c
  ruby/lib/google/protobuf.rb
  ruby/lib/google/protobuf/descriptor_dsl.rb
  ruby/travis-test.sh
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  tests.sh
Labels: cla: yes, release notes: yes, ruby

#8835 Fix default value of enum(int) in json_util with proto2
  src/google/protobuf/util/internal/default_value_objectwriter.cc
  src/google/protobuf/util/json_format.proto
  src/google/protobuf/util/json_util_test.cc
Labels: c++, cla: yes, release notes: yes

#8854 Migrate PHP & Ruby to ABSL wyhash
  Makefile.am
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  php/generate_test_protos.sh
  php/prepare_c_extension.sh
  php/tests/compile_extension.sh
  ruby/Rakefile
  ruby/ext/google/protobuf_c/convert.c
  ruby/ext/google/protobuf_c/extconf.rb
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
  ruby/lib/google/protobuf/descriptor_dsl.rb
  third_party/wyhash/LICENSE
  third_party/wyhash/wyhash.h
Labels: cla: yes, php, release notes: yes, ruby

#8859 Disallow missing field initializers
  BUILD
  src/google/protobuf/arena_impl.h
  src/google/protobuf/compiler/cpp/cpp_helpers.cc
  src/google/protobuf/compiler/cpp/cpp_helpers.h
  src/google/protobuf/io/tokenizer_unittest.cc
Labels: cla: yes, release notes: no

#8847 bazel: make `*.bzl` files publicly visible targets
  BUILD
Labels: cla: yes, bazel, release notes: no

#8878 Add SECURITY.md
  SECURITY.md
Labels: cla: yes, release notes: no

#8874 Remove .bazelrc file containing the -std=c++11 flag
  .bazelrc
Labels: cla: yes, release notes: no

#8879 Fix recursive symlink error
  .bazelignore
  php/generate_test_protos.sh
Labels: cla: yes, bazel, release notes: no

#8887 Update protobuf version
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8888 Update change log
  CHANGES.txt
Labels: cla: yes, release notes: no

#8892 Exclude reflection_tester from release
  Protobuf-C++.podspec
Labels: cla: yes, release notes: no

#8891 No need to test python2.7
  python/release.sh
Labels: cla: yes, python, release notes: no

#8901 Added release notes indicating that 3.17.3 is the last Python 2.x release.
  CHANGES.txt
Labels: cla: yes, release notes: no

#8851 cmake: support `MSVC_RUNTIME_LIBRARY` property
  cmake/CMakeLists.txt
Labels: cla: yes, c++, release notes: yes

#7855 Standardize NPE checks on JDK Objects utility
  java/core/src/main/java/com/google/protobuf/AbstractMessageLite.java
  java/core/src/main/java/com/google/protobuf/AllocatedBuffer.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryWriter.java
  java/core/src/main/java/com/google/protobuf/BooleanArrayList.java
  java/core/src/main/java/com/google/protobuf/ByteString.java
  java/core/src/main/java/com/google/protobuf/CodedInputStream.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/CodedOutputStream.java
  java/core/src/main/java/com/google/protobuf/CodedOutputStreamWriter.java
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  java/core/src/main/java/com/google/protobuf/DoubleArrayList.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/FieldInfo.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/FloatArrayList.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/IntArrayList.java
  java/core/src/main/java/com/google/protobuf/Internal.java
  java/core/src/main/java/com/google/protobuf/LazyFieldLite.java
  java/core/src/main/java/com/google/protobuf/LongArrayList.java
  java/core/src/main/java/com/google/protobuf/ManifestSchemaFactory.java
  java/core/src/main/java/com/google/protobuf/MapField.java
  java/core/src/main/java/com/google/protobuf/MapFieldLite.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/NioByteString.java
  java/core/src/main/java/com/google/protobuf/Protobuf.java
  java/core/src/main/java/com/google/protobuf/RepeatedFieldBuilder.java
  java/core/src/main/java/com/google/protobuf/RepeatedFieldBuilderV3.java
  java/core/src/main/java/com/google/protobuf/RopeByteString.java
  java/core/src/main/java/com/google/protobuf/SingleFieldBuilder.java
  java/core/src/main/java/com/google/protobuf/SingleFieldBuilderV3.java
  java/core/src/main/java/com/google/protobuf/StructuralMessageInfo.java
Labels: cla: yes, cleanup, release notes: no

#8917 Use if constexpr in template functions
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/stringprintf.cc
Labels: cla: yes, c++, cleanup, release notes: no, platform related

#8932 Fix cast truncates constant value warning
  src/google/protobuf/io/tokenizer.cc
Labels: cla: yes, c++, release notes: no

#8931 Fix uninitialized variable warnings in descriptor.cc
  src/google/protobuf/descriptor.cc
Labels: cla: yes, c++, release notes: no

#8908 add Stack Overflow as a possible support channel.
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes, documentation, release notes: no

#8922 Update change log
  CHANGES.txt
Labels: cla: yes, integration, release notes: no

#8936 Added missing "options" parameter.
  ruby/lib/google/protobuf/descriptor_dsl.rb
  ruby/tests/basic_test.proto
Labels: cla: yes, ruby, release notes: no

#8939 Addresses duplicates identified in #8925
  java/core/BUILD
  java/util/BUILD
Labels: cla: yes, java, bazel, java-lite, release notes: no

#8941 Addresses duplicates identified in #8925 (#8939)
  java/core/BUILD
  java/util/BUILD
Labels: cla: yes, java, release notes: no
