Repository protocolbuffers/protobuf, pull requests merged in 2021-03, with the labels that each got.

#8353 [C++] Delete StringPiecePod
  src/google/protobuf/stubs/stringpiece.h
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/util/internal/datapiece.h
Labels: c++, cla: yes, release notes: yes

#8309 Fix gcc error: comparison of unsigned expression in '>= 0' is always …
  src/google/protobuf/parse_context.h
Labels: c++, cla: yes, release notes: yes

#8347 Create a CMake option to control whether or not RTTI is enabled
  cmake/CMakeLists.txt
Labels: c++, cla: yes, release notes: yes

#8351 Fix endian.h location on FreeBSD
  src/google/protobuf/io/coded_stream.h
  src/google/protobuf/stubs/port.h
Labels: c++, cla: yes, release notes: yes

#8352 [bazel] Flip --incompatible_use_com_google_googletest
  BUILD
Labels: bazel, cla: yes, release notes: yes

#8361 Create a CMake option to control whether or not RTTI is enabled
  cmake/CMakeLists.txt
Labels: c++, cla: yes, release notes: yes

#8364 [Ruby] Fixed quadratic memory usage when appending to arrays.
  ruby/ext/google/protobuf_c/ruby-upb.c
Labels: cla: yes, release notes: yes, ruby

#8363 Fixed SEGV when users pass nil messages. This also disallows `nil` in RepeatedField or Map.
  ruby/compatibility_tests/v3.0.0/tests/repeated_field_test.rb
  ruby/ext/google/protobuf_c/message.c
  ruby/tests/basic.rb
  ruby/tests/repeated_field_test.rb
Labels: cla: yes, release notes: yes, ruby

#8362 read_property() handler is not supposed to return NULL
  php/ext/google/protobuf/message.c
Labels: cla: yes, php, release notes: yes

#8368 Cherry-picked #8362 into 3.15.x
  php/ext/google/protobuf/message.c
Labels: cla: yes, release notes: no

#8369 Revert "[bazel] Flip --incompatible_use_com_google_googletest"
  BUILD
Labels: bazel, cla: yes, release notes: yes

#8370 Merge 3.15.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/compatibility_tests/v3.0.0/tests/repeated_field_test.rb
  ruby/ext/google/protobuf_c/message.c
  ruby/google-protobuf.gemspec
  ruby/tests/basic.rb
  ruby/tests/repeated_field_test.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8357 docs: update version
  java/README.md
Labels: cla: yes, release notes: no

#8379 Fixed quadratic memory use in array append for PHP and Ruby.
  php/ext/google/protobuf/php-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.c
Labels: cla: yes, php, release notes: yes, ruby

#8377 Do not disable RTTI by default in the CMake build
  cmake/CMakeLists.txt
Labels: c++, cla: yes, release notes: yes

#8339 Switch on "new" buffer API
  python/google/protobuf/internal/message_test.py
  python/google/protobuf/internal/python_message.py
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/message.cc
  python/tox.ini
Labels: cla: yes, python, release notes: yes

#8383 Merge 3.15.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  cmake/CMakeLists.txt
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8386 [Ruby] Fixed bug in string comparison logic.
  ruby/ext/google/protobuf_c/convert.c
  ruby/tests/common_tests.rb
Labels: cla: yes, release notes: yes, ruby

#8390 Fix typo in docs/implementing_proto3_presence.md
  docs/implementing_proto3_presence.md
Labels: cla: yes, release notes: no

#8388 docs: register Coach Client Connect extension number (1107)
  docs/options.md
Labels: cla: yes, release notes: no

#8394 Remove link to unmaintained TypeScript library
  docs/third_party.md
Labels: cla: yes, release notes: no

#8387 Correcting arch classifier for s390x
  kokoro/release/protoc/linux/build.sh
  protoc-artifacts/README.md
  protoc-artifacts/build-protoc.sh
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
Labels: cla: yes, release notes: no

#8397 Allocate extension 1108 to Kratos API Errors
  docs/options.md
Labels: cla: yes, release notes: no

#6073 Register mark objects so Protobuf is compaction friendly
  ruby/ext/google/protobuf_c/protobuf.c
Labels: cla: yes, release notes: no, ruby

#8396 [bazel] Remove deprecated way to depend on googletest
  BUILD
  WORKSPACE
Labels: bazel, cla: yes, release notes: yes

#8354 [C++] Refactor util::Status
  conformance/conformance_cpp.cc
  src/google/protobuf/stubs/logging.h
  src/google/protobuf/stubs/status.cc
  src/google/protobuf/stubs/status.h
  src/google/protobuf/stubs/status_test.cc
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/util/internal/datapiece.cc
  src/google/protobuf/util/internal/json_stream_parser_test.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
Labels: c++, cla: yes, release notes: yes

#8287 Add autotools to release notes languages.
  .github/mergeable.yml
Labels: cla: yes, release notes: no

#8285 Fix missing -llog when compiling for android
  configure.ac
  src/Makefile.am
Labels: android, autotools, cla: yes, release notes: no

#8374 [CMake] Abilty to pass options to protoc executable from cmake
  cmake/protobuf-config.cmake.in
Labels: cla: yes, protoc, release notes: yes

#8319 deps: update JUnit and Truth
  java/pom.xml
Labels: cla: yes, java, release notes: yes

#8405 Make util::Status more similar to absl::Status
  src/google/protobuf/stubs/status.cc
  src/google/protobuf/stubs/status.h
  src/google/protobuf/stubs/status_test.cc
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/stubs/statusor_test.cc
  src/google/protobuf/util/internal/datapiece.cc
  src/google/protobuf/util/internal/field_mask_utility.cc
  src/google/protobuf/util/internal/json_stream_parser.cc
  src/google/protobuf/util/internal/json_stream_parser.h
  src/google/protobuf/util/internal/json_stream_parser_test.cc
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/internal/protostream_objectsource_test.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/json_util_test.cc
  src/google/protobuf/util/type_resolver_util.cc
Labels: c++, cla: yes, release notes: yes

#7744 [bazel] Add BUILD files for benchmark protos
  WORKSPACE
  benchmarks/BUILD
  benchmarks/cpp/BUILD
  benchmarks/datasets/BUILD
  benchmarks/datasets/google_message1/proto2/BUILD
  benchmarks/datasets/google_message1/proto3/BUILD
  benchmarks/datasets/google_message2/BUILD
  benchmarks/datasets/google_message3/BUILD
  benchmarks/datasets/google_message4/BUILD
Labels: cla: yes, release notes: no

#8407 Add protobuf for Ada
  docs/third_party.md
Labels: cla: yes, release notes: no

#8402 Merge 3.15.x into master branch
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/bom/pom.xml
  java/core/pom.xml
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/ext/google/protobuf_c/convert.c
  ruby/google-protobuf.gemspec
  ruby/tests/common_tests.rb
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: cla: yes, release notes: no

#8408 Fix -Wsuggest-destructor-override for generated C++ proto classes.
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/cpp/cpp_message.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: c++, cla: yes, release notes: yes

#8409 add error returns missing from protoc to prevent it from exiting with…
  src/google/protobuf/compiler/command_line_interface.cc
Labels: cla: yes, protoc, release notes: yes

#8406 [C++] Refactor StatusOr and StringPiece
  src/google/protobuf/stubs/bytestream.cc
  src/google/protobuf/stubs/casts.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/stubs/logging.h
  src/google/protobuf/stubs/macros.h
  src/google/protobuf/stubs/status_macros.h
  src/google/protobuf/stubs/statusor.cc
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/stubs/statusor_test.cc
  src/google/protobuf/stubs/stringpiece.cc
  src/google/protobuf/stubs/stringpiece.h
  src/google/protobuf/stubs/stringpiece_unittest.cc
  src/google/protobuf/stubs/stringprintf.cc
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/util/internal/object_writer.cc
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
Labels: c++, cla: yes, release notes: yes

#8423 Remove the ::pb namespace (alias).
  src/google/protobuf/port.h
Labels: c++, cla: yes, release notes: yes

#8426 Added UnsafeByteOperations to protobuf-lite
  java/core/BUILD
  java/lite/pom.xml
Labels: cla: yes, java-lite, release notes: yes

#8429 Fix unbounded memory growth for Ruby <2.7.
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
Labels: cla: yes, release notes: yes, ruby

#8280 Enable crosscompiling aarch64 python wheels under dockcross manylinux docker image
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/linux/config.sh
  python/setup.py
Labels: cla: yes, python, release notes: yes

#8437 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/CodedInputStream.java
  java/core/src/test/java/com/google/protobuf/CodedInputStreamTest.java
  java/util/src/main/java/com/google/protobuf/util/Durations.java
  python/google/protobuf/pyext/descriptor.cc
  python/google/protobuf/pyext/descriptor_pool.cc
  python/google/protobuf/pyext/map_container.cc
  python/google/protobuf/pyext/message.cc
  python/google/protobuf/pyext/message_factory.cc
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/port.h
  src/google/protobuf/stubs/status.cc
  src/google/protobuf/stubs/status.h
  src/google/protobuf/stubs/status_test.cc
  src/google/protobuf/stubs/statusor.h
  src/google/protobuf/stubs/statusor_test.cc
  src/google/protobuf/util/field_comparator.h
  src/google/protobuf/util/internal/datapiece.cc
  src/google/protobuf/util/internal/field_mask_utility.cc
  src/google/protobuf/util/internal/json_stream_parser.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
  src/google/protobuf/util/json_util.cc
  src/google/protobuf/util/type_resolver_util.cc
Labels: cla: yes, release notes: no

#8439 Add 'java/lite/target' to .gitignore
  .gitignore
Labels: cla: yes, java, release notes: no

#8440 Fix maven URL in protoc-artifacts/README.md
  protoc-artifacts/README.md
Labels: cla: yes, release notes: no
