Repository protocolbuffers/protobuf, pull requests merged in 2022-11, with the labels that each got.

#10816 Update cc_dist_library() to include transitive sources
  pkg/BUILD.bazel
  pkg/cc_dist_library.bzl
  src/file_lists.cmake
Labels: c++, release notes: no

#10910 Update CMake file generation to avoid including Bazel-specific WKT paths
  pkg/build_systems.bzl
  src/file_lists.cmake
Labels: release notes: no

#10850 Create CODEOWNERS
  .github/CODEOWNERS
Labels: tooling, kokoro:run, release notes: no

#11039 Update third_party.md
  docs/third_party.md
Labels: release notes: no

#11068 Add public modifiers to kotlin code
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/map_field_lite.cc
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/message_field_lite.cc
  src/google/protobuf/compiler/java/message_lite.cc
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/primitive_field_lite.cc
  src/google/protobuf/compiler/java/string_field.cc
  src/google/protobuf/compiler/java/string_field_lite.cc
Labels: release notes: yes, kotlin

#11077 Pre-emptively suppress target framework EOL warnings
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, release notes: no

#11083 Disable CocoaPods watchOS validation
  .github/workflows/objc_cocoapods.yml
Labels: mac, release notes: no
