Repository protocolbuffers/protobuf, pull requests merged in 2022-05, with the labels that each got.

#9896 Remove cuda.list from apt sources
  kokoro/release/collect_all_artifacts.sh
Labels: release notes: no

#9898 Remove cuda.list from apt sources (#9896)
  kokoro/release/collect_all_artifacts.sh
Labels: release notes: no

#9899 Remove cuda.list from apt sources (#9896)
  kokoro/release/collect_all_artifacts.sh
Labels: release notes: no

#9900 Update protobuf_version.bzl to separate protoc and per-language java …
  java/core/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
  java/util/BUILD.bazel
  protobuf_release.bzl
  protobuf_version.bzl
Labels: java, bazel, release notes: yes

#9906 Remove cuda.list from apt sources (#9896)
  kokoro/release/collect_all_artifacts.sh
Labels: release notes: no

#9907 Integrate from Piper for C++, Java, and Python
  src/google/protobuf/parse_context.h
  src/google/protobuf/wire_format_lite.h
Labels: release notes: no

#9908 Remove the support for the kokoro cocoapods integration tests.
  Makefile.am
  kokoro/macos/objectivec_cocoapods_integration/build.sh
  kokoro/macos/objectivec_cocoapods_integration/continuous.cfg
  kokoro/macos/objectivec_cocoapods_integration/presubmit.cfg
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester.xcodeproj/project.pbxproj
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester.xcodeproj/xcshareddata/xcschemes/OSXCocoaPodsTester.xcscheme
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/AppDelegate.h
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/AppDelegate.m
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/Assets.xcassets/AppIcon.appiconset/Contents.json
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/Base.lproj/MainMenu.xib
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/Info.plist
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/OSXCocoaPodsTester/main.m
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/Podfile-framework
  objectivec/Tests/CocoaPods/OSXCocoaPodsTester/Podfile-static
  objectivec/Tests/CocoaPods/README.md
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/Podfile-framework
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/Podfile-static
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester.xcodeproj/project.pbxproj
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester.xcodeproj/xcshareddata/xcschemes/iOSCocoaPodsTester.xcscheme
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/AppDelegate.h
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/AppDelegate.m
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/Assets.xcassets/AppIcon.appiconset/Contents.json
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/Base.lproj/LaunchScreen.storyboard
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/Base.lproj/Main.storyboard
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/Info.plist
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/ViewController.h
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/ViewController.m
  objectivec/Tests/CocoaPods/iOSCocoaPodsTester/iOSCocoaPodsTester/main.m
  objectivec/Tests/CocoaPods/run_tests.sh
  tests.sh
Labels: objective-c, release notes: no

#9905 ObjC: Revise the minimal extension deps algorithm.
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
Labels: objective-c, release notes: no

#9882 Add Starlark utilities to generate files with lists of files
  pkg/BUILD.bazel
  pkg/build_systems.bzl
Labels: cmake, bazel, autotools, release notes: no

#9909 Remove duplicate java generated code
  java/kotlin/generate-sources-build.xml
Labels: release notes: yes, kotlin

#9885 Use PROTOBUF_CONSTEXPR instead of constexpr for kRepHeaderSize
  src/google/protobuf/port_def.inc
  src/google/protobuf/repeated_field.h
Labels: c++, release notes: no

#9910 Remove references to //:composer.json and JS compiler.
  BUILD.bazel
  pkg/BUILD.bazel
Labels: release notes: no

#9913 [Bazel] Fix broken build rules or mark them manual
  BUILD.bazel
  java/core/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
  java/util/BUILD.bazel
Labels: bazel, release notes: no

#9915 [Bazel] Expand lists of protos in BUILD files
  BUILD.bazel
  java/core/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
Labels: bazel, release notes: no

#9923 Updated to upb for -rc1.
  protobuf_deps.bzl
  protobuf_version.bzl
Labels: release notes: no

#9926 Increment python major version to 4 in version.json for python upb
  version.json
Labels: python, release notes: yes

#9927 Integrate from Piper for C++, Java, and Python
  src/google/protobuf/arena.h
  src/google/protobuf/compiler/cpp/helpers.cc
  src/google/protobuf/compiler/cpp/options.h
  src/google/protobuf/map.h
  src/google/protobuf/message_unittest.inc
Labels: release notes: no

#9891 Add macosx action environment variable
  toolchain/toolchains.bazelrc
Labels: bazel, release notes: no

#9921 [Bazel] Move C++ build-related logic into //build_defs
  BUILD.bazel
  Makefile.am
  build_defs/BUILD.bazel
  build_defs/cc_proto_blacklist_test.bzl
  build_defs/compiler_config_setting.bzl
  build_defs/cpp_opts.bzl
  java/kotlin-lite/BUILD.bazel
  kokoro/linux/bazel/build.sh
  pkg/BUILD.bazel
Labels: bazel, release notes: no

#9922 [Bazel] Move conformance test targets to //conformance.
  BUILD.bazel
  Makefile.am
  conformance/BUILD.bazel
  conformance/conformance_test_runner.sh
  conformance/defs.bzl
  java/core/BUILD.bazel
  java/lite/BUILD.bazel
Labels: bazel, release notes: no

#9928 Added cmake abseil include guard
  cmake/abseil-cpp.cmake
Labels: c++, cmake, release notes: no

#9936 Use __constinit only in GCC 12.2 and up
  src/google/protobuf/port_def.inc
Labels: c++, release notes: yes

#9929 Add a test for bazel-built dist archives
  BUILD.bazel
  benchmarks/BUILD.bazel
  benchmarks/cpp/BUILD.bazel
  benchmarks/datasets/google_message1/proto2/BUILD.bazel
  benchmarks/datasets/google_message1/proto3/BUILD.bazel
  benchmarks/datasets/google_message2/BUILD.bazel
  benchmarks/datasets/google_message3/BUILD.bazel
  benchmarks/datasets/google_message4/BUILD.bazel
  conformance/BUILD.bazel
  kokoro/linux/bazel_distcheck/build.sh
  kokoro/linux/bazel_distcheck/continuous.cfg
  kokoro/linux/bazel_distcheck/presubmit.cfg
  pkg/BUILD.bazel
  third_party/BUILD.bazel
Labels: release notes: no

#9621 feat: [PHP] remove legacy generate class file
  src/google/protobuf/compiler/php/php_generator.cc
Labels: php, release notes: yes

#9949 Run kotlin tests on JDK 8 *and later*
  tests.sh
Labels: release notes: no, kotlin

#9939 [Kokoro] Add dist check build for linux+cmake
  kokoro/common/caplog.sh
  kokoro/common/check_missing_dist_files.sh
  kokoro/common/cmake.sh
  kokoro/linux/cmake_distcheck/build.sh
  kokoro/linux/cmake_distcheck/continuous.cfg
  kokoro/linux/cmake_distcheck/presubmit.cfg
  kokoro/macos-next/cpp/build.sh
Labels: cmake, release notes: no

#9950 Switch C++ test protos to use the normal cc_proto_library rules.
  BUILD.bazel
  java/core/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
  java/lite/BUILD.bazel
Labels: bazel, release notes: no

#9951 Change how proto_gen rule exposes sources
  protobuf.bzl
Labels: bazel, release notes: no

#9946 Add endian.h to includes list
  cmake/extract_includes.bat.in
Labels: cmake, release notes: yes

#9952 [Bazel] Move Python rules to //python
  BUILD.bazel
  Makefile.am
  kokoro/common/check_missing_dist_files.sh
  kokoro/linux/bazel_distcheck/build.sh
  pkg/BUILD.bazel
  protobuf.bzl
  python/BUILD.bazel
  python/internal.bzl
Labels: bazel, release notes: no

#9695 Helper method on Any to allow an any to be unpacked more easily
  csharp/src/Google.Protobuf.Test/WellKnownTypes/AnyTest.cs
  csharp/src/Google.Protobuf/WellKnownTypes/AnyPartial.cs
Labels: c#, release notes: yes

#9959 Reserve extension id for Protonium
  docs/options.md
Labels: release notes: no

#9962 Update version.json to: 21.0-dev
  version.json
Labels: release notes: no

#9344 Various fixups to warnings flags
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/importer.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser_unittest.cc
Labels: protoc, release notes: no

#9963 Ruby: Support x64-mingw-ucrt platform
  ruby/Rakefile
Labels: ruby, release notes: no

#9967 Fix c# Kokoro errors
  csharp/src/Google.Protobuf/WellKnownTypes/AnyPartial.cs
Labels: c#, release notes: no

#9602 Fix failing FieldMask.Merge for well-known wrapper field types
  csharp/src/Google.Protobuf.Test/FieldMaskTreeTest.cs
  csharp/src/Google.Protobuf/FieldMaskTree.cs
Labels: cla: yes, c#, release notes: yes

#9964 Merge 21.x back to main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  kokoro/docs/publish-python.sh
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/docs/requirements.txt
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#9976 Fixed win32 build and fixed str(message) on all Windows platforms.
  protobuf_deps.bzl
Labels: python, release notes: yes

#9969 21.x Backport: Ruby: Support x64-mingw-ucrt platform
  ruby/Rakefile
Labels: ruby, release notes: no

#9965 [Bazel/macOS] Use the constructed environment when running libtool.
  pkg/cc_dist_library.bzl
Labels: bazel, release notes: no

#9968 [Python] Handle user-provided `--link-objects` and `--library-dirs`.
  kokoro/release/python/macos/config.sh
  python/setup.py
Labels: release notes: no

#9980 [Bazel/C++] Factor out stubs, io, and testing libraries.
  BUILD.bazel
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel_distcheck/build.sh
  pkg/BUILD.bazel
  src/Makefile.am
  src/google/protobuf/io/BUILD.bazel
  src/google/protobuf/stubs/BUILD.bazel
  src/google/protobuf/testing/BUILD.bazel
Labels: release notes: no

#9979 Fix protoc_release target
  BUILD.bazel
  pkg/BUILD.bazel
Labels: packaging & distribution, release notes: no

#9966 [Kokoro] Switch macos/python_release to use bazel-built cc_dist_library targets
  kokoro/release/python/macos/config.sh
Labels: release notes: no

#9985 [Bazel/C++] Factor out compiler packages.
  BUILD.bazel
  conformance/BUILD.bazel
  csharp/BUILD.bazel
  pkg/BUILD.bazel
  src/Makefile.am
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
  src/google/protobuf/compiler/csharp/BUILD.bazel
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/php/BUILD.bazel
  src/google/protobuf/compiler/python/BUILD.bazel
  src/google/protobuf/compiler/ruby/BUILD.bazel
Labels: c++, bazel, release notes: no

#9986 Updated upb, which will give a better error message if generated code is out of date
  protobuf_deps.bzl
Labels: release notes: no

#9988 [Bazel/C++] Move core C++ implementation to //src/google/protobuf package.
  BUILD.bazel
  java/core/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
  java/lite/BUILD.bazel
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel_distcheck/build.sh
  pkg/BUILD.bazel
  python/BUILD.bazel
  src/BUILD.bazel
  src/Makefile.am
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
  src/google/protobuf/compiler/csharp/BUILD.bazel
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/php/BUILD.bazel
  src/google/protobuf/compiler/python/BUILD.bazel
  src/google/protobuf/compiler/ruby/BUILD.bazel
  src/google/protobuf/io/BUILD.bazel
  src/google/protobuf/stubs/BUILD.bazel
  src/google/protobuf/testing/BUILD.bazel
  src/google/protobuf/util/BUILD.bazel
  src/google/protobuf/util/internal/BUILD.bazel
Labels: c++, bazel, release notes: no

#9995 Fixed PHP SEGV by not writing to shared memory for zend_class_entry.
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
Labels: php, release notes: yes

#9996 Fixed PHP SEGV by not writing to shared memory for zend_class_entry.
  php/ext/google/protobuf/message.c
  php/ext/google/protobuf/protobuf.c
  php/ext/google/protobuf/protobuf.h
Labels: php, release notes: yes

#10000 Cherry-pick PR #9981 into 21.x branch
  csharp/src/AddressBook/Addressbook.cs
  csharp/src/Google.Protobuf.Benchmarks/BenchmarkMessage1Proto3.cs
  csharp/src/Google.Protobuf.Benchmarks/Benchmarks.cs
  csharp/src/Google.Protobuf.Benchmarks/WrapperBenchmarkMessages.cs
  csharp/src/Google.Protobuf.Conformance/Conformance.cs
  csharp/src/Google.Protobuf.Test.TestProtos/MapUnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto2.cs
  csharp/src/Google.Protobuf.Test.TestProtos/TestMessagesProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/Unittest.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestCustomOptionsProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImport.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublic.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestImportPublicProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936A.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936B.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssue6936C.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestProto3Optional.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestSelfreferentialOptions.cs
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestWellKnownTypes.cs
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Any.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Api.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Duration.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Empty.cs
  csharp/src/Google.Protobuf/WellKnownTypes/FieldMask.cs
  csharp/src/Google.Protobuf/WellKnownTypes/SourceContext.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Struct.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Timestamp.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Type.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Wrappers.cs
  src/google/protobuf/compiler/csharp/csharp_reflection_class.cc
Labels: c#, release notes: yes

#10003 Fix some style/lint issues.
  build_defs/cpp_opts.bzl
  conformance/defs.bzl
  python/setup.py
Labels: release notes: no

#9997 Add protoc-gen-xo to global extension registry
  docs/options.md
Labels: release notes: no

#10006 Update version.json to: 21.0-dev
  version.json
Labels: release notes: no

#10009 [Bazel] Use pyenv to select Python 3.9.5 on our linux/bazel builds.
  kokoro/common/pyenv.sh
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel_distcheck/build.sh
Labels: release notes: no

#10018 Merge 21.x into Main
  CHANGES.txt
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  pkg/BUILD.bazel
  protobuf_deps.bzl
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: release notes: no

#10019 Fix podspecs
  Protobuf-C++.podspec
  Protobuf.podspec
Labels: release notes: no

#10010 [Bazel] Make the protobuf workspace (nearly) wildcard-buildable
  benchmarks/BUILD.bazel
  pkg/build_systems.bzl
Labels: bazel, release notes: no

#10008 [Kokoro/Bazel] Send Bazel build results to BES.
  kokoro/common/bazel_wrapper.sh
  kokoro/linux/bazel/build.sh
  kokoro/linux/bazel/common.cfg
  kokoro/linux/bazel_distcheck/build.sh
  kokoro/linux/bazel_distcheck/common.cfg
Labels: bazel, release notes: no

#10025 Fixed the Windows build of protoc by statically linking deps.
  BUILD.bazel
  build_defs/BUILD.bazel
  build_defs/cpp_opts.bzl
Labels: release notes: no

#10026 [Bazel/C++] Augment `cc_dist_library` to generate lists of source files
  pkg/BUILD.bazel
  pkg/build_systems.bzl
  pkg/cc_dist_library.bzl
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
  src/google/protobuf/compiler/csharp/BUILD.bazel
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/php/BUILD.bazel
  src/google/protobuf/compiler/python/BUILD.bazel
  src/google/protobuf/compiler/ruby/BUILD.bazel
Labels: bazel, release notes: no

#10037 Revert "Various fixups to warnings flags (#9344)"
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/importer.cc
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser_unittest.cc
Labels: release notes: no

#10036 Revert "fix: reserve "ReadOnly" keyword for PHP 8.1 and add compatibi…lity (#9633)"
  php/ext/google/protobuf/names.c
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/tests/GeneratedClassTest.php
  php/tests/proto/test_reserved_enum_lower.proto
  php/tests/proto/test_reserved_enum_upper.proto
  php/tests/proto/test_reserved_enum_value_lower.proto
  php/tests/proto/test_reserved_enum_value_upper.proto
  php/tests/proto/test_reserved_message_lower.proto
  php/tests/proto/test_reserved_message_upper.proto
  src/google/protobuf/compiler/php/php_generator.cc
Labels: release notes: no

#10024 Add header search paths to protobuf-c++ spec
  Protobuf-C++.podspec
Labels: c++, release notes: yes

#10014 Adding a DEPENDENCIES option to the protobuf_generate cmake function
  cmake/protobuf-config.cmake.in
Labels: cmake, release notes: no

#10039 [Bazel/C++] Split apart protobuf_test rule
  src/google/protobuf/BUILD.bazel
Labels: c++, bazel, release notes: no

#10044 Update versions and changelog for 21.x
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
  version.json
Labels: release notes: no

#10015 Migrate linux-aarch64 tests away from autotools
  kokoro/linux/aarch64/cpp_crosscompile_and_run_tests_with_qemu_aarch64.sh
  kokoro/linux/aarch64/dockcross_helpers/run_dockcross_manylinux2014_aarch64.sh
  kokoro/linux/aarch64/protoc_crosscompile_aarch64.sh
  kokoro/linux/aarch64/python_crosscompile_aarch64.sh
  kokoro/linux/aarch64/python_run_tests_with_qemu_aarch64.sh
Labels: autotools, release notes: no

#10057 Cherry-pick #9946 to 21.x
  cmake/extract_includes.bat.in
Labels: release notes: no

#10058 Update upb commit/sha256 to include updated python wheel
  protobuf_deps.bzl
Labels: python, release notes: yes

#10060 Revert "Fix cmake install targets (#9822)"
  cmake/install.cmake
Labels: c++, release notes: no

#10061 [Bazel] Add back a filegroup for :well_known_protos.
  BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
Labels: bazel, release notes: no

#10047 Update version.json to: 21.1-dev
  version.json
Labels: release notes: no

#10066 Update upb commit to include fix for segmentation fault when instanti…
  protobuf_deps.bzl
Labels: python, release notes: yes

#10067 Fix continuous aarch64 builds
  kokoro/linux/aarch64/protoc_crosscompile_aarch64.sh
Labels: c++, release notes: no

#10071 Update version.json to 21.2-dev
  version.json
Labels: release notes: no

#10089 Remove expected cmake failure due to missing abseil sources, since ab…
  kokoro/linux/cmake_distcheck/build.sh
Labels: cmake, release notes: no

#10049 [Bazel] Add filegroups for test sources and include them in file lists.
  pkg/BUILD.bazel
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
  src/google/protobuf/compiler/csharp/BUILD.bazel
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/php/BUILD.bazel
  src/google/protobuf/compiler/python/BUILD.bazel
  src/google/protobuf/compiler/ruby/BUILD.bazel
  src/google/protobuf/io/BUILD.bazel
  src/google/protobuf/stubs/BUILD.bazel
  src/google/protobuf/util/BUILD.bazel
  src/google/protobuf/util/internal/BUILD.bazel
Labels: bazel, release notes: no

#10027 Move cmake file lists into src/file_lists.cmake.
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/tests.cmake
  src/Makefile.am
  src/file_lists.cmake
Labels: cmake, release notes: no
