Repository protocolbuffers/protobuf, pull requests merged in 2022-04, with the labels that each got.

#9721 Merge 3.20.0 into main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/release.sh
  protobuf.bzl
  protobuf_deps.bzl
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
  update_version.py
Labels: release notes: no

#9709 [Kokoro] Emit XML test logs on macos-next.
  kokoro/caplog.sh
  kokoro/macos-next/cpp/build.sh
  kokoro/macos-next/cpp/continuous.cfg
  kokoro/macos-next/cpp/presubmit.cfg
Labels: release notes: no

#9714 JRuby fixes for 3.20.x
  ruby/src/main/java/com/google/protobuf/jruby/RubyDescriptor.java
  ruby/src/main/java/com/google/protobuf/jruby/RubyMessage.java
  ruby/tests/basic.rb
  ruby/tests/basic_proto2.rb
  ruby/tests/common_tests.rb
Labels: ruby, release notes: yes, jruby

#9738 Remove unused `HasTopLevelEnums` function
  src/google/protobuf/compiler/python/generator.cc
Labels: python, release notes: no

#9745 Tweak how python/python3 is used.
  objectivec/DevTools/full_mac_build.sh
  objectivec/DevTools/pddm.py
  objectivec/DevTools/pddm_tests.py
Labels: release notes: no

#9727 Fix building packaged PHP extension
  .github/workflows/php-ext.yml
  php/ext/google/protobuf/config.m4
Labels: php, release notes: yes

#9642 [Kotlin] remove redundant public modifiers for compiled code
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/map_field_lite.cc
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/message_field_lite.cc
  src/google/protobuf/compiler/java/message_lite.cc
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/primitive_field_lite.cc
  src/google/protobuf/compiler/java/string_field.cc
  src/google/protobuf/compiler/java/string_field_lite.cc
Labels: release notes: yes, kotlin

#9735 include gen_dir irrespective of sources_dir in protoc_gen
  protobuf.bzl
Labels: bug, bazel, release notes: no

#9722 [Ruby] Fix RepeatedField#last, #first inconsistencies
  ruby/lib/google/protobuf/repeated_field.rb
  ruby/tests/repeated_field_test.rb
Labels: ruby, release notes: yes

#9750 Add k8 toolchain
  toolchain/BUILD
  toolchain/cc_toolchain_config.bzl
Labels: bazel, release notes: no

#9753 -DfailIfNoSpecifiedTests=false
  kokoro/linux/aarch64/test_java_aarch64.sh
Labels: java, release notes: no

#9761 -Dsurefire.
  kokoro/linux/aarch64/test_java_aarch64.sh
Labels: java, release notes: no

#9760 Merge 3.20.1-rc1 into main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#9754 Add Google Gnostic Registered Extension Number
  docs/options.md
Labels: release notes: no

#9767 Add micro Registered Extension Number
  docs/options.md
Labels: release notes: no

#9752 Update protobuf_deps.bzl to add a dependency on Abseil
  protobuf_deps.bzl
Labels: c++, bazel, release notes: no

#9757 deps: update Guava to 31.1
  java/pom.xml
Labels: java, release notes: no

#9777 Replace master with main in URLs & docs
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  README.md
  benchmarks/README.md
  cmake/README.md
  conformance/README.md
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf.Benchmarks/GoogleMessageBenchmark.cs
  docs/implementing_proto3_presence.md
  docs/jvm_aot.md
  docs/performance.md
  examples/WORKSPACE
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  js/README.md
  js/package.json
  kokoro/docs/publish-python.sh
  kokoro/docs/trampoline.sh
  objectivec/GPBCodedInputStream.m
  python/docs/generate_docs.py
  src/google/protobuf/compiler/annotation_test_util.h
  src/google/protobuf/compiler/java/file.cc
  src/google/protobuf/util/internal/protostream_objectwriter.cc
Labels: documentation, release notes: no

#9633 fix: reserve "ReadOnly" keyword for PHP 8.1 and add compatibility
  php/ext/google/protobuf/names.c
  php/src/Google/Protobuf/Internal/GPBUtil.php
  php/tests/GeneratedClassTest.php
  php/tests/proto/test_reserved_enum_lower.proto
  php/tests/proto/test_reserved_enum_upper.proto
  php/tests/proto/test_reserved_enum_value_lower.proto
  php/tests/proto/test_reserved_enum_value_upper.proto
  php/tests/proto/test_reserved_message_lower.proto
  php/tests/proto/test_reserved_message_upper.proto
  src/google/protobuf/compiler/php/php_generator.cc
Labels: php, release notes: yes

#9787 Remove unnecessary console output from test
  csharp/src/Google.Protobuf.Test/Collections/MapFieldTest.cs
Labels: c#, release notes: no

#9788 Add disallowment of setting numpy singleton arrays and multi-dimensio…
  CHANGES.txt
Labels: python, documentation, release notes: no

#9791 Move private utf8 helpers to anonymous namespace
  src/google/protobuf/stubs/structurally_valid.cc
Labels: c++, release notes: no

#9743 add JDK 8 target
  tests.sh
Labels: java, release notes: no

#9741 LAST_RELEASED=3.20.0
  tests.sh
Labels: release notes: no

#9803 Remove LAST_RELEASED variable we haven't been updating
  tests.sh
Labels: php, release notes: no

#9802 Add JDK 17 target
  tests.sh
Labels: java, release notes: no

#9784 fix: phpdoc syntax for repeatedfield parameters
  php/src/Google/Protobuf/Api.php
  php/src/Google/Protobuf/Enum.php
  php/src/Google/Protobuf/EnumValue.php
  php/src/Google/Protobuf/Field.php
  php/src/Google/Protobuf/FieldMask.php
  php/src/Google/Protobuf/Internal/DescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumDescriptorProto.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/EnumValueOptions.php
  php/src/Google/Protobuf/Internal/ExtensionRangeOptions.php
  php/src/Google/Protobuf/Internal/FieldOptions.php
  php/src/Google/Protobuf/Internal/FileDescriptorProto.php
  php/src/Google/Protobuf/Internal/FileDescriptorSet.php
  php/src/Google/Protobuf/Internal/FileOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  php/src/Google/Protobuf/Internal/MethodOptions.php
  php/src/Google/Protobuf/Internal/OneofOptions.php
  php/src/Google/Protobuf/Internal/ServiceDescriptorProto.php
  php/src/Google/Protobuf/Internal/ServiceOptions.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo.php
  php/src/Google/Protobuf/Internal/SourceCodeInfo/Location.php
  php/src/Google/Protobuf/Internal/UninterpretedOption.php
  php/src/Google/Protobuf/ListValue.php
  php/src/Google/Protobuf/Method.php
  php/src/Google/Protobuf/Type.php
  php/tests/GeneratedPhpdocTest.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: php, release notes: yes

#9769 Do not use range based UTF-8 validation in truffleruby
  third_party/utf8_range/utf8_range.h
Labels: ruby, release notes: yes, platform related

#9783 fix: phpdoc for repeatedfield
  php/src/Google/Protobuf/Internal/RepeatedField.php
Labels: php, release notes: yes

#9807 Apply registration for `protoc-gen-authz` extension
  docs/options.md
Labels: release notes: no

#9816 Disable the aarch64 build on macOS because it is broken.
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
Labels: ruby, release notes: yes

#9819 fix: move composer.json out of root to avoid confusion
  php/composer.json.dist
  php/release.sh
Labels: php, release notes: yes

#9820 Update protobuf version
  Makefile.am
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/port_def.inc
  src/google/protobuf/stubs/common.h
Labels: release notes: no

#9823 Move rules_pkg targets into //pkg, and add experimental C++ library rules
  BUILD
  pkg/BUILD
  pkg/cc_dist_library.bzl
Labels: release notes: no

#9826 Updated CHANGES.txt for 3.20.1
  CHANGES.txt
Labels: release notes: no

#9822 Fix cmake install targets
  cmake/install.cmake
Labels: c++, cmake, release notes: yes

#9833 Upgrade bazelbuild/rules_pkg to 0.7.0.
  protobuf_deps.bzl
Labels: release notes: no

#9831 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/Utf8.java
  java/core/src/test/java/com/google/protobuf/GeneratedMessageTest.java
  python/google/protobuf/internal/api_implementation.py
  python/google/protobuf/internal/text_format_test.py
  python/google/protobuf/internal/unknown_fields_test.py
  python/google/protobuf/text_format.py
  python/google/protobuf/unknown_fields.py
  src/google/protobuf/compiler/cpp/helpers.cc
  src/google/protobuf/compiler/cpp/helpers.h
  src/google/protobuf/compiler/cpp/message.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/generated_message_reflection.cc
  src/google/protobuf/generated_message_reflection_unittest.cc
  src/google/protobuf/metadata_lite.h
Labels: release notes: no

#9832 Fixed PHP release script.
  php/composer.json.dist
  php/release.sh
Labels: release notes: no

#9836 Integrate from Piper for C++, Java, and Python
  python/google/protobuf/internal/api_implementation.py
Labels: release notes: no

#9815 Remove old kokoro configs
  kokoro/linux/64-bit/Dockerfile
  kokoro/linux/golang/build.sh
  kokoro/linux/golang/continuous.cfg
  kokoro/linux/golang/presubmit.cfg
  kokoro/linux/java_jdk7/build.sh
  kokoro/linux/java_jdk7/continuous.cfg
  kokoro/linux/java_jdk7/presubmit.cfg
  kokoro/linux/java_oracle7/build.sh
  kokoro/linux/java_oracle7/continuous.cfg
  kokoro/linux/java_oracle7/presubmit.cfg
  kokoro/linux/php80/build.sh
  kokoro/linux/php80/continuous.cfg
  kokoro/linux/php80/presubmit.cfg
  kokoro/linux/python_compatibility/build.sh
  kokoro/linux/python_compatibility/continuous.cfg
  kokoro/linux/python_compatibility/presubmit.cfg
  kokoro/linux/python_cpp/build.sh
  kokoro/linux/python_cpp/continuous.cfg
  kokoro/linux/python_cpp/presubmit.cfg
Labels: java, release notes: no

#9834 Merge 3.20.x to main
  CHANGES.txt
  Makefile.am
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  php/composer.json.dist
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  php/release.sh
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
Labels: release notes: no

#9837 add Kokoro config for OpenJDK11
  kokoro/linux/java_jdk11/build.sh
  kokoro/linux/java_jdk11/continuous.cfg
  kokoro/linux/java_jdk11/presubmit.cfg
Labels: java, release notes: no

#9840 Add initial version.json file for 21-dev
  version.json
Labels: json, integration, release notes: yes

#9843 Add jdk11 test
  tests.sh
Labels: release notes: no

#9835 Add source distribution packaging rules
  BUILD
  Makefile.am
  benchmarks/BUILD
  benchmarks/cpp/BUILD
  benchmarks/datasets/BUILD
  benchmarks/datasets/google_message1/proto2/BUILD
  benchmarks/datasets/google_message1/proto3/BUILD
  benchmarks/datasets/google_message2/BUILD
  benchmarks/datasets/google_message3/BUILD
  benchmarks/datasets/google_message4/BUILD
  csharp/BUILD
  examples/BUILD
  java/BUILD
  java/core/BUILD
  java/internal/BUILD
  java/kotlin-lite/BUILD
  java/kotlin/BUILD
  java/lite/BUILD
  java/util/BUILD
  js/BUILD
  objectivec/BUILD
  php/BUILD
  pkg/BUILD
  pkg/README.md
  ruby/BUILD
  third_party/zlib.BUILD
  util/python/BUILD
Labels: bazel, release notes: no

#9848 -Dsurefire.failIfNoSpecifiedTests=false
  kokoro/linux/aarch64/test_java_aarch64.sh
Labels: java, release notes: no

#9849 Remove some unnecessary header includes from objectivec sources.
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message_field.cc
Labels: objective-c, release notes: no

#9845 Add Kokoro config for JDK 17
  kokoro/linux/dockerfile/test/java_stretch/Dockerfile
  kokoro/linux/java_jdk17/build.sh
  kokoro/linux/java_jdk17/continuous.cfg
  kokoro/linux/java_jdk17/presubmit.cfg
Labels: java, release notes: no

#9850 Remove 2 more unnecessary header includes from objectivec sources.
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc
Labels: objective-c, release notes: no

#9812 Added a Bazel dependency for upb
  BUILD
  WORKSPACE
  protobuf_deps.bzl
  python/google/protobuf/internal/test_util.py
  python/google/protobuf/internal/testing_refleaks.py
Labels: release notes: no

#9847 Fix typos
  kokoro/linux/aarch64/test_java_aarch64.sh
Labels: java, release notes: no

#9852 Remove various unused includes
  python/google/protobuf/pyext/extension_dict.h
  python/google/protobuf/pyext/map_container.h
  python/google/protobuf/pyext/repeated_composite_container.h
  python/google/protobuf/pyext/repeated_scalar_container.h
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
  src/google/protobuf/compiler/java/message_lite.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.h
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/io/zero_copy_stream.h
  src/google/protobuf/wire_format.h
Labels: c++, protoc, release notes: no

#9851 Update more code to use standard int types.
  src/google/protobuf/compiler/js/js_generator.cc
  src/google/protobuf/compiler/js/js_generator.h
  src/google/protobuf/compiler/ruby/ruby_generator.cc
  src/google/protobuf/stubs/common.cc
  src/google/protobuf/stubs/int128.cc
  src/google/protobuf/stubs/int128.h
  src/google/protobuf/stubs/int128_unittest.cc
  src/google/protobuf/stubs/port.h
  src/google/protobuf/stubs/structurally_valid.cc
  src/google/protobuf/stubs/strutil.cc
  src/google/protobuf/stubs/strutil.h
  src/google/protobuf/stubs/time.cc
  src/google/protobuf/stubs/time.h
Labels: release notes: no

#9800 Add a github action workflow to run CocoaPods validation.
  .github/workflows/objc_cocoapods.yml
  Protobuf.podspec
Labels: objective-c, release notes: no

#9780 Change enum string name for reserved words
  php/tests/GeneratedClassTest.php
  src/google/protobuf/compiler/php/php_generator.cc
Labels: php, release notes: yes

#9771 fix some typos
  csharp/src/Google.Protobuf/CodedInputStream.cs
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
  docs/field_presence.md
  post_process_dist.sh
  src/google/protobuf/compiler/cpp/helpers.h
  src/google/protobuf/io/coded_stream.cc
  src/google/protobuf/parse_context.h
Labels: c#, c++, documentation, cleanup, kokoro:run, kokoro:force-run, release notes: no

#9860 Rollback of #9852
  python/google/protobuf/pyext/extension_dict.h
  python/google/protobuf/pyext/map_container.h
  python/google/protobuf/pyext/repeated_composite_container.h
  python/google/protobuf/pyext/repeated_scalar_container.h
  src/google/protobuf/compiler/csharp/csharp_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_map_field.h
  src/google/protobuf/compiler/csharp/csharp_message_field.h
  src/google/protobuf/compiler/csharp/csharp_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_message_field.h
  src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.h
  src/google/protobuf/compiler/csharp/csharp_wrapper_field.h
  src/google/protobuf/compiler/java/message_lite.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.h
  src/google/protobuf/generated_message_reflection.h
  src/google/protobuf/io/zero_copy_stream.h
  src/google/protobuf/wire_format.h
Labels: c++, release notes: no

#9858 Remove a bunch of clang-tidy warnings re explicit
  src/google/protobuf/compiler/objectivec/objectivec_enum_field.h
  src/google/protobuf/compiler/objectivec/objectivec_field.h
  src/google/protobuf/compiler/objectivec/objectivec_map_field.h
  src/google/protobuf/compiler/objectivec/objectivec_message_field.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.h
Labels: objective-c, release notes: no

#9859 Integrate from Piper for C++, Java, and Python
  csharp/src/Google.Protobuf.Test/testprotos.pb
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/test/proto/com/google/protobuf/test_bad_identifiers.proto
  python/google/protobuf/internal/descriptor_pool_test.py
  python/google/protobuf/internal/message_test.py
  python/google/protobuf/internal/unknown_fields_test.py
  src/google/protobuf/compiler/java/helpers.cc
  src/google/protobuf/io/coded_stream_unittest.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/util/delimited_message_util.cc
  src/google/protobuf/util/time_util.cc
  src/google/protobuf/util/time_util.h
Labels: release notes: no

#9862 Fail on unit tests failure
  kokoro/linux/java_jdk11/build.sh
  kokoro/linux/java_jdk17/build.sh
Labels: java, release notes: no

#9864 Updated upb.
  protobuf_deps.bzl
Labels: release notes: no

#9871 Update UPB version
  protobuf_deps.bzl
Labels: release notes: no

#9873 build_java without conformance tests
  tests.sh
Labels: java, release notes: no

#9866 Include JDK11 in error message on first run
  tests.sh
Labels: java, release notes: no

#9881 Specify full path to testing `.proto` files
  cmake/tests.cmake
Labels: release notes: no

#9880 Factor out MSVC-only `version.rc` logic, and ensure other variables are always initialized
  CMakeLists.txt
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
  cmake/protoc.cmake
  cmake/tests.cmake
Labels: release notes: no

#9889 Make genrule portable for windows
  protobuf.bzl
  third_party/zlib.BUILD
Labels: bazel, release notes: no

#9883 Add forwarding lang_generator.h headers for cpp, java, and python.
  cmake/extract_includes.bat.in
  cmake/libprotoc.cmake
  src/Makefile.am
  src/google/protobuf/compiler/cpp/cpp_generator.h
  src/google/protobuf/compiler/java/java_generator.h
  src/google/protobuf/compiler/python/python_generator.h
Labels: release notes: no

#9890 Be explicit with empty globs
  BUILD
Labels: bazel, release notes: no

#9892 Rename all BUILD files to BUILD.bazel
  BUILD.bazel
  Makefile.am
  benchmarks/BUILD.bazel
  benchmarks/cpp/BUILD.bazel
  benchmarks/datasets/BUILD.bazel
  benchmarks/datasets/google_message1/proto2/BUILD.bazel
  benchmarks/datasets/google_message1/proto3/BUILD.bazel
  benchmarks/datasets/google_message2/BUILD.bazel
  benchmarks/datasets/google_message3/BUILD.bazel
  benchmarks/datasets/google_message4/BUILD.bazel
  csharp/BUILD.bazel
  examples/BUILD.bazel
  java/BUILD.bazel
  java/core/BUILD.bazel
  java/internal/BUILD.bazel
  java/kotlin-lite/BUILD.bazel
  java/kotlin/BUILD.bazel
  java/lite/BUILD.bazel
  java/util/BUILD.bazel
  objectivec/BUILD.bazel
  php/BUILD.bazel
  pkg/BUILD.bazel
  ruby/BUILD.bazel
  third_party/BUILD.bazel
  third_party/utf8_range/BUILD.bazel
  toolchain/BUILD.bazel
  util/python/BUILD.bazel
Labels: release notes: no
