Repository protocolbuffers/protobuf, pull requests merged in 2022-01, with the labels that each got.

#9216 Pin multibuild scripts to get manylinux1 wheels back
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/windows/build_artifacts.bat
Labels: cla: yes, python, release notes: yes

#9368 fix spelling errors
  js/experimental/runtime/kernel/kernel_test.js
  js/experimental/runtime/kernel/tag_test.js
Labels: javascript, release notes: no

#9372 Fix Ruby release build by pinning rake-compiler-dock version
  ruby/google-protobuf.gemspec
Labels: release notes: no

#9371 Improve performance of parsing unknown fields in Java
  Makefile.am
  java/core/BUILD
  java/core/src/main/java/com/google/protobuf/UnknownFieldSet.java
  java/core/src/test/java/com/google/protobuf/UnknownFieldSetPerformanceTest.java
  java/core/src/test/java/com/google/protobuf/UnknownFieldSetTest.java
  java/lite/pom.xml
Labels: java, release notes: no

#9376 Default two more of the options from env variables.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
Labels: objective-c, release notes: no

#9367 update GSON to 2.8.9
  java/util/pom.xml
  maven_install.json
  protobuf_deps.bzl
Labels: java, release notes: no

#9354 BUILD: Set `protoc` binary file mode to 0555 in release archive
  BUILD
Labels: protoc, bazel, release notes: no

#9381 Update, fix, or delete an assortment of broken links
  docs/third_party.md
Labels: documentation, release notes: no

#9382 Revert "Transition to NIO StandardCharsets"
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/ByteString.java
  java/core/src/main/java/com/google/protobuf/CodedInputStream.java
  java/core/src/main/java/com/google/protobuf/CodedOutputStream.java
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  java/core/src/main/java/com/google/protobuf/Internal.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/Utf8.java
  java/core/src/test/java/com/google/protobuf/BoundedByteStringTest.java
  java/core/src/test/java/com/google/protobuf/ByteStringTest.java
  java/core/src/test/java/com/google/protobuf/CodedOutputStreamTest.java
  java/core/src/test/java/com/google/protobuf/DecodeUtf8Test.java
  java/core/src/test/java/com/google/protobuf/DescriptorsTest.java
  java/core/src/test/java/com/google/protobuf/IsValidUtf8TestUtil.java
  java/core/src/test/java/com/google/protobuf/LiteralByteStringTest.java
  java/core/src/test/java/com/google/protobuf/NioByteStringTest.java
  java/core/src/test/java/com/google/protobuf/RopeByteStringSubstringTest.java
  java/core/src/test/java/com/google/protobuf/RopeByteStringTest.java
  java/core/src/test/java/com/google/protobuf/TextFormatTest.java
  java/core/src/test/java/com/google/protobuf/Utf8Test.java
  java/core/src/test/java/com/google/protobuf/WrappersLiteOfMethodTest.java
  java/core/src/test/java/com/google/protobuf/WrappersOfMethodTest.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
Labels: java, java-lite, release notes: no

#9386 restore Android API level 14 compatibility
  java/core/src/main/java/com/google/protobuf/ByteString.java
Labels: java, java-lite, release notes: no

#9388 restore even more Android API level 14 compatibility
  java/core/src/main/java/com/google/protobuf/Descriptors.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
Labels: java, java-lite, release notes: no

#9383 turn on animal-sniffer
  java/pom.xml
  java/util/pom.xml
Labels: java, java-lite, release notes: no

#9389 Update protojure link
  docs/third_party.md
Labels: documentation, release notes: no

#9400 Revert "Standardize on Array copyOf"
  java/core/src/main/java/com/google/protobuf/BooleanArrayList.java
  java/core/src/main/java/com/google/protobuf/DoubleArrayList.java
  java/core/src/main/java/com/google/protobuf/FloatArrayList.java
  java/core/src/main/java/com/google/protobuf/IntArrayList.java
  java/core/src/main/java/com/google/protobuf/LongArrayList.java
  java/core/src/main/java/com/google/protobuf/ProtobufArrayList.java
Labels: java, release notes: yes

#9402 Merge 3.19.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  kokoro/linux/dockerfile/test/ruby/Dockerfile
  kokoro/release/python/windows/install_python_interpreters.ps1
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/google/protobuf/pyext/unknown_fields.cc
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#9403 Update CHANGES.txt to include recent Java security advisory
  CHANGES.txt
Labels: release notes: no

#9360 Add $(nproc) to make documentation
  src/README.md
Labels: packaging & distribution, release notes: no

#9407 remove Proto2MessageLiteInfoFactory and Proto3MessageLiteInfoFactory
  Makefile.am
  java/core/src/test/java/com/google/protobuf/Proto3MessageLiteInfoFactory.java
  java/lite/src/test/java/com/google/protobuf/Proto2MessageLiteInfoFactory.java
Labels: java-lite, release notes: no

#9408 Adding kotlin bazel tests
  BUILD
  Makefile.am
  WORKSPACE
  java/BUILD
  java/core/BUILD
  java/kotlin-lite/BUILD
  java/kotlin-lite/generate-test-sources-build.xml
  java/kotlin-lite/pom.xml
  java/kotlin-lite/pom_template.xml
  java/kotlin-lite/src/main/kotlin/com/google/protobuf/ExtendableMessageLiteExtensions.kt
  java/kotlin-lite/src/test/kotlin/com/google/protobuf/Proto3LiteTest.kt
  java/kotlin-lite/src/test/proto/com/google/protobuf/evil_names_proto2.proto
  java/kotlin-lite/src/test/proto/com/google/protobuf/evil_names_proto3.proto
  java/kotlin-lite/src/test/proto/com/google/protobuf/multiple_files_proto3.proto
  java/kotlin/BUILD
  java/kotlin/pom.xml
  java/kotlin/pom_template.xml
  java/kotlin/src/test/kotlin/com/google/protobuf/ByteStringsTest.kt
  maven_install.json
  protobuf_deps.bzl
Labels: bazel, release notes: no, kotlin

#9429 Update location of llvm-ar in bazel toolchain
  toolchain/cc_toolchain_config.bzl
Labels: bazel, release notes: no

#9428 Migrate kotlin bazel tests from kt_jvm_test
  java/kotlin-lite/BUILD
  java/kotlin/BUILD
Labels: bazel, release notes: no, kotlin

#9434 Use constexpr for FieldTypeClass
  src/google/protobuf/generated_message_table_driven.h
Labels: c++, cleanup, release notes: no

#9437 link with correct C runtime on MSVC
  cmake/CMakeLists.txt
Labels: c++, windows, cmake, release notes: no

#9436 Updated Ruby to the current version of upb
  CHANGES.txt
  ruby/Rakefile
  ruby/ext/google/protobuf_c/convert.c
  ruby/ext/google/protobuf_c/convert.h
  ruby/ext/google/protobuf_c/defs.c
  ruby/ext/google/protobuf_c/defs.h
  ruby/ext/google/protobuf_c/extconf.rb
  ruby/ext/google/protobuf_c/map.c
  ruby/ext/google/protobuf_c/map.h
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/message.h
  ruby/ext/google/protobuf_c/protobuf.c
  ruby/ext/google/protobuf_c/protobuf.h
  ruby/ext/google/protobuf_c/repeated_field.c
  ruby/ext/google/protobuf_c/repeated_field.h
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
  ruby/ext/google/protobuf_c/wrap_memcpy.c
  ruby/tests/common_tests.rb
  third_party/utf8_range/BUILD
  third_party/utf8_range/LICENSE
  third_party/utf8_range/utf8_range.c
  third_party/utf8_range/utf8_range.h
Labels: ruby, release notes: no

#9435 Make libprotobuf symbols local on OSX (#8346)
  python/setup.py
Labels: release notes: no

#9441 Use proper SPDX license identifier
  Protobuf-C++.podspec
  Protobuf.podspec
  java/bom/pom.xml
  java/pom.xml
  php/ext/google/protobuf/package.xml
  protoc-artifacts/pom.xml
  python/protobuf_distutils/setup.py
  python/setup.py
  ruby/pom.xml
Labels: c++, java, python, release notes: no

#9445 simplify mergeable UI messages
  .github/mergeable.yml
Labels: cleanup, release notes: no

#9422 Disable [[clang::musttail]] attribute on Windows x86
  src/google/protobuf/port_def.inc
Labels: c++, windows, release notes: no

#9448 Update CHANGES.txt for 3.19.4 release
  CHANGES.txt
Labels: release notes: no

#9450 Fixed data loss bug in PHP C extension
  CHANGES.txt
  php/ext/google/protobuf/php-upb.c
  php/tests/GeneratedClassTest.php
  php/tests/proto/test.proto
Labels: php, release notes: no

#9451 Fixed data loss bug in Ruby extension
  CHANGES.txt
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/tests/basic.rb
  ruby/tests/basic_test.proto
Labels: ruby, release notes: no

#9449 Update protobuf version to 3.19.4
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#9426 Add ToProto() method to all C# descriptor classes
  csharp/src/Google.Protobuf.Test/Reflection/DescriptorsTest.cs
  csharp/src/Google.Protobuf/Reflection/EnumDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/EnumValueDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/FileDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MessageDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/MethodDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/OneofDescriptor.cs
  csharp/src/Google.Protobuf/Reflection/ServiceDescriptor.cs
Labels: enhancement, c#, release notes: yes

#9454 Must build project before running benchmarks
  benchmarks/README.md
Labels: java, release notes: no

#9452 Merge 3.19.x into master
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  js/package.json
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/protobuf.h
  php/tests/GeneratedClassTest.php
  php/tests/proto/test.proto
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  python/setup.py
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  ruby/tests/basic.rb
  ruby/tests/basic_test.proto
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#9438 Selectively add source or gen dir to includes.
  protobuf.bzl
Labels: bug, bazel, release notes: no

#9430 Fixes NullReferenceException when accessing FieldDescriptor.IsPacked
  csharp/src/Google.Protobuf/Reflection/FieldDescriptor.cs
Labels: bug, c#, release notes: yes
