Repository protocolbuffers/protobuf, pull requests merged in 2022-09, with the labels that each got.

#10494 [ObjC] Fix the name of the test file.
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_tvOS.xcodeproj/project.pbxproj
  objectivec/Tests/GPBCodedOutputStreamTests.m
Labels: objective-c, release notes: no

#10460 Make abseil a public dependency of libprotobuf
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/libprotoc.cmake
Labels: c++, release notes: no

#10490 Update README.md
  php/README.md
Labels: php, release notes: no

#10503 Add version file
  version.json
Labels: packaging & distribution, release notes: no

#10504 Add version file
  version.json
Labels: packaging & distribution, release notes: no

#10502 Add new version file
  version.json
Labels: packaging & distribution, release notes: no

#10505 Add version file
  version.json
Labels: packaging & distribution, release notes: no

#10506 move portable_strdup into the windows ifdef
  src/google/protobuf/compiler/subprocess.cc
Labels: c++, release notes: no

#10508 Retain existing array in RepeatedField.Clear
  csharp/src/Google.Protobuf.Test/Collections/RepeatedFieldTest.cs
  csharp/src/Google.Protobuf/Collections/RepeatedField.cs
Labels: c#, release notes: yes

#10511 Fix broken python builds
  kokoro/release/python/macos/config.sh
Labels: testing, release notes: no

#10515 Add deprecated python proto alias
  protobuf.bzl
Labels: python, bazel, release notes: no

#10512 Fix python release on macos
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/python/macos/build_artifacts.sh
Labels: python, testing, release notes: no

#10516 Delete performance.md
  docs/performance.md
Labels: documentation, release notes: no

#10464 CMake: Enable projects to set the C++ version
  CMakeLists.txt
Labels: c++, cmake, release notes: yes

#10522 Porting #10512 to 21.x
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/python/macos/build_artifacts.sh
Labels: testing, release notes: no

#10520 Apply Obsolete attribute to deprecated enums and enum values in C# generated code
  csharp/protos/unittest_issues.proto
  csharp/src/Google.Protobuf.Test.TestProtos/UnittestIssues.cs
  csharp/src/Google.Protobuf.Test/DeprecatedMemberTest.cs
  csharp/src/Google.Protobuf.Test/testprotos.pb
  src/google/protobuf/compiler/csharp/csharp_enum.cc
Labels: c#, release notes: yes

#10528 Update version.json
  version.json
Labels: packaging & distribution, release notes: no

#10529 Update version.json
  version.json
Labels: packaging & distribution, release notes: no

#10530 Update version.json
  version.json
Labels: packaging & distribution, release notes: no

#10531 Update version.json
  version.json
Labels: packaging & distribution, release notes: no

#10534 Update version.json with "lts": true
  version.json
Labels: release notes: no

#10533 Update version.json with "lts": true
  version.json
Labels: release notes: no

#10535 Update version.json with "lts": true
  version.json
Labels: release notes: no

#10403 Fix build with Python 3.11
  python/google/protobuf/pyext/descriptor.cc
Labels: python, to-be-fixed, release notes: no

#10540 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  python/google/protobuf/pyext/descriptor_containers.cc
  python/google/protobuf/pyext/descriptor_database.cc
  python/google/protobuf/pyext/descriptor_database.h
  python/google/protobuf/pyext/descriptor_pool.cc
  python/google/protobuf/pyext/extension_dict.cc
  python/google/protobuf/pyext/map_container.cc
  python/google/protobuf/pyext/message.cc
  python/google/protobuf/pyext/message_factory.cc
  python/google/protobuf/pyext/repeated_scalar_container.cc
  src/google/protobuf/compiler/cpp/helpers.h
  src/google/protobuf/io/printer.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/text_format.cc
Labels: release notes: no, sync

#10519 Update docs for MessageToJson indent parameter
  python/google/protobuf/json_format.py
Labels: json, documentation, release notes: no

#10493 Move note to the top
  src/google/protobuf/descriptor.proto
Labels: documentation, release notes: no

#10488 Update conformance/README.md for jruby
  conformance/README.md
Labels: documentation, conformance tests, release notes: no

#10542 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.inc
Labels: c++, release notes: no

#10543 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.inc
Labels: c++, release notes: no

#10545 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.inc
Labels: c++, release notes: no

#10544 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.inc
Labels: c++, release notes: no

#10547 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.cc
Labels: c++, release notes: no

#10553 3.18.x 202209131833
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: release notes: no

#10548 Merge version updates
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: packaging & distribution, release notes: no

#10551 3.19.x 202209131125
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: packaging & distribution, release notes: no

#10550 3.20.x 202209131133
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: release notes: no

#10556 Fix Kokoro tests to work on Monterey machines
  benchmarks/Makefile.am
  kokoro/macos/objectivec_cocoapods_integration/build.sh
  kokoro/macos/prepare_build_macos_rc
  kokoro/release/ruby/macos/build_artifacts.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  objectivec/DevTools/full_mac_build.sh
  objectivec/Tests/CocoaPods/run_tests.sh
  tests.sh
Labels: ruby, release notes: no

#10557 Update versions for 21.6 release
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: release notes: no

#10570 3.20.x 202209141109
  CHANGES.txt
  php/ext/google/protobuf/package.xml
  version.json
Labels: release notes: no

#10559 Fix PHP release
  composer.json
  php/ext/google/protobuf/package.xml
  php/release.sh
Labels: packaging & distribution, php, release notes: no

#10558 Fix php release script
  composer.json
  php/ext/google/protobuf/package.xml
  php/release.sh
Labels: packaging & distribution, php, release notes: no

#10572 Backport python release improvement
  python/release.sh
Labels: python, packaging & distribution, release notes: no

#10577 Fix stale descriptor files after comment change
  csharp/src/Google.Protobuf/Reflection/Descriptor.cs
  php/src/Google/Protobuf/Internal/MessageOptions.php
Labels: c#, release notes: no

#10575 Backport python release improvement
  python/release.sh
Labels: python, packaging & distribution, release notes: no

#10579 Update version.json to: 21.7-dev
  version.json
Labels: packaging & distribution, release notes: no

#10578 3.19.x 202209141437
  php/ext/google/protobuf/package.xml
  version.json
Labels: release notes: no

#10573 Backport python release improvement
  python/release.sh
Labels: python, packaging & distribution, release notes: no

#10580 3.18.x 202209142234
  php/ext/google/protobuf/package.xml
  version.json
Labels: release notes: no

#10574 Backport python release improvement
  php/release.sh
  python/release.sh
Labels: python, packaging & distribution, release notes: no

#10546 Apply patch
  src/google/protobuf/extension_set_inl.h
  src/google/protobuf/wire_format.cc
  src/google/protobuf/wire_format_lite.h
  src/google/protobuf/wire_format_unittest.inc
Labels: c++, release notes: no

#10576 Use generated WKT code in Bazel builds
  BUILD.bazel
  cmake/install.cmake
  pkg/BUILD.bazel
  src/file_lists.cmake
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
  src/google/protobuf/compiler/csharp/BUILD.bazel
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/php/BUILD.bazel
  src/google/protobuf/compiler/python/BUILD.bazel
  src/google/protobuf/compiler/ruby/BUILD.bazel
Labels: c++, bazel, release notes: no

#10470 json_name and default pseudo-options have source code info consistent with options
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/compiler/parser_unittest.cc
Labels: json, release notes: no

#10587 [ObjC] Clean up includes.
  src/google/protobuf/compiler/objectivec/objectivec_enum.cc
  src/google/protobuf/compiler/objectivec/objectivec_extension.cc
  src/google/protobuf/compiler/objectivec/objectivec_field.cc
  src/google/protobuf/compiler/objectivec/objectivec_file.cc
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_map_field.h
  src/google/protobuf/compiler/objectivec/objectivec_message.cc
  src/google/protobuf/compiler/objectivec/objectivec_message_field.h
  src/google/protobuf/compiler/objectivec/objectivec_oneof.cc
  src/google/protobuf/compiler/objectivec/objectivec_oneof.h
  src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc
Labels: objective-c, release notes: no

#10585 [ObjC] Add helper for IsCreateName for the CF Create Rule.
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers_unittest.cc
Labels: objective-c, release notes: no

#10565 [ObjC] Move generation options out to their own file.
  src/file_lists.cmake
  src/google/protobuf/compiler/objectivec/BUILD.bazel
  src/google/protobuf/compiler/objectivec/objectivec_file.h
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_options.h
Labels: objective-c, release notes: no

#10582 Merge 21.x release branch into main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  kokoro/macos/ruby31/build.sh
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#10555 protoc: fix consistency with parsing very large decimal numbers
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/io/tokenizer.cc
  src/google/protobuf/io/tokenizer.h
Labels: protoc, release notes: yes

#10599 Add "public" modifier to Kotlin generated code
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/map_field_lite.cc
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/message_field_lite.cc
  src/google/protobuf/compiler/java/message_lite.cc
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/primitive_field_lite.cc
  src/google/protobuf/compiler/java/string_field.cc
  src/google/protobuf/compiler/java/string_field_lite.cc
Labels: release notes: yes, kotlin

#10600 Add clang-format for some things are well formatted already.
  src/google/protobuf/compiler/objectivec/objectivec_generator.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
  src/google/protobuf/compiler/objectivec/objectivec_helpers_unittest.cc
Labels: objective-c, release notes: no

#10601 Remove osx-aarch_64
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
Labels: packaging & distribution, release notes: no

#10605 Use local protoc artifacts
  protoc-artifacts/build-zip.sh
Labels: packaging & distribution, release notes: no

#10606 Use local protoc artifacts
  protoc-artifacts/build-zip.sh
Labels: packaging & distribution, release notes: no

#10603 Fix codespell errors
  .github/workflows/codespell.yml
  conformance/conformance_test.h
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
  objectivec/GPBCodedInputStream.h
  python/google/protobuf/internal/message_test.py
  src/google/protobuf/descriptor.h
  src/google/protobuf/text_format.cc
  update_version.py
Labels: release notes: no

#10604 Fix codespell errors
  .github/workflows/codespell.yml
  conformance/conformance_test.h
  csharp/src/Google.Protobuf/Reflection/ExtensionCollection.cs
  objectivec/GPBCodedInputStream.h
  python/google/protobuf/internal/message_test.py
  src/google/protobuf/descriptor.h
  src/google/protobuf/text_format.cc
  update_version.py
Labels: release notes: no

#10607 Use local protoc artifacts
  protoc-artifacts/build-zip.sh
Labels: packaging & distribution, release notes: no

#10592 Auto-generate CMake file lists in GitHub action
  .github/workflows/generated_cmake.yml
  cmake/push_auto_update.sh
Labels: cmake, release notes: no

#10611 Run CMake file auto-generation only on the main protobuf repo
  .github/workflows/generated_cmake.yml
Labels: release notes: no

#10612 Make slight change to ordering in src/file_lists.cmake
  src/file_lists.cmake
Labels: release notes: no

#10614 Fix broken examples build
  examples/.bazelrc
  kokoro/linux/bazel/common.cfg
  kokoro/linux/cmake/build.sh
  kokoro/windows/bazel/build.bat
  kokoro/windows/cmake/build.bat
Labels: testing, bazel, release notes: no

#10589 Adding full build to 32 bit tests
  kokoro/linux/32-bit/test_php.sh
  php/generate_descriptor_protos.sh
  php/generate_test_protos.sh
  src/google/protobuf/compiler/cpp/message_size_unittest.cc
  src/google/protobuf/extension_set_unittest.cc
  src/google/protobuf/io/zero_copy_stream_unittest.cc
  src/google/protobuf/repeated_field_unittest.cc
  src/google/protobuf/util/time_util_test.cc
Labels: release notes: no

#10615 Improve CMake installation tests
  BUILD.bazel
  cmake/conformance.cmake
  cmake/tests.cmake
  kokoro/windows/cmake/build.bat
  kokoro/windows/cmake_install/build.bat
  kokoro/windows/cmake_nmake/build.bat
  kokoro/windows/cmake_shared/build.bat
  pkg/BUILD.bazel
  src/file_lists.cmake
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/cpp/BUILD.bazel
Labels: cmake, installation, release notes: no

#10620 Keep the class forward declaration also.
  objectivec/GPBCodedInputStream.h
  objectivec/GPBMessage.h
Labels: objective-c, release notes: no

#10621 Add reserved extension number for Pigweed
  docs/options.md
Labels: protoc, release notes: no

#10622 [ObjC] Use a real import for GPBExtensionRegistry.
  objectivec/GPBCodedInputStream.h
  objectivec/GPBMessage.h
Labels: objective-c, release notes: no

#10629 Correct the link to example WORKSPACE file
  src/README.md
Labels: documentation, release notes: no

#10586 protoc: validate reserved names are identifiers
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/compiler/parser_unittest.cc
Labels: c++, protoc, release notes: yes

#10581 protoc: validate custom json_name configuration
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
Labels: c++, protoc, release notes: yes

#10635 Unbreak Windows tests
  src/google/protobuf/descriptor.cc
Labels: c++, release notes: no

#10636 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  conformance/BUILD.bazel
  conformance/binary_json_conformance_suite.cc
  conformance/conformance_test.cc
  conformance/conformance_test.h
  conformance/conformance_test_runner.cc
  conformance/text_format_conformance_suite.cc
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/test/proto/com/google/protobuf/map_for_proto2_lite_test.proto
  src/file_lists.cmake
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/arena.cc
  src/google/protobuf/arena_impl.h
  src/google/protobuf/arena_unittest.cc
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/cpp/file.cc
  src/google/protobuf/compiler/cpp/message.cc
  src/google/protobuf/compiler/cpp/service.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/compiler/java/generator.cc
  src/google/protobuf/compiler/java/helpers.cc
  src/google/protobuf/compiler/java/map_field_lite.cc
  src/google/protobuf/compiler/java/message_builder_lite.cc
  src/google/protobuf/compiler/java/message_field_lite.cc
  src/google/protobuf/compiler/java/message_lite.cc
  src/google/protobuf/compiler/java/primitive_field_lite.cc
  src/google/protobuf/compiler/java/string_field_lite.cc
  src/google/protobuf/compiler/python/generator.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/io/BUILD.bazel
  src/google/protobuf/io/printer.cc
  src/google/protobuf/io/printer.h
  src/google/protobuf/io/printer_unittest.cc
  src/google/protobuf/io/tokenizer.cc
  src/google/protobuf/map_field_test.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/stubs/BUILD.bazel
  src/google/protobuf/stubs/stringprintf.cc
  src/google/protobuf/stubs/stringprintf.h
  src/google/protobuf/stubs/stringprintf_unittest.cc
  src/google/protobuf/unittest.proto
  src/google/protobuf/util/internal/proto_writer.h
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectwriter.h
  src/google/protobuf/util/internal/protostream_objectwriter_test.cc
  src/google/protobuf/util/json_util.h
  src/google/protobuf/util/message_differencer.cc
  src/google/protobuf/util/time_util.cc
  src/google/protobuf/util/type_resolver_util.h
  src/google/protobuf/wire_format_lite.cc
Labels: release notes: no, sync

#10650 Remove the pre Xcode 10.2 support.
  objectivec/DevTools/full_mac_build.sh
  objectivec/GPBDescriptor_PackagePrivate.h
  objectivec/GPBDictionary.m
  objectivec/GPBMessage.m
  objectivec/Tests/unittest_objc.proto
Labels: objective-c, release notes: no

#10653 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  cmake/install.cmake
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  python/google/protobuf/text_format.py
  src/google/protobuf/arena.cc
  src/google/protobuf/compiler/cpp/message.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/generated_message_tctable_gen.cc
  src/google/protobuf/generated_message_tctable_gen.h
  src/google/protobuf/generated_message_tctable_impl.h
  src/google/protobuf/generated_message_tctable_lite.cc
Labels: release notes: no, sync

#10649 Add an objc_class_prefix for the proto2 syntax file used in conformance tests
  conformance/conformance_objc.m
  src/google/protobuf/test_messages_proto2.proto
Labels: objective-c, release notes: no

#10651 [ObjC] Move from `#pragma unused()` to `_unused`
  objectivec/GPBCodedOutputStream.m
  objectivec/GPBDescriptor.m
  objectivec/GPBDictionary.m
  objectivec/GPBMessage.m
  objectivec/GPBRootObject.m
  objectivec/GPBUnknownField.m
  objectivec/GPBUnknownFieldSet.m
  objectivec/GPBUtilities.m
  objectivec/Tests/GPBArrayTests.m
  objectivec/Tests/GPBDictionaryTests+Bool.m
  objectivec/Tests/GPBDictionaryTests+Int32.m
  objectivec/Tests/GPBDictionaryTests+Int64.m
  objectivec/Tests/GPBDictionaryTests+String.m
  objectivec/Tests/GPBDictionaryTests+UInt32.m
  objectivec/Tests/GPBDictionaryTests+UInt64.m
  objectivec/Tests/GPBDictionaryTests.pddm
  objectivec/Tests/GPBMessageTests+Runtime.m
  objectivec/Tests/GPBMessageTests.m
Labels: objective-c, release notes: no

#10652 [ObjC] Raise the min OS versions (and required Xcode)
  Protobuf.podspec
  objectivec/DevTools/full_mac_build.sh
  objectivec/ProtocolBuffers_OSX.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_iOS.xcodeproj/project.pbxproj
  objectivec/ProtocolBuffers_tvOS.xcodeproj/project.pbxproj
  objectivec/README.md
Labels: objective-c, release notes: yes

#10658 Revert "Merge pull request #10470 from jhump/jh/source-code-info-pseudo options"
  src/google/protobuf/compiler/parser.cc
  src/google/protobuf/compiler/parser.h
  src/google/protobuf/compiler/parser_unittest.cc
Labels: release notes: no

#10656 Remove NMake support
  cmake/README.md
  kokoro/windows/cmake_nmake/build.bat
  kokoro/windows/cmake_nmake/common.cfg
  kokoro/windows/cmake_nmake/continuous.cfg
  kokoro/windows/cmake_nmake/presubmit.cfg
Labels: windows, testing, release notes: no

#10657 Revert "Merge pull request #10581 from jhump/jh/custom-json-name-validation"
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor_unittest.cc
Labels: release notes: no

#10616 Add missing `public` modifier to Kotlin generated code
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field_lite.cc
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_lite.cc
Labels: release notes: yes, kotlin

#10628 Remove deprecated protoc-artifacts directory
  java/protoc/README.md
  java/protoc/pom.xml
  kokoro/release/collect_all_artifacts.sh
  kokoro/release/protoc/build-protoc.sh
  kokoro/release/protoc/linux/build.sh
  protoc-artifacts/README.md
  protoc-artifacts/build-zip.sh
  protoc-artifacts/pom.xml
  protoc-artifacts/scl-enable-devtoolset.sh
Labels: release notes: no

#10610 No longer define no_threadlocal on OpenBSD
  src/google/protobuf/stubs/platform_macros.h
Labels: c++, release notes: yes

#10647 Fix MSVC C4244 narrowing conversion warning on 64-bit Windows.
  src/google/protobuf/repeated_field.h
  src/google/protobuf/repeated_ptr_field.h
Labels: c++, windows, release notes: no

#10660 gracefully handle weird placement of linebreaks around comments
  src/google/protobuf/io/tokenizer.cc
  src/google/protobuf/io/tokenizer_unittest.cc
Labels: protoc, release notes: yes

#10662 Correct the link name for BUILD.bazel file
  examples/README.md
Labels: release notes: no

#10454 Auto capitalize enums name in Ruby
  ruby/compatibility_tests/v3.0.0/tests/basic.rb
  ruby/ext/google/protobuf_c/message.c
  ruby/src/main/java/com/google/protobuf/jruby/RubyEnumDescriptor.java
  ruby/tests/basic_test.proto
  ruby/tests/basic_test_proto2.proto
  ruby/tests/common_tests.rb
  ruby/tests/generated_code.proto
  ruby/tests/generated_code_proto2.proto
  ruby/tests/repeated_field_test.rb
Labels: ruby, release notes: yes

#10664 Refactoring Java parsing (22.x)
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/AbstractMessage.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchema.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaFull.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaLite.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/MessageLiteToString.java
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/MessageSetSchema.java
  java/core/src/main/java/com/google/protobuf/NewInstanceSchemaLite.java
  java/core/src/main/java/com/google/protobuf/Reader.java
  java/core/src/main/java/com/google/protobuf/SchemaUtil.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLite.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLiteSchema.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field.h
  src/google/protobuf/compiler/java/field.cc
  src/google/protobuf/compiler/java/field.h
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/map_field.h
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_builder.cc
  src/google/protobuf/compiler/java/message_builder.h
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/message_field.h
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/primitive_field.h
  src/google/protobuf/compiler/java/string_field.cc
  src/google/protobuf/compiler/java/string_field.h
Labels: java, java-lite, release notes: no, kotlin, jruby

#10665 Refactoring Java parsing (21.x)
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/AbstractMessage.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchema.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaFull.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaLite.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/MessageLiteToString.java
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/MessageSetSchema.java
  java/core/src/main/java/com/google/protobuf/NewInstanceSchemaLite.java
  java/core/src/main/java/com/google/protobuf/Reader.java
  java/core/src/main/java/com/google/protobuf/SchemaUtil.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLite.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLiteSchema.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/enum_field.h
  src/google/protobuf/compiler/java/field.cc
  src/google/protobuf/compiler/java/field.h
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/map_field.h
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_builder.cc
  src/google/protobuf/compiler/java/message_builder.h
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/message_field.h
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/primitive_field.h
  src/google/protobuf/compiler/java/string_field.cc
  src/google/protobuf/compiler/java/string_field.h
Labels: java, java-lite, release notes: no, kotlin, jruby

#10666 Refactoring Java parsing (3.20.x)
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/AbstractMessage.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchema.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaFull.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaLite.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/MessageLiteToString.java
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/MessageSetSchema.java
  java/core/src/main/java/com/google/protobuf/NewInstanceSchemaLite.java
  java/core/src/main/java/com/google/protobuf/Reader.java
  java/core/src/main/java/com/google/protobuf/SchemaUtil.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLite.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLiteSchema.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_enum_field.h
  src/google/protobuf/compiler/java/java_field.cc
  src/google/protobuf/compiler/java/java_field.h
  src/google/protobuf/compiler/java/java_map_field.cc
  src/google/protobuf/compiler/java/java_map_field.h
  src/google/protobuf/compiler/java/java_message.cc
  src/google/protobuf/compiler/java/java_message_builder.cc
  src/google/protobuf/compiler/java/java_message_builder.h
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_message_field.h
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field.h
  src/google/protobuf/compiler/java/java_string_field.cc
  src/google/protobuf/compiler/java/java_string_field.h
Labels: java, java-lite, release notes: no, kotlin, jruby

#10672 Clean up TextFormat parser
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
Labels: java, java-lite, release notes: no, kotlin, jruby

#10674 Clean up TextFormat
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
Labels: java, java-lite, release notes: no, kotlin, jruby

#10673 Clean up TextFormat parser
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
Labels: java, java-lite, release notes: no, kotlin, jruby

#10668 Refactoring Java parsing (3.16.x)
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/AbstractMessage.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchema.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaFull.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaLite.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/MessageLiteToString.java
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/MessageSetSchema.java
  java/core/src/main/java/com/google/protobuf/NewInstanceSchemaLite.java
  java/core/src/main/java/com/google/protobuf/Reader.java
  java/core/src/main/java/com/google/protobuf/SchemaUtil.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLite.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLiteSchema.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_enum_field.h
  src/google/protobuf/compiler/java/java_field.cc
  src/google/protobuf/compiler/java/java_field.h
  src/google/protobuf/compiler/java/java_map_field.cc
  src/google/protobuf/compiler/java/java_map_field.h
  src/google/protobuf/compiler/java/java_message.cc
  src/google/protobuf/compiler/java/java_message_builder.cc
  src/google/protobuf/compiler/java/java_message_builder.h
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_message_field.h
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field.h
  src/google/protobuf/compiler/java/java_string_field.cc
  src/google/protobuf/compiler/java/java_string_field.h
Labels: java, java-lite, release notes: no, jruby

#10667 Refactoring Java parsing (3.19.x)
  CHANGES.txt
  java/core/src/main/java/com/google/protobuf/AbstractMessage.java
  java/core/src/main/java/com/google/protobuf/ArrayDecoders.java
  java/core/src/main/java/com/google/protobuf/BinaryReader.java
  java/core/src/main/java/com/google/protobuf/CodedInputStreamReader.java
  java/core/src/main/java/com/google/protobuf/DescriptorMessageInfoFactory.java
  java/core/src/main/java/com/google/protobuf/DynamicMessage.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchema.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaFull.java
  java/core/src/main/java/com/google/protobuf/ExtensionSchemaLite.java
  java/core/src/main/java/com/google/protobuf/FieldSet.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageLite.java
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/main/java/com/google/protobuf/MessageLiteToString.java
  java/core/src/main/java/com/google/protobuf/MessageReflection.java
  java/core/src/main/java/com/google/protobuf/MessageSchema.java
  java/core/src/main/java/com/google/protobuf/MessageSetSchema.java
  java/core/src/main/java/com/google/protobuf/NewInstanceSchemaLite.java
  java/core/src/main/java/com/google/protobuf/Reader.java
  java/core/src/main/java/com/google/protobuf/SchemaUtil.java
  java/core/src/main/java/com/google/protobuf/TextFormat.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLite.java
  java/core/src/main/java/com/google/protobuf/UnknownFieldSetLiteSchema.java
  java/lite/src/test/java/com/google/protobuf/LiteTest.java
  java/util/src/main/java/com/google/protobuf/util/FieldMaskTree.java
  src/google/protobuf/compiler/java/java_enum_field.cc
  src/google/protobuf/compiler/java/java_enum_field.h
  src/google/protobuf/compiler/java/java_field.cc
  src/google/protobuf/compiler/java/java_field.h
  src/google/protobuf/compiler/java/java_map_field.cc
  src/google/protobuf/compiler/java/java_map_field.h
  src/google/protobuf/compiler/java/java_message.cc
  src/google/protobuf/compiler/java/java_message_builder.cc
  src/google/protobuf/compiler/java/java_message_builder.h
  src/google/protobuf/compiler/java/java_message_field.cc
  src/google/protobuf/compiler/java/java_message_field.h
  src/google/protobuf/compiler/java/java_primitive_field.cc
  src/google/protobuf/compiler/java/java_primitive_field.h
  src/google/protobuf/compiler/java/java_string_field.cc
  src/google/protobuf/compiler/java/java_string_field.h
Labels: java, java-lite, release notes: no, kotlin, jruby

#10675 Updating version.json and repo version numbers to: 16.3
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: packaging & distribution, release notes: no

#10590 doc: Add documentation for CMake `protobuf_generate`
  docs/cmake_protobuf_generate.md
Labels: documentation, release notes: no

#10676 Update versions and upb commit
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_deps.bzl
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: release notes: no

#10677 3.19.x 202209291050
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: packaging & distribution, release notes: no

#10678 3.20.x 202209291741
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: packaging & distribution, release notes: no

#10680 3.19.x 202209291514
  version.json
Labels: packaging & distribution, release notes: no

#10681 3.20.x 202209292242
  php/ext/google/protobuf/package.xml
  version.json
Labels: packaging & distribution, release notes: no

#10684 Add a staleness test for src/file_lists.cmake
  pkg/build_systems.bzl
  protobuf_deps.bzl
  src/BUILD.bazel
Labels: cmake, release notes: no

#10687 Add a Kokoro release job for running staleness tests
  kokoro/linux/staleness/release.cfg
Labels: release notes: no

#10682 Update version.json to: 16.4-dev
  version.json
Labels: packaging & distribution, release notes: no

#10561 fix serialization warnings in generated code when compiling with Java 18 and above
  src/google/protobuf/compiler/java/enum_field.cc
  src/google/protobuf/compiler/java/map_field.cc
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message_field.cc
  src/google/protobuf/compiler/java/primitive_field.cc
  src/google/protobuf/compiler/java/string_field.cc
Labels: java, release notes: yes

#10688 Merge release branch 21.x into main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: release notes: no

#10496 Added staleness test to keep ruby-upb.{c,h} amalgamation files in sync with upb repo
  conformance/failure_list_ruby.txt
  protobuf_deps.bzl
  ruby/BUILD.bazel
  ruby/ext/google/protobuf_c/message.c
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
  upb.patch
Labels: ruby, release notes: no
