Repository protocolbuffers/protobuf, pull requests merged in 2022-06, with the labels that each got.

#10073 [Bazel] Add a doc explaining our C++ build systems and distribution archives.
  docs/cpp_build_systems.md
Labels: bazel, release notes: no

#10094 use char to find instead of string
  src/google/protobuf/compiler/csharp/csharp_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_enum.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/php/php_generator.cc
  src/google/protobuf/compiler/ruby/ruby_generator.cc
Labels: c++, release notes: no

#10092 [Kokoro] Switch normal macos build to use cmake.
  kokoro/macos/cpp/build.sh
Labels: release notes: no

#10101 remove const from function return type if returning const value
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/util/internal/protostream_objectsource.cc
  src/google/protobuf/util/internal/protostream_objectsource.h
  src/google/protobuf/util/internal/utility.cc
  src/google/protobuf/util/internal/utility.h
Labels: c++, release notes: no

#10055 Delete obsolete python release setup
  kokoro/release/python/linux/build_artifacts.sh
  kokoro/release/python/linux/config.sh
  kokoro/release/python/linux/continuous.cfg
  kokoro/release/python/linux/presubmit.cfg
  kokoro/release/python/linux/release.cfg
  kokoro/release/python/macos/build_artifacts.sh
  kokoro/release/python/macos/config.sh
  kokoro/release/python/macos/continuous.cfg
  kokoro/release/python/macos/presubmit.cfg
  kokoro/release/python/macos/release.cfg
  kokoro/release/python/windows/build_artifacts.bat
  kokoro/release/python/windows/build_single_artifact.bat
  kokoro/release/python/windows/continuous.cfg
  kokoro/release/python/windows/install_python_interpreters.ps1
  kokoro/release/python/windows/presubmit.cfg
  kokoro/release/python/windows/release.cfg
Labels: python, autotools, release notes: no

#10107 Update inlined_string_field.h
  src/google/protobuf/inlined_string_field.h
Labels: c++, release notes: no

#10112 Fix usage of sprintf in strutil.cc
  src/google/protobuf/stubs/strutil.cc
Labels: c++, release notes: no

#10117 Ignore configure~
  .gitignore
Labels: autotools, release notes: no

#10123 add missing quotes in BUILD.bazel's comments
  BUILD.bazel
Labels: release notes: no

#10125 Correct file extention of README
  examples/AddPerson.java
  examples/ListPeople.java
  examples/Makefile
  examples/add_person.cc
  examples/add_person.py
  examples/addressbook.proto
  examples/list_people.cc
  examples/list_people.py
Labels: release notes: no

#10128 Length check accommodates NUL emitted by sprintf
  src/google/protobuf/stubs/strutil.cc
Labels: c++, release notes: no

#10120 Remove unused Offset function
  src/google/protobuf/generated_message_tctable_lite.cc
Labels: c++, release notes: no

#10102 Exposed more functions in FieldDescriptor and OneofDescriptor.
  php/src/Google/Protobuf/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/OneofDescriptor.php
  php/src/Google/Protobuf/OneofDescriptor.php
Labels: php, release notes: yes

#10135 Add package_as_prefix_forced_prefix generation option.
  objectivec/README.md
  src/google/protobuf/compiler/objectivec/objectivec_generator.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.cc
  src/google/protobuf/compiler/objectivec/objectivec_helpers.h
Labels: objective-c, release notes: no

#10139 Fix up missing include files for unordered_set/map
  src/google/protobuf/compiler/objectivec/objectivec_file.h
Labels: objective-c, release notes: no

#10141 Removing deleted files from dist rule
  Makefile.am
Labels: c#, packaging & distribution, release notes: no

#10137 Add Ballerina gRPC `ballerina_package` file option to global extension registry
  docs/options.md
Labels: release notes: no

#10148 Integrate from Piper for C++, Java, and Python
  CHANGES.txt
  conformance/conformance_cpp.cc
  java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java
  java/core/src/test/java/com/google/protobuf/DescriptorsTest.java
  java/core/src/test/java/com/google/protobuf/GeneratedMessageTest.java
  src/Makefile.am
  src/file_lists.cmake
  src/google/protobuf/arena_impl.h
  src/google/protobuf/arenastring.cc
  src/google/protobuf/arenastring.h
  src/google/protobuf/arenaz_sampler.cc
  src/google/protobuf/arenaz_sampler.h
  src/google/protobuf/arenaz_sampler_test.cc
  src/google/protobuf/compiler/cpp/enum_field.cc
  src/google/protobuf/compiler/cpp/message.cc
  src/google/protobuf/compiler/cpp/parse_function_generator.cc
  src/google/protobuf/compiler/cpp/primitive_field.cc
  src/google/protobuf/compiler/java/BUILD.bazel
  src/google/protobuf/compiler/java/message.cc
  src/google/protobuf/compiler/java/message.h
  src/google/protobuf/compiler/java/message_serialization.cc
  src/google/protobuf/compiler/java/message_serialization.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/generated_message_tctable_lite.cc
  src/google/protobuf/generated_message_util.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
  src/google/protobuf/struct.pb.cc
  src/google/protobuf/stubs/status.cc
  src/google/protobuf/stubs/status.h
  src/google/protobuf/util/internal/proto_writer.cc
  src/google/protobuf/util/json_util_test.cc
Labels: release notes: no

#10140 Update versions for publish python script
  kokoro/docs/publish-python.sh
Labels: release notes: no

#10160 Update options.md
  docs/options.md
Labels: documentation, release notes: no

#10090 Allow for CMAKE_INSTALL_LIBDIR to be absolute
  cmake/install.cmake
Labels: c++, cmake, release notes: yes

#10168 Cherry pick arenastring and PHP API
  php/src/Google/Protobuf/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/FieldDescriptor.php
  php/src/Google/Protobuf/Internal/OneofDescriptor.php
  php/src/Google/Protobuf/OneofDescriptor.php
  src/google/protobuf/arena_impl.h
  src/google/protobuf/arenastring.cc
  src/google/protobuf/arenastring.h
Labels: release notes: no

#10169 Adjust editor config to reflect cast conventions in C# libraries
  csharp/.editorconfig
Labels: c#, release notes: no

#10181 Generate CHANGES.txt
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: release notes: no, v21.2

#10182 Fix python link to install packages
  python/README.md
Labels: documentation, release notes: no

#10118 Make //:protobuf_python and //:well_known_types_py_pb2 public.
  BUILD.bazel
Labels: python, bazel, release notes: yes

#9998 Raise KeyError in Python ServiceDescriptor.FindMethodByName (#9592)
  python/google/protobuf/descriptor.py
  python/google/protobuf/internal/descriptor_test.py
Labels: python, release notes: yes

#10183 merge 21.x into main
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/package.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: v21.2

#9855 Rewrite for clarity
  docs/jvm_aot.md
Labels: java, release notes: no

#10195 fix C# minimum lang version to 10.0
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
Labels: c#, release notes: no

#10190 Change phpunit version to fix error
  php/composer.json
Labels: php, release notes: no

#10197 Disabling broken mac php tests
  kokoro/macos/php7.0_mac/build.sh
  kokoro/macos/php7.3_mac/build.sh
Labels: php, release notes: no

#10187 Add protoc pom file to java directory
  Makefile.am
  java/BUILD.bazel
  java/protoc/pom.xml
Labels: java, bazel, release notes: no
