Repository protocolbuffers/protobuf, pull requests merged in 2022-12, with the labels that each got.

#11118 Add "public" modifier to Kotlin generated code
  src/google/protobuf/compiler/java/map_field.cc
Labels: release notes: yes, kotlin

#11138 Main 202212021626
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: mergeable:force-allow

#11258 Updated release branch to latest upb.
  php/ext/google/protobuf/php-upb.c
  protobuf_deps.bzl
  ruby/ext/google/protobuf_c/ruby-upb.c
Labels: release notes: no, mergeable:force-allow

#11281 Updating version.json and repo version numbers to: 21.12
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  configure.ac
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  protoc-artifacts/pom.xml
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/Makefile.am
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: mergeable:force-allow

#11283 fix kokoro git config
  kokoro/release/collect_all_artifacts.sh
Labels: bug, mergeable:force-allow

#11282 fix kokoro git config
  kokoro/release/collect_all_artifacts.sh
Labels: bug, mergeable:force-allow

#11284 fix kokoro git config
  kokoro/release/collect_all_artifacts.sh
Labels: bug, mergeable:force-allow

#11286 fix kokoro git config
  kokoro/release/collect_all_artifacts.sh
Labels: bug, mergeable:force-allow

#11315 Point python setup to zlib after mac update
  kokoro/macos/prepare_build_macos_rc
Labels: mac, testing, release notes: no

#11316 Point python setup to zlib after mac update
  kokoro/macos/prepare_build_macos_rc
Labels: mac, testing, release notes: no

#11317 Point python setup to zlib after mac update
  kokoro/macos/prepare_build_macos_rc
Labels: mac, testing, release notes: no

#11320 Update iOS simulator to a supported version
  objectivec/Tests/CocoaPods/run_tests.sh
Labels: mergeable:force-allow

#10843 GitHub Workflows security hardening
  .github/workflows/codespell.yml
  .github/workflows/generate_files.yml
  .github/workflows/objc_cocoapods.yml
  .github/workflows/php-ext.yml
  .github/workflows/update_php_repo.yml
Labels: tooling, release notes: no

#11322 Update iOS version
  objectivec/Tests/CocoaPods/run_tests.sh
Labels: mergeable:force-allow

#11340 Main 202212161220
  CHANGES.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  csharp/src/Google.Protobuf/Reflection/Descriptor.pb.cs
  csharp/src/Google.Protobuf/WellKnownTypes/Any.pb.cs
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  php/src/GPBMetadata/Google/Protobuf/Internal/Descriptor.php
  php/src/Google/Protobuf/Any.php
  php/src/Google/Protobuf/Internal/EnumOptions.php
  php/src/Google/Protobuf/Internal/GeneratedCodeInfo/Annotation.php
  php/src/Google/Protobuf/Internal/MessageOptions.php
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: mergeable:force-allow

#11412 Pin ruby bundler
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/travis-test.sh
Labels: ruby, release notes: no, mergeable:force-allow

#11418 Pin to bundler with ruby 2.5 support
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/travis-test.sh
Labels: ruby, release notes: no, mergeable:force-allow

#11419 Pin bundler for ruby 2.5 support
  kokoro/release/ruby/macos/ruby/ruby_build_environment.sh
  ruby/travis-test.sh
Labels: mergeable:force-allow
