Repository protocolbuffers/protobuf, pull requests merged in 2023-07, with the labels that each got.

#13215 Update upb dep to the latest 23.x commit
  .github/workflows/test_java.yml
  objectivec/DevTools/pddm_tests.py
  protobuf_deps.bzl
Labels: dependencies

#13288 Explicitly delete the destructor for the internal `Rep` structure.
  src/google/protobuf/repeated_field.h
Labels: back-port

#13309 Put a 4k limit on preallocation to prevent OOM from malformed inputs.
  src/google/protobuf/compiler/java/primitive_field.cc
Labels: mergeable:force-allow

#13312 Backport java linkage monitor fix
  java/BUILD.bazel
  java/linkage_monitor.sh
  java/test/linkage-monitor-check-bom/pom.xml
Labels: back-port

#13316 Backport editions plugin improvements
  php/ext/google/protobuf/php-upb.c
  php/ext/google/protobuf/php-upb.h
  ruby/ext/google/protobuf_c/ruby-upb.c
  ruby/ext/google/protobuf_c/ruby-upb.h
  src/file_lists.cmake
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/code_generator.h
  src/google/protobuf/compiler/code_generator_unittest.cc
  src/google/protobuf/compiler/command_line_interface.cc
  src/google/protobuf/compiler/command_line_interface.h
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/cpp/bootstrap_unittest.cc
  src/google/protobuf/compiler/cpp/generator.h
  src/google/protobuf/compiler/cpp/generator_unittest.cc
  src/google/protobuf/compiler/cpp/unittest.cc
  src/google/protobuf/compiler/cpp/unittest.inc
  src/google/protobuf/compiler/fake_plugin.cc
  src/google/protobuf/compiler/java/message_serialization_unittest.cc
  src/google/protobuf/compiler/mock_code_generator.cc
  src/google/protobuf/compiler/mock_code_generator.h
  src/google/protobuf/compiler/parser_unittest.cc
  src/google/protobuf/compiler/plugin.pb.cc
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/compiler/plugin.proto
  src/google/protobuf/compiler/retention.cc
  src/google/protobuf/compiler/retention.h
  src/google/protobuf/compiler/retention_unittest.cc
  src/google/protobuf/descriptor.cc
  src/google/protobuf/descriptor.h
  src/google/protobuf/descriptor.pb.cc
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/descriptor.proto
  src/google/protobuf/descriptor_unittest.cc
  src/google/protobuf/descriptor_visitor.h
  src/google/protobuf/descriptor_visitor_test.cc
  src/google/protobuf/extension_set_unittest.cc
  src/google/protobuf/feature_resolver.cc
  src/google/protobuf/io/zero_copy_stream_unittest.cc
  src/google/protobuf/json/json_test.cc
  src/google/protobuf/map_test.inc
  src/google/protobuf/message_unittest.inc
  src/google/protobuf/test_util2.h
  src/google/protobuf/text_format_unittest.cc
  src/google/protobuf/unittest_features.proto
Labels: back-port

#13417 Backport dropped support of Bazel 5 to 24.x
  .github/workflows/test_cpp.yml
  .github/workflows/test_csharp.yml
  .github/workflows/test_java.yml
  .github/workflows/test_objectivec.yml
  .github/workflows/test_php.yml
  .github/workflows/test_php_ext.yml
  .github/workflows/test_python.yml
  .github/workflows/test_ruby.yml
  .github/workflows/test_rust.yml
  build_defs/internal_shell.bzl
  objectivec/BUILD.bazel
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/test_plugin_injection.bzl
Labels: bazel, dependencies

#13418 Backport dropped support of Bazel 5 to 24.x
  .github/workflows/test_cpp.yml
  .github/workflows/test_csharp.yml
  .github/workflows/test_java.yml
  .github/workflows/test_objectivec.yml
  .github/workflows/test_php.yml
  .github/workflows/test_php_ext.yml
  .github/workflows/test_python.yml
  .github/workflows/test_ruby.yml
  .github/workflows/test_rust.yml
  build_defs/internal_shell.bzl
  objectivec/BUILD.bazel
  src/google/protobuf/BUILD.bazel
  src/google/protobuf/compiler/BUILD.bazel
  src/google/protobuf/compiler/command_line_interface_unittest.cc
  src/google/protobuf/compiler/test_plugin_injection.bzl
Labels: bazel, dependencies
