Repository protocolbuffers/protobuf, pull requests merged in 2023-03, with the labels that each got.

#12113 Fix toolchain resolution for osx x86_64
  build_defs/BUILD.bazel
Labels: :a: safe for tests

#12152 Add release tests for statically linked binaries
  .github/workflows/test_cpp.yml
  .github/workflows/test_java.yml
  .github/workflows/test_python.yml
  BUILD.bazel
  CMakeLists.txt
  build_defs/BUILD.bazel
  cmake/protobuf-generate.cmake
Labels: :a: safe for tests

#12168 Update version numbers for 22.1 release
  CMakeLists.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/protoc/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: :a: safe for tests

#12276 Remove erroneous dependencies @com_google_googletest//:gtest and @com…
  src/google/protobuf/json/BUILD.bazel
Labels: bazel

#12301 Only include utf8_range if it hasn't been included already
  cmake/libprotobuf-lite.cmake
  cmake/libprotobuf.cmake
  cmake/utf8_range.cmake
Labels: cmake
