Repository protocolbuffers/protobuf, pull requests merged in 2023-02, with the labels that each got.

#11741 Cherrypick: Fix update php repo GHA.
  .github/workflows/update_php_repo.yml
Labels: mergeable:force-allow

#11909 Delete codeowners file in release branch
  .github/CODEOWNERS
Labels: :a: safe for tests

#11944 Backport GHA fixes and optimizations to 22.x
  .github/BUILD.bazel
  .github/actions/bazel-docker/action.yml
  .github/actions/bazel/action.yml
  .github/actions/ccache/action.yml
  .github/actions/internal/ccache-setup-windows/action.yml
  .github/workflows/README.md
  .github/workflows/forked_pr_workflow_check.yml
  .github/workflows/staleness_check.yml
  .github/workflows/staleness_refresh.yml
  .github/workflows/test_cpp.yml
  .github/workflows/test_objectivec.yml
  .github/workflows/test_runner.yml
  CMakeLists.txt
  ci/README.md
  rust/BUILD.bazel
Labels: release notes: no, back-port

#11975 Merge 22.x back to main after 22.0 release
  .github/workflows/test_runner.yml
  CMakeLists.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/protoc/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
Labels: :a: safe for tests

#11979 Backport GHA improvements to 22.x
  .github/actions/bazel/action.yml
  .github/actions/internal/bazel-setup/action.yml
  .github/actions/internal/ccache-setup-windows/action.yml
  .github/workflows/codespell.yml
  push_auto_update.sh
Labels: testing, release notes: no

#12030 Add OSGi headers to pom files.
  java/core/pom_template.xml
  java/lite/pom_template.xml
  java/util/pom_template.xml
Labels: packaging & distribution, 22.x
