Repository protocolbuffers/protobuf, pull requests merged in 2023-01, with the labels that each got.

#11494 Add explicit abort() at the end of AlignFail (Backports #10188)
  src/google/protobuf/generated_message_tctable_impl.h
Labels: c++

#11636 Clean up deprecation message for WKT
  BUILD.bazel
Labels: bazel, release notes: no

#11657 Adding targets for bootstrap proto srcs
  BUILD.bazel
Labels: bazel, release notes: no

#11728 Cherrypick Bazel 4 test fix
  kokoro/linux/bazel4/common.cfg
Labels: mergeable:force-allow

#11737 Downgrade ruby major version
  version.json
Labels: mergeable:force-allow
