Repository protocolbuffers/protobuf, pull requests merged in 2023-05, with the labels that each got.

#12695 Backport increased C++ test coverage + fixes
  .github/workflows/test_cpp.yml
  cmake/install.cmake
  src/google/protobuf/io/printer_death_test.cc
  src/google/protobuf/port_def.inc
  src/google/protobuf/repeated_field.h
Labels: back-port

#12694 Backport increased C++ test coverage + fixes
  .github/workflows/test_cpp.yml
  cmake/install.cmake
  src/google/protobuf/io/printer_death_test.cc
  src/google/protobuf/port.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/repeated_field.h
Labels: back-port

#12702 Cherry pick various portability fixes from mainline
  cmake/install.cmake
  cmake/protobuf-lite.pc.cmake
  cmake/protobuf.pc.cmake
  src/google/protobuf/arena_align.h
  src/google/protobuf/repeated_field.h
Labels: back-port

#12703 Cherry pick various portability fixes from mainline
  cmake/install.cmake
  cmake/protobuf-lite.pc.cmake
  cmake/protobuf.pc.cmake
  src/google/protobuf/arena_align.h
  src/google/protobuf/repeated_field.h
Labels: back-port

#12743 Backport GCC tests+fixes
  .github/workflows/test_cpp.yml
  src/google/protobuf/port_def.inc
Labels: back-port

#12742 Backport GCC tests+fixes
  .github/workflows/test_cpp.yml
Labels: back-port

#12747 Update version numbers for 22.5 release
  CMakeLists.txt
  Protobuf-C++.podspec
  Protobuf.podspec
  csharp/Google.Protobuf.Tools.nuspec
  csharp/src/Google.Protobuf/Google.Protobuf.csproj
  java/README.md
  java/bom/pom.xml
  java/core/pom.xml
  java/kotlin-lite/pom.xml
  java/kotlin/pom.xml
  java/lite.md
  java/lite/pom.xml
  java/pom.xml
  java/protoc/pom.xml
  java/util/pom.xml
  php/ext/google/protobuf/protobuf.h
  protobuf_version.bzl
  python/google/protobuf/__init__.py
  ruby/google-protobuf.gemspec
  ruby/pom.xml
  src/google/protobuf/any.pb.h
  src/google/protobuf/api.pb.h
  src/google/protobuf/compiler/plugin.pb.h
  src/google/protobuf/descriptor.pb.h
  src/google/protobuf/duration.pb.h
  src/google/protobuf/empty.pb.h
  src/google/protobuf/field_mask.pb.h
  src/google/protobuf/port_def.inc
  src/google/protobuf/source_context.pb.h
  src/google/protobuf/struct.pb.h
  src/google/protobuf/stubs/common.h
  src/google/protobuf/timestamp.pb.h
  src/google/protobuf/type.pb.h
  src/google/protobuf/wrappers.pb.h
  version.json
Labels: :a: safe for tests

#12775 fix: avoid warnings with MSVC (#12762)
  src/google/protobuf/has_bits.h
  src/google/protobuf/string_block.h
Labels: back-port, 23.x

#12823 Backport fixes for 22.x
  .github/workflows/test_cpp.yml
  src/google/protobuf/port_def.inc
  src/google/protobuf/port_undef.inc
Labels: back-port

#12906 Automated rollback of commit 4d76f12a82bc53cc2d846e65dd8c4bce6c1d4645.
  objectivec/GPBAny.pbobjc.m
  objectivec/GPBApi.pbobjc.m
  objectivec/GPBDuration.pbobjc.m
  objectivec/GPBEmpty.pbobjc.m
  objectivec/GPBFieldMask.pbobjc.m
  objectivec/GPBSourceContext.pbobjc.m
  objectivec/GPBStruct.pbobjc.m
  objectivec/GPBTimestamp.pbobjc.m
  objectivec/GPBType.pbobjc.m
  objectivec/GPBWrappers.pbobjc.m
  src/google/protobuf/compiler/java/message_builder.cc
Labels: back-port

#12907 Update upb dependency
  protobuf_deps.bzl
Labels: dependencies
