Repository protocolbuffers/protobuf, pull requests merged in 2024-12, with the labels that each got.

#19701 Update artifact actions to v4
  .github/workflows/scorecard.yml
  .github/workflows/test_php_ext.yml
  .github/workflows/test_upb.yml
Labels: :a: safe for tests

#19703 Update artifact actions to v4
  .github/workflows/scorecard.yml
  .github/workflows/test_php_ext.yml
  .github/workflows/test_upb.yml
Labels: :a: safe for tests, back-port

#19773 Fix cmake installation location of java and go features
  cmake/install.cmake
  go/BUILD.bazel
  go/google/protobuf/go_features.proto
  pkg/BUILD.bazel
  src/file_lists.cmake
Labels: java, cmake, :a: safe for tests, back-port, go
