Repository protocolbuffers/protobuf, pull requests merged in 2025-09, with the labels that each got.

#23373 fix(php): remove "provide" from composer.json
  php/composer.json
  php/composer.json.dist
  php/tests/ComposerJsonTest.php
Labels: php

#23459 [Cherrypick] Restore Protobuf Java extension modifiers in gencode
  src/google/protobuf/compiler/java/full/message_builder.cc
Labels: 32.x

#23547 Add gencode smoke tests
  compatibility/smoke/BUILD.bazel
  compatibility/smoke/CHECKED_IN_GENCODE_BUILD.bazel.template
  compatibility/smoke/README.md
  compatibility/smoke/StaleGencodeSmokeTest.java
  compatibility/smoke/add_gencode.sh
  compatibility/smoke/proto3_gencode_test.proto
  compatibility/smoke/stale_gencode_smoke_test.bzl
  compatibility/smoke/v3.19.0/BUILD.bazel
  compatibility/smoke/v3.19.0/legacy_gencode_test/proto3/Proto3GencodeTestProto.java
Labels: :a: safe for tests
